"use client";

import { Copy, FileCode2, Hash, KeyRound, RefreshCw, Type, CalendarDays } from "lucide-react";
import { useState } from "react";

type Tab = "text" | "json" | "password" | "hash" | "date";
const tabs: { id: Tab; label: string; icon: typeof Type }[] = [{ id: "text", label: "Text", icon: Type }, { id: "json", label: "JSON", icon: FileCode2 }, { id: "password", label: "Password", icon: KeyRound }, { id: "hash", label: "SHA-256", icon: Hash }, { id: "date", label: "Dates", icon: CalendarDays }];
function copy(value: string) { void navigator.clipboard.writeText(value); }
function password(length: number) { const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*"; const values = new Uint32Array(length); crypto.getRandomValues(values); return Array.from(values, (value) => alphabet[value % alphabet.length]).join(""); }

export default function EverydayStudio() {
  const [tab, setTab] = useState<Tab>("text"); const [text, setText] = useState(""); const [json, setJson] = useState('{\n  "hello": "world"\n}'); const [jsonStatus, setJsonStatus] = useState("Paste JSON to format, minify, or validate it."); const [secret, setSecret] = useState(() => password(20)); const [length, setLength] = useState(20); const [hashInput, setHashInput] = useState(""); const [hash, setHash] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState("");
  const words = text.trim() ? text.trim().split(/\s+/).length : 0; const lines = text ? text.split("\n").length : 0;
  const formatJson = (compact = false) => { try { setJson(JSON.stringify(JSON.parse(json), null, compact ? undefined : 2)); setJsonStatus(compact ? "Valid JSON, compacted." : "Valid JSON, formatted."); } catch (error) { setJsonStatus(`Invalid JSON: ${error instanceof Error ? error.message : "unknown error"}`); } };
  const digest = async () => { const bytes = new TextEncoder().encode(hashInput); const result = await crypto.subtle.digest("SHA-256", bytes); setHash(Array.from(new Uint8Array(result), (byte) => byte.toString(16).padStart(2, "0")).join("")); };
  const days = start && end ? Math.abs(Math.round((new Date(`${end}T00:00:00`).getTime() - new Date(`${start}T00:00:00`).getTime()) / 86400000)) : null;
  return <div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-2xl shadow-slate-950/10 dark:border-white/10 dark:bg-slate-900 sm:p-7"><div className="flex flex-wrap gap-2">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold ${tab === id ? "bg-violet-700 text-white" : "bg-slate-100 text-slate-700 dark:bg-white/5 dark:text-slate-200"}`}><Icon size={15} /> {label}</button>)}</div>
    {tab === "text" && <div className="mt-6"><h2 className="text-2xl font-black">Text cleaner and counter</h2><p className="mt-1 text-sm text-slate-500">Count exactly, change case, and remove extra whitespace.</p><textarea value={text} onChange={(e) => setText(e.target.value)} rows={10} placeholder="Paste text here…" className="mt-5 w-full rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm dark:border-white/10 dark:bg-white/5" /><div className="mt-3 flex flex-wrap gap-2 text-sm"><span className="rounded-lg bg-slate-100 px-3 py-2 dark:bg-white/5">{words} words</span><span className="rounded-lg bg-slate-100 px-3 py-2 dark:bg-white/5">{text.length} characters</span><span className="rounded-lg bg-slate-100 px-3 py-2 dark:bg-white/5">{lines} lines</span></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setText(text.toUpperCase())} className="rounded-lg border px-3 py-2 text-sm font-bold">UPPERCASE</button><button onClick={() => setText(text.toLowerCase())} className="rounded-lg border px-3 py-2 text-sm font-bold">lowercase</button><button onClick={() => setText(text.replace(/\s+/g, " ").trim())} className="rounded-lg border px-3 py-2 text-sm font-bold">Clean spaces</button><button onClick={() => copy(text)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-bold"><Copy size={14} /> Copy</button></div></div>}
    {tab === "json" && <div className="mt-6"><h2 className="text-2xl font-black">JSON formatter and validator</h2><textarea value={json} onChange={(e) => setJson(e.target.value)} spellCheck={false} rows={12} className="mt-5 w-full rounded-xl border border-slate-200 bg-slate-950 p-4 font-mono text-sm text-emerald-300 dark:border-white/10" /><p className="mt-2 text-sm text-slate-500">{jsonStatus}</p><div className="mt-4 flex gap-2"><button onClick={() => formatJson()} className="rounded-lg bg-violet-700 px-3 py-2 text-sm font-bold text-white">Format</button><button onClick={() => formatJson(true)} className="rounded-lg border px-3 py-2 text-sm font-bold">Minify</button><button onClick={() => copy(json)} className="rounded-lg border px-3 py-2 text-sm font-bold">Copy</button></div></div>}
    {tab === "password" && <div className="mt-6"><h2 className="text-2xl font-black">Secure password generator</h2><p className="mt-1 text-sm text-slate-500">Generated with your browser’s cryptographic random source.</p><div className="mt-5 rounded-xl bg-slate-950 p-4 font-mono text-lg break-all text-emerald-300">{secret}</div><label className="mt-5 block text-sm font-bold">Length: {length}<input type="range" min="12" max="64" value={length} onChange={(e) => setLength(Number(e.target.value))} className="mt-2 w-full accent-violet-700" /></label><div className="mt-4 flex gap-2"><button onClick={() => setSecret(password(length))} className="inline-flex items-center gap-2 rounded-lg bg-violet-700 px-3 py-2 text-sm font-bold text-white"><RefreshCw size={15} /> Generate</button><button onClick={() => copy(secret)} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-bold"><Copy size={15} /> Copy</button></div></div>}
    {tab === "hash" && <div className="mt-6"><h2 className="text-2xl font-black">SHA-256 text hash</h2><p className="mt-1 text-sm text-slate-500">Create an exact fingerprint for text, locally.</p><textarea value={hashInput} onChange={(e) => setHashInput(e.target.value)} rows={6} className="mt-5 w-full rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm dark:border-white/10 dark:bg-white/5" placeholder="Text to hash…" /><button onClick={() => void digest()} className="mt-4 rounded-lg bg-violet-700 px-3 py-2 text-sm font-bold text-white">Create SHA-256</button>{hash && <div className="mt-4 rounded-xl bg-slate-950 p-4 font-mono text-xs break-all text-emerald-300"><button onClick={() => copy(hash)} className="float-right text-white"><Copy size={15} /></button>{hash}</div>}</div>}
    {tab === "date" && <div className="mt-6"><h2 className="text-2xl font-black">Exact date difference</h2><p className="mt-1 text-sm text-slate-500">Count calendar days between two dates.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Start date<input type="date" value={start} onChange={(e) => setStart(e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-white/10 dark:bg-white/5" /></label><label className="text-sm font-bold">End date<input type="date" value={end} onChange={(e) => setEnd(e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 bg-white p-3 dark:border-white/10 dark:bg-white/5" /></label></div>{days !== null && <p className="mt-6 rounded-xl bg-violet-50 p-5 text-3xl font-black text-violet-950 dark:bg-violet-400/10 dark:text-violet-100">{days.toLocaleString()} days</p>}</div>}
  </div>;
}
