"use client";

import { Download, FilePlus2, GripVertical, LoaderCircle, Trash2 } from "lucide-react";
import { useRef, useState } from "react";
import { PDFDocument } from "pdf-lib";

type Source = { id: string; file: File; pages: number };

export default function PdfMergeStudio() {
  const input = useRef<HTMLInputElement>(null); const [files, setFiles] = useState<Source[]>([]); const [busy, setBusy] = useState(false); const [status, setStatus] = useState("Add two or more PDFs. They never leave your browser.");
  async function addFiles(picked: FileList | null) { if (!picked?.length) return; setBusy(true); try { const additions = await Promise.all(Array.from(picked).filter((f) => f.type === "application/pdf").map(async (file) => ({ id: crypto.randomUUID(), file, pages: (await PDFDocument.load(await file.arrayBuffer())).getPageCount() }))); setFiles((old) => [...old, ...additions]); setStatus(`${additions.length} PDF${additions.length === 1 ? "" : "s"} added. Drag-free ordering controls are below.`); } catch { setStatus("One of those PDFs could not be read. Password-protected files are not supported."); } finally { setBusy(false); } }
  function reorder(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= files.length) return; const next = [...files]; [next[index], next[target]] = [next[target], next[index]]; setFiles(next); }
  async function merge() { if (files.length < 2) { setStatus("Add at least two PDFs to merge."); return; } setBusy(true); setStatus("Combining pages locally…"); try { const result = await PDFDocument.create(); for (const source of files) { const doc = await PDFDocument.load(await source.file.arrayBuffer()); const pages = await result.copyPages(doc, doc.getPageIndices()); pages.forEach((page) => result.addPage(page)); } const bytes = await result.save(); download(bytes, "merged.pdf"); setStatus("Merged PDF downloaded."); } catch { setStatus("We could not merge those files. Try PDFs without passwords or restrictions."); } finally { setBusy(false); } }
  return <div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-2xl shadow-slate-950/10 dark:border-white/10 dark:bg-slate-900 sm:p-7"><input ref={input} type="file" accept="application/pdf" multiple className="sr-only" onChange={(e) => void addFiles(e.target.files)} /><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-700 dark:text-violet-300">Local PDF merge</p><h2 className="mt-1 text-2xl font-black text-slate-950 dark:text-white">Combine PDFs in your order</h2></div><button onClick={() => input.current?.click()} disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white disabled:opacity-60 dark:bg-white dark:text-slate-950"><FilePlus2 size={16} /> Add PDFs</button></div><div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-600 dark:border-white/15 dark:bg-white/5 dark:text-slate-300">{busy && <LoaderCircle className="mr-2 inline animate-spin text-violet-600" size={16} />}{status}</div>{files.length > 0 && <div className="mt-5 space-y-2">{files.map((source, index) => <div key={source.id} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-white/10"><GripVertical className="text-slate-400" size={18} /><span className="min-w-0 flex-1 truncate text-sm font-bold">{source.file.name} <span className="font-normal text-slate-500">· {source.pages} pages</span></span><button onClick={() => reorder(index, -1)} disabled={index === 0} className="rounded border px-2 py-1 text-xs disabled:opacity-30">Up</button><button onClick={() => reorder(index, 1)} disabled={index === files.length - 1} className="rounded border px-2 py-1 text-xs disabled:opacity-30">Down</button><button onClick={() => setFiles((old) => old.filter((f) => f.id !== source.id))} className="text-rose-600"><Trash2 size={17} /></button></div>)}</div>}<button onClick={() => void merge()} disabled={busy || files.length < 2} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-violet-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><Download size={16} /> Merge and download</button></div>;
}
function download(bytes: Uint8Array, name: string) { const url = URL.createObjectURL(new Blob([bytes.slice().buffer as ArrayBuffer], { type: "application/pdf" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
