"use client";

import { FileOutput, LoaderCircle, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { PDFDocument } from "pdf-lib";

function pagesFromRange(value: string, max: number) { const pages = new Set<number>(); value.split(",").forEach((part) => { const [from, to = from] = part.trim().split("-").map(Number); if (!Number.isFinite(from) || !Number.isFinite(to)) return; for (let n = Math.max(1, Math.min(from, to)); n <= Math.min(max, Math.max(from, to)); n += 1) pages.add(n); }); return [...pages].sort((a, b) => a - b); }
export default function PdfPageStudio() { const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [count, setCount] = useState(0); const [range, setRange] = useState("1"); const [busy, setBusy] = useState(false); const [status, setStatus] = useState("Select a PDF, then choose pages like 1-3, 5, 8-10.");
  async function pick(next?: File) { if (!next || next.type !== "application/pdf") return; setBusy(true); try { const doc = await PDFDocument.load(await next.arrayBuffer()); setFile(next); setCount(doc.getPageCount()); setRange(`1-${doc.getPageCount()}`); setStatus(`${doc.getPageCount()} pages ready. Export a page range as a new PDF.`); } catch { setStatus("That PDF could not be opened. Password-protected files are not supported."); } finally { setBusy(false); } }
  async function extract() { if (!file) return; const indices = pagesFromRange(range, count).map((p) => p - 1); if (!indices.length) { setStatus("Enter a valid range, such as 1-3, 5."); return; } setBusy(true); try { const inputDoc = await PDFDocument.load(await file.arrayBuffer()); const output = await PDFDocument.create(); const pages = await output.copyPages(inputDoc, indices); pages.forEach((page) => output.addPage(page)); const bytes = await output.save(); const url = URL.createObjectURL(new Blob([bytes.slice().buffer as ArrayBuffer], { type: "application/pdf" })); const link = document.createElement("a"); link.href = url; link.download = `${file.name.replace(/\.pdf$/i, "")}-pages.pdf`; link.click(); URL.revokeObjectURL(url); setStatus("Your selected pages were downloaded."); } catch { setStatus("Those pages could not be exported."); } finally { setBusy(false); } }
  return <div className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-2xl shadow-slate-950/10 dark:border-white/10 dark:bg-slate-900 sm:p-7"><input ref={input} type="file" accept="application/pdf" className="sr-only" onChange={(e) => void pick(e.target.files?.[0])} /><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-700 dark:text-violet-300">PDF page extractor</p><h2 className="mt-1 text-2xl font-black text-slate-950 dark:text-white">Keep only the pages you need</h2></div><button onClick={() => input.current?.click()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white dark:bg-white dark:text-slate-950"><Upload size={16} /> Select PDF</button></div><p className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-600 dark:border-white/15 dark:bg-white/5 dark:text-slate-300">{busy && <LoaderCircle className="mr-2 inline animate-spin text-violet-600" size={16} />}{status}</p><label className="mt-5 block text-sm font-bold">Pages to keep <span className="font-normal text-slate-500">(of {count || "…"})</span><input value={range} onChange={(e) => setRange(e.target.value)} disabled={!file} placeholder="1-3, 5, 8-10" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-normal dark:border-white/10 dark:bg-white/5" /></label><button onClick={() => void extract()} disabled={!file || busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-violet-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><FileOutput size={16} /> Export selected pages</button></div>; }
