"use client";

import { useState, type ReactNode } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import type { PortfolioData, PortfolioProject } from "../template-one/TemplateOne";

type EditField = "name" | "professional-title" | "about-you" | "projects" | "experience" | "skills" | "email";
const has = <T,>(items?: T[]): items is T[] => Boolean(items?.length);

function Editable({ field, onEdit, children, className = "" }: { field: EditField; onEdit?: (field: EditField) => void; children: ReactNode; className?: string }) {
  if (!onEdit) return <div className={className}>{children}</div>;
  return <button type="button" onClick={() => onEdit(field)} className={`group relative block w-full cursor-text text-left outline-none ${className}`} title="Click to edit"><span className="pointer-events-none absolute -inset-x-2 -inset-y-1 rounded opacity-0 ring-2 ring-[rgb(var(--kp-accent))] transition group-hover:opacity-100 group-focus-visible:opacity-100" />{children}</button>;
}

function Section({ id, label, children }: { id: string; label: string; children: ReactNode }) {
  return <section id={id} className="grid grid-cols-12 gap-x-4 px-5 py-20 md:px-10 md:py-28"><h2 className="col-span-12 mb-6 text-lg italic text-[rgb(var(--kp-accent))] md:col-span-2 md:mb-0 md:pt-3">{label}</h2><div className="col-span-12 md:col-span-10">{children}</div></section>;
}

function Work({ project, onEdit }: { project: PortfolioProject; onEdit?: (field: EditField) => void }) {
  const [open, setOpen] = useState(false); const reduce = !!useReducedMotion(); const detailed = Boolean(project.description || project.technologies?.length || project.live_url || project.github);
  return <li className="border-t border-[rgb(var(--kp-ink)/.3)] last:border-b"><button type="button" onClick={() => detailed && setOpen(!open)} className="group flex w-full items-baseline gap-4 py-5 text-left"><span className="kp-display flex-1 text-[clamp(2.25rem,7.5vw,6.5rem)] font-bold leading-[.95] tracking-[-.04em] group-hover:text-[rgb(var(--kp-accent))]">{project.title}</span>{detailed && <span className="kp-display text-3xl text-[rgb(var(--kp-accent))]">{open ? "−" : "+"}</span>}</button><AnimatePresence>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: reduce ? 0 : .35 }} className="overflow-hidden"><Editable field="projects" onEdit={onEdit}><div className="grid gap-5 pb-8 md:grid-cols-12">{project.description && <p className="text-xl leading-snug md:col-span-7">{project.description}</p>}<p className="text-lg italic md:col-span-5">{project.technologies?.join(", ")}</p></div></Editable></motion.div>}</AnimatePresence></li>;
}

export default function KineticPortfolio({ portfolio, embedded = false, onEdit }: { portfolio: PortfolioData; embedded?: boolean; onEdit?: (field: EditField) => void }) {
  const name = portfolio.name?.trim() || "Your Name"; const intro = portfolio.summary?.filter(Boolean).join(" ") || portfolio.tagline || "Add your story in the portfolio editor.";
  return <div className={`kinetic-portfolio relative isolate min-h-full overflow-hidden ${embedded ? "min-h-[900px]" : "min-h-screen"}`}><main className={embedded ? "" : "md:pl-14"}><header className="flex min-h-[100svh] flex-col justify-between px-5 pb-16 pt-8 md:px-10 md:pb-20"><Editable field="professional-title" onEdit={onEdit} className="text-lg italic">{portfolio.professional_title || "Your professional title"}</Editable><Editable field="name" onEdit={onEdit} className="my-10"><h1 className="kp-display text-[clamp(4rem,17.5vw,21rem)] font-extrabold leading-[.84] tracking-[-.055em]">{name.split(/\s+/).map((word, index) => <span key={`${word}-${index}`} className={`block w-fit ${index % 2 ? "ml-auto md:ml-[18vw]" : ""}`}>{word}</span>)}</h1></Editable><Editable field="about-you" onEdit={onEdit} className="max-w-[34ch] text-[clamp(1.4rem,2.5vw,2.4rem)] leading-[1.2] md:ml-[calc(41.666%+1rem)]">{intro}</Editable></header>{has(portfolio.projects) && <Section id="work" label="Work"><ul>{portfolio.projects.map((project, index) => <Work key={`${project.title}-${index}`} project={project} onEdit={onEdit} />)}</ul></Section>}{has(portfolio.experience) && <Section id="path" label="Path"><Editable field="experience" onEdit={onEdit}><ul className="space-y-10">{portfolio.experience.map((role, index) => <li key={`${role.company}-${index}`} className="grid gap-x-4 md:grid-cols-10"><p className="text-lg italic md:col-span-3">{[role.start_date, role.end_date].filter(Boolean).join(" – ")}</p><div className="md:col-span-7"><p className="kp-display text-[clamp(1.75rem,3.6vw,3.25rem)] font-bold leading-none">{role.company}</p><p className="mt-2 text-xl italic">{role.job_title}</p></div></li>)}</ul></Editable></Section>}{has(portfolio.skills) && <Section id="tools" label="Tools"><Editable field="skills" onEdit={onEdit}><ul className="kp-display flex flex-wrap gap-x-3 text-[clamp(2rem,5.5vw,5rem)] font-semibold">{portfolio.skills.map((skill) => <li key={skill}>{skill}<span className="ml-3 font-serif font-normal italic text-[rgb(var(--kp-accent))]">/</span></li>)}</ul></Editable></Section>}<Section id="contact" label="Contact"><Editable field="email" onEdit={onEdit}><a href={onEdit ? undefined : `mailto:${portfolio.email || "hello@example.com"}`} className="kp-display block text-[clamp(1.75rem,7.2vw,7.5rem)] font-bold leading-none [overflow-wrap:anywhere]">{portfolio.email || "hello@example.com"}</a></Editable></Section></main></div>;
}
