import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Code2, FileOutput, FilePlus2, FileSearch, FileText, ImageIcon, KeyRound, LockKeyhole, Sparkles, WandSparkles } from "lucide-react";
import PdfToImageStudio from "@/components/tools/PdfToImageStudio";

export const metadata: Metadata = { title: "Free document tools", description: "Convert PDF pages to PNG locally, extract CV details, and explore privacy-first document tools from Formora." };

const plannedTools = [
  { icon: FileText, title: "PDF to text", description: "Pull editable text from digital PDFs and scanned documents.", state: "Available in CV extractor", href: "/DetailExtractorPage" },
  { icon: FileSearch, title: "CV detail extractor", description: "Turn your CV into structured details ready for a portfolio.", state: "Open workspace", href: "/DetailExtractorPage" },
  { icon: ImageIcon, title: "Image to text", description: "Read text from screenshots and scans with OCR.", state: "Available in CV extractor", href: "/DetailExtractorPage" },
  { icon: WandSparkles, title: "PDF editor", description: "Replace visible text, annotate, draw, and save an edited PDF.", state: "Open editor", href: "/tools/pdf-editor" },
  { icon: FilePlus2, title: "Merge PDF", description: "Combine PDFs in any order and download one file.", state: "Merge files", href: "/tools/merge-pdf" },
  { icon: FileOutput, title: "Extract PDF pages", description: "Keep selected pages or make a smaller PDF.", state: "Extract pages", href: "/tools/extract-pdf-pages" },
  { icon: ImageIcon, title: "Background remover", description: "Remove a simple photo background or export a larger image.", state: "Edit image", href: "/tools/image-tools" },
  { icon: KeyRound, title: "Everyday toolbox", description: "Format JSON, count text, make secure passwords, hashes, and date calculations.", state: "Open toolbox", href: "/tools/everyday-toolbox" },
  { icon: Code2, title: "Developer tools", description: "JSON, Base64, JWT, UUID, regex and Unix timestamp tools for exact local work.", state: "Open dev tools", href: "/tools/developer-tools" },
];

export default function ToolsPage() {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [{ "@type": "Question", name: "Are Formora tools free?", acceptedAnswer: { "@type": "Answer", text: "Yes. The available PDF, image, everyday, and developer tools are free to use without an account." } }, { "@type": "Question", name: "Are my files uploaded?", acceptedAnswer: { "@type": "Answer", text: "The browser-based PDF and image tools process files on your device. Developer utilities also transform pasted data locally." } }, { "@type": "Question", name: "Which PDF tasks can I complete?", acceptedAnswer: { "@type": "Answer", text: "You can convert PDF pages to PNG, edit visible text and annotations, merge PDF files, and extract a selected range of pages." } }, { "@type": "Question", name: "What developer tools are available?", acceptedAnswer: { "@type": "Answer", text: "The developer hub includes JSON formatting and validation, URL and Base64 conversion, JWT decoding, UUID generation, Unix time conversion, and regex testing." } }] };
  return <div className="overflow-hidden bg-[color:var(--background)]"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c") }} />
    <section className="relative border-b border-slate-200 px-5 py-16 dark:border-white/10 sm:px-6 sm:py-24"><div className="pointer-events-none absolute inset-0 -z-0 bg-[radial-gradient(circle_at_76%_20%,rgba(124,58,237,0.16),transparent_28rem),radial-gradient(circle_at_12%_65%,rgba(34,197,94,0.11),transparent_24rem)]" /><div className="relative mx-auto max-w-7xl"><p className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-violet-800 dark:border-violet-400/20 dark:bg-violet-400/10 dark:text-violet-200"><Sparkles size={14} /> Free, browser-first tools</p><div className="mt-7 grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-end"><div><h1 className="max-w-3xl text-5xl font-black leading-[0.94] tracking-[-0.065em] text-slate-950 dark:text-white sm:text-7xl">Files in.<br /><span className="text-violet-700 dark:text-violet-300">Useful work</span> out.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">A growing collection of simple document tools. No account for the basics, no clutter, and clear privacy boundaries.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#convert" className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-violet-800 dark:bg-white dark:text-slate-950">Try PDF to PNG</a><Link href="/DetailExtractorPage" className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold text-slate-800 transition hover:border-violet-400 dark:border-white/15 dark:text-white">Extract CV details</Link></div></div><div className="grid grid-cols-2 gap-3 text-sm"><div className="rounded-2xl border border-slate-200 bg-white/70 p-5 backdrop-blur dark:border-white/10 dark:bg-white/5"><LockKeyhole className="text-violet-700 dark:text-violet-300" size={21} /><p className="mt-6 font-bold text-slate-950 dark:text-white">Local by default</p><p className="mt-1 text-slate-600 dark:text-slate-400">Your converter files stay in your browser.</p></div><div className="mt-8 rounded-2xl bg-slate-950 p-5 text-white dark:bg-violet-200 dark:text-slate-950"><p className="text-3xl font-black">$0</p><p className="mt-6 font-bold">Core tools are free</p><p className="mt-1 opacity-70">No account required for PDF to PNG.</p></div></div></div></div></section>
    <section id="convert" className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-24"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-700 dark:text-violet-300">Tool 01</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-4xl">Convert without sending.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-600 dark:text-slate-400">A focused, browser-only PDF renderer. Choose a file, preview each page, and save PNGs individually.</p></div><PdfToImageStudio /></section>
    <section className="border-y border-slate-200 bg-slate-50 px-5 py-16 dark:border-white/10 dark:bg-white/[0.03] sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-700 dark:text-violet-300">A useful, honest toolbox</p><h2 className="mt-3 max-w-2xl text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-4xl">Fast free tools for the jobs people do every day.</h2><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{plannedTools.map((tool) => { const Icon = tool.icon; const content = <><Icon size={21} className="text-violet-700 dark:text-violet-300" /><p className="mt-8 text-lg font-black text-slate-950 dark:text-white">{tool.title}</p><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{tool.description}</p><p className="mt-6 flex items-center gap-1 text-xs font-bold uppercase tracking-[0.12em] text-violet-700 dark:text-violet-300">{tool.state}{tool.href && <ArrowRight size={14} />}</p></>; return tool.href ? <Link key={tool.title} href={tool.href} className="rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-1 hover:border-violet-300 hover:shadow-lg dark:border-white/10 dark:bg-slate-900">{content}</Link> : <div key={tool.title} className="rounded-2xl border border-dashed border-slate-300 bg-white/60 p-6 dark:border-white/15 dark:bg-white/5">{content}</div>; })}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-6 sm:py-24"><div className="grid gap-10 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-700 dark:text-violet-300">How it works</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Made for the small jobs that hold up your day.</h2></div><ol className="space-y-5">{["Choose a focused tool instead of a crowded all-in-one dashboard.", "Drop in a file or paste data and see exactly what happens to it.", "Download your result, copy the output, or move on to your portfolio workspace."].map((step, index) => <li key={step} className="flex gap-4 border-b border-slate-200 pb-5 text-slate-700 dark:border-white/10 dark:text-slate-300"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-violet-100 text-xs font-black text-violet-800 dark:bg-violet-400/15 dark:text-violet-200">0{index + 1}</span><span className="pt-0.5 leading-6">{step}</span></li>)}</ol></div><div className="mt-16 max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-700 dark:text-violet-300">What Formora does</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 dark:text-white">Free online tools for documents, images, data, and development.</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-400">Formora is a privacy-first toolbox for practical work. Use it to merge and split PDFs, turn PDF pages into images, edit visible PDF text, remove simple image backgrounds, increase image size, clean up text, or handle exact developer transformations. We focus on tasks where speed, a clear result, and keeping files on your own device matter more than an AI-generated answer.</p><p className="mt-4 leading-7 text-slate-600 dark:text-slate-400">Each tool explains what it does and its limits. File tools work in your browser whenever possible; developer tools do not execute pasted code or verify private credentials. That makes Formora useful for everyday personal documents, freelance work, portfolio preparation, and routine engineering tasks.</p></div></section>
  </div>;
}
