import { role } from "./types";

/** Law, money, people, property, marketing and public service. Prices follow each base persona’s location. */
const SRA: [string, string, string] = ["Admitted as a solicitor", "Solicitors Regulation Authority", "2010"];

export const BUSINESS_ROLES = [
  // ——— Law (Manchester, £) ———
  role("corporate-lawyer", "Corporate Lawyer", "corporate lawyers", "legal", ["commercial lawyer", "M&A lawyer", "business lawyer", "corporate solicitor"], {
    title: "Corporate Solicitor & Partner", tagline: "Deals done properly, explained without the jargon.",
    bio: ["I advise founders, investors and family businesses on buying and selling companies, investment rounds and shareholder agreements.", "I tell clients what matters in a contract and what they can safely ignore."],
    skills: "Mergers & acquisitions · Venture capital · Shareholder agreements · Company sales · Due diligence · Commercial contracts",
    services: [["Investment round", "Term sheet to completion for a seed or Series A round.", "From £9,500 + VAT"], ["Shareholder agreement", "Drafted for your company.", "Fixed £2,400 + VAT"], ["Contract review", "Written advice within three working days.", "From £450 + VAT"]],
    stats: [["£640m", "of deals completed"], ["120+", "transactions"], ["15", "years in practice"]],
    quote: ["Priya got our sale over the line without a single surprise. Calm, quick and always on our side.", "Founder", "Company sale, 2024"],
    experience: [["Partner, Corporate", "Halden Raman LLP", "2019", "Present"], ["Senior Associate, Corporate", "Broadgate Clarke", "2012", "2019"]],
    education: [["LLB Law", "University of Manchester", "2006"], SRA],
  }, ["brief", "prospectus"]),
  role("criminal-defence-lawyer", "Criminal Defence Lawyer", "criminal defence lawyers", "legal", ["criminal lawyer", "defense attorney", "criminal solicitor", "police station representative"], {
    title: "Criminal Defence Solicitor", tagline: "Arrested or under investigation? Call me first.",
    bio: ["I represent people at the police station and in court, from driving offences to serious fraud.", "I answer my phone at night, and I tell clients the truth about their chances."],
    skills: "Police station advice · Magistrates’ court · Crown Court · Driving offences · Fraud · Youth justice · Higher Rights of Audience",
    services: [["Police station attendance", "Free under legal aid; private representation available.", "Free / from £600"], ["Driving offence defence", "Fixed fee for a guilty plea and mitigation.", "From £950 + VAT"], ["Crown Court defence", "Fixed fee agreed after reviewing the evidence.", "Quote"]],
    stats: [["24/7", "police station cover"], ["1,800+", "clients represented"], ["16", "years in practice"]],
    quote: ["She answered at 2am and got me home by breakfast. I’ll never forget it.", "Client", "Police station advice"],
    experience: [["Criminal Defence Solicitor", "Raman & Co. Criminal Defence", "2018", "Present"], ["Solicitor", "Northern Defence Partnership", "2010", "2018"]],
    education: [SRA, ["Higher Rights of Audience (Criminal)", "SRA", "2014"]],
    availability: "Emergency line open 24 hours",
  }, ["brief", "site-board"]),
  role("family-lawyer", "Family Lawyer", "family lawyers", "legal", ["divorce lawyer", "family solicitor", "child custody lawyer", "family law"], {
    title: "Family Solicitor & Mediator", tagline: "Divorce and separation handled with care, and without unnecessary fights.",
    bio: ["I help people through divorce, separation, arrangements for children and dividing money and property.", "I’m also a trained mediator, so I always look for agreements that keep you out of court."],
    skills: "Divorce · Financial settlements · Child arrangements · Prenuptial agreements · Mediation · Cohabitation disputes",
    services: [["First meeting", "An hour to understand your situation and options.", "£150 + VAT"], ["Uncontested divorce", "From application to final order.", "Fixed £950 + VAT"], ["Mediation session", "Ninety minutes, per person.", "£140 + VAT"]],
    stats: [["700+", "families helped"], ["85%", "settled without court"], ["Resolution", "accredited specialist"]],
    quote: ["She kept things calm when I couldn’t. My children barely noticed the change.", "Client", "Separation, 2024"],
    experience: [["Family Solicitor & Mediator", "Halden Raman LLP", "2017", "Present"], ["Solicitor, Family", "Pennine Law", "2010", "2017"]],
    education: [SRA, ["Accredited Family Mediator", "Family Mediation Council", "2016"]],
  }, ["brief", "sanctuary"]),
  role("immigration-lawyer", "Immigration Lawyer", "immigration lawyers", "legal", ["visa lawyer", "immigration solicitor", "immigration adviser", "asylum lawyer"], {
    title: "Immigration Solicitor", tagline: "Clear advice on visas, settlement and citizenship, in your language.",
    bio: ["I help families, students, workers and employers with visas, settlement, citizenship and appeals.", "I speak English, Tamil and Hindi, and I give every client a written checklist so nothing is missed."],
    skills: "Skilled worker visas · Family visas · Settlement (ILR) · British citizenship · Appeals · Sponsor licences",
    services: [["Visa consultation", "An hour on your options, with written advice.", "£180 + VAT"], ["Spouse visa application", "Full preparation and submission.", "Fixed £1,600 + VAT"], ["Sponsor licence", "For employers hiring from abroad.", "Fixed £2,200 + VAT"]],
    stats: [["2,000+", "applications"], ["97%", "success rate"], ["3", "languages"]],
    quote: ["After two refusals elsewhere, Priya got my wife’s visa approved in six weeks.", "Client", "Spouse visa"],
    experience: [["Immigration Solicitor", "Halden Raman LLP", "2018", "Present"], ["Immigration Caseworker", "North West Law Centre", "2011", "2018"]],
    education: [SRA],
  }, ["brief", "practice"]),
  role("property-lawyer", "Conveyancing Solicitor", "conveyancing solicitors", "legal", ["conveyancer", "property lawyer", "real estate attorney", "property solicitor"], {
    title: "Residential Conveyancing Solicitor", tagline: "Buying or selling a home, with updates you don’t have to chase.",
    bio: ["I handle house purchases, sales and remortgages across England and Wales.", "You’ll get one named solicitor, a fixed fee and an update every week until you have the keys."],
    skills: "Purchases · Sales · Remortgages · Leasehold · New builds · Transfers of equity · Shared ownership",
    services: [["Purchase", "Freehold house, up to £500k.", "Fixed £1,150 + VAT"], ["Sale", "Freehold house.", "Fixed £950 + VAT"], ["Remortgage", "Including searches.", "Fixed £550 + VAT"]],
    stats: [["3,400", "completions"], ["9", "weeks average purchase"], ["4.9★", "from 900 reviews"]],
    quote: ["The only part of buying our house that didn’t stress us out.", "Buyers", "Purchase, 2025"],
    experience: [["Conveyancing Solicitor", "Halden Raman LLP", "2016", "Present"], ["Conveyancer", "Pennine Law", "2010", "2016"]],
    education: [SRA],
  }, ["brief", "open-house"]),
  role("barrister", "Barrister", "barristers", "legal", ["counsel", "advocate", "trial lawyer", "litigator"], {
    title: "Barrister, Employment & Commercial", tagline: "Advocacy that is prepared, persuasive and clear.",
    bio: ["I appear in the Employment Tribunal, County Court and High Court, and advise on merits and strategy before proceedings start.", "Solicitors instruct me because I’m easy to reach and my advice is practical."],
    skills: "Advocacy · Employment tribunals · Commercial disputes · Advice on merits · Drafting pleadings · Mediation advocacy",
    services: [["Advice on merits", "Written opinion within seven days.", "Quote"], ["Hearing", "Brief fee agreed in advance.", "Quote"], ["Direct access", "Members of the public may instruct me directly.", "Quote"]],
    stats: [["14", "years’ call"], ["Ranked", "in independent directories"], ["Direct access", "qualified"]],
    quote: ["Priya’s cross-examination won the case. The judgment quotes her closing submissions twice.", "Instructing solicitor", "Employment Tribunal"],
    experience: [["Barrister", "St John Street Chambers", "2011", "Present"]],
    education: [["Bar Professional Training Course", "The City Law School", "2010"], ["Called to the Bar", "Middle Temple", "2011"]],
  }, ["brief", "broadsheet"]),
  role("paralegal", "Paralegal", "paralegals", "legal", ["legal assistant", "trainee solicitor", "legal secretary", "law graduate"], {
    title: "Paralegal, Employment", tagline: "Organised, accurate and ready for a training contract.",
    bio: ["I support an employment team of five: preparing bundles, drafting letters, managing deadlines and taking first instructions from clients.", "I’m studying for the SQE and looking for a training contract."],
    skills: "Legal research · Bundles · Drafting · Case management · Client intake · Deadlines · Microsoft 365 · Practical Law",
    services: [["Bundle preparation", "Hearing bundles, indexed and paginated.", ""], ["Legal research", "Case law and practice notes.", ""], ["Client intake", "First calls and file opening.", ""]],
    stats: [["300+", "files supported"], ["SQE1", "passed"], ["2", "languages"]],
    quote: ["Reliable, sharp and calm under deadlines. She’ll be an excellent solicitor.", "Partner", "Halden Raman LLP"],
    experience: [["Paralegal", "Halden Raman LLP", "2023", "Present"], ["Legal Administrator", "Pennine Law", "2022", "2023"]],
    education: [["LLB Law", "University of Leeds", "2022"], ["SQE1", "Solicitors Regulation Authority", "2025"]],
    name: "Priya Raman", availability: "Seeking a training contract for 2026",
  }, ["brief", "syllabus"]),

  // ——— Finance (London, £) ———
  role("accountant", "Accountant", "accountants", "finance", ["chartered accountant", "CPA", "small business accountant", "ACA", "ACCA"], {
    title: "Chartered Accountant", tagline: "Accounts done on time, and advice that saves you money.",
    bio: ["I look after the accounts, tax and payroll for 90 small businesses and freelancers in London.", "Clients get a fixed monthly fee, a named accountant and answers within one working day."],
    skills: "Annual accounts · Corporation tax · VAT · Payroll · Self assessment · Xero · Management accounts",
    services: [["Sole trader package", "Bookkeeping review, tax return and advice.", "From £60 / month"], ["Limited company package", "Accounts, corporation tax, payroll and VAT.", "From £180 / month"], ["One-off tax return", "Self assessment.", "£295"]],
    stats: [["90", "clients"], ["100%", "filed on time"], ["1 day", "response time"]],
    quote: ["Henrik saved us more in the first year than he’ll charge us in ten.", "Founder", "Client"],
    experience: [["Founder", "Larsen Accounting", "2019", "Present"], ["Audit Manager", "Deloitte", "2012", "2019"]],
    education: [["Chartered Accountant (ACA)", "ICAEW", "2012"]],
  }, ["prospectus", "practice"]),
  role("bookkeeper", "Bookkeeper", "bookkeepers", "finance", ["bookkeeping", "accounts assistant", "payroll bureau"], {
    title: "Bookkeeper & Payroll", tagline: "Tidy books every month, so tax time is boring.",
    bio: ["I keep the books for 40 small businesses: bank reconciliations, invoicing, payroll and VAT returns.", "I send every client a one-page summary each month so they know exactly where they stand."],
    skills: "Bookkeeping · Bank reconciliation · Payroll · VAT returns · Credit control · Xero · QuickBooks · Dext",
    services: [["Monthly bookkeeping", "Up to 100 transactions a month.", "From £120 / month"], ["Payroll", "Per employee, per month.", "£8"], ["Catch-up bookkeeping", "When things have got behind.", "£35 / hour"]],
    stats: [["40", "businesses"], ["Xero", "certified advisor"], ["Monthly", "one-page reports"]],
    quote: ["I finally understand my numbers, and I never miss a VAT deadline.", "Café owner", "Client"],
    experience: [["Bookkeeper", "Larsen Books", "2018", "Present"], ["Accounts Assistant", "Kontor Software", "2014", "2018"]],
    education: [["AAT Level 4", "Association of Accounting Technicians", "2016"]],
  }, ["prospectus", "practice"]),
  role("financial-adviser", "Financial Adviser", "financial advisers", "finance", ["financial planner", "financial advisor", "wealth manager", "IFA", "retirement planner"], {
    title: "Chartered Financial Planner", tagline: "A plan for your money, written down and reviewed every year.",
    bio: ["I help families plan for retirement, school fees and passing on wealth, and I explain every recommendation in writing.", "I’m independent and paid by fees, not commissions."],
    skills: "Retirement planning · Pensions · Investments · Inheritance tax · Protection · Cash-flow modelling",
    services: [["First meeting", "Ninety minutes, no obligation.", "Free"], ["Financial plan", "Cash-flow model and written recommendations.", "From £1,800"], ["Ongoing advice", "Annual review and rebalancing.", "0.6% a year"]],
    stats: [["£180m", "advised assets"], ["140", "families"], ["Chartered", "financial planner"]],
    quote: ["For the first time, we know when we can retire, and that we’ll be fine.", "Clients", "Retirement plan"],
    experience: [["Chartered Financial Planner", "Larsen Wealth", "2018", "Present"], ["Paraplanner", "St Ives Wealth", "2013", "2018"]],
    education: [["Chartered Financial Planner", "Chartered Insurance Institute", "2018"]],
  }, ["prospectus", "practice"]),
  role("tax-adviser", "Tax Adviser", "tax advisers", "finance", ["tax consultant", "chartered tax adviser", "CTA", "tax accountant"], {
    title: "Chartered Tax Adviser", tagline: "Tax planning that is clever, legal and explained simply.",
    bio: ["I advise business owners, landlords and people moving to or from the UK on income tax, capital gains and inheritance tax.", "I also deal with HMRC enquiries, so you don’t have to."],
    skills: "Personal tax · Capital gains · Inheritance tax · Property tax · Residency · HMRC enquiries · R&D tax credits",
    services: [["Tax consultation", "An hour, with a written summary.", "£250"], ["Property tax review", "For landlords with two or more properties.", "From £900"], ["HMRC enquiry", "Representation from first letter to closure.", "Quote"]],
    stats: [["14", "years advising"], ["£11m", "client tax saved"], ["CTA", "qualified"]],
    quote: ["Henrik handled our HMRC enquiry calmly and it closed with no additional tax.", "Landlord", "Client"],
    experience: [["Chartered Tax Adviser", "Larsen Tax", "2019", "Present"], ["Tax Manager", "Deloitte", "2012", "2019"]],
    education: [["Chartered Tax Adviser (CTA)", "Chartered Institute of Taxation", "2014"]],
  }, ["prospectus", "brief"]),
  role("mortgage-broker", "Mortgage Broker", "mortgage brokers", "finance", ["mortgage adviser", "mortgage advisor", "loan officer", "home loans"], {
    title: "Mortgage Adviser", tagline: "The right mortgage, found and handled from offer to keys.",
    bio: ["I help first-time buyers, movers and self-employed people find mortgages from more than 90 lenders.", "I handle the paperwork and chase the lender, so you don’t have to."],
    skills: "First-time buyers · Remortgages · Self-employed mortgages · Buy-to-let · Protection insurance",
    services: [["Mortgage advice", "Search, application and support to completion.", "£499"], ["Remortgage", "Reviewed six months before your deal ends.", "£299"], ["Protection review", "Life and income cover.", "Free"]],
    stats: [["1,100", "mortgages arranged"], ["90+", "lenders"], ["4.9★", "from 480 reviews"]],
    quote: ["Self-employed, with two years of accounts. Henrik found us a mortgage when the bank said no.", "First-time buyers", "Client"],
    experience: [["Mortgage Adviser", "Larsen Mortgages", "2017", "Present"], ["Mortgage Adviser", "High Street Bank", "2012", "2017"]],
    education: [["CeMAP", "London Institute of Banking & Finance", "2012"]],
  }, ["prospectus", "open-house"]),
  role("auditor", "Auditor", "auditors", "finance", ["audit manager", "internal auditor", "external auditor", "risk and assurance"], {
    title: "Audit Manager", tagline: "Independent, thorough and easy to work with.",
    bio: ["I lead external audits for mid-sized companies and charities, from planning to signing the opinion.", "I find issues early and explain them clearly, so the finance team isn’t surprised at the end."],
    skills: "External audit · Internal controls · IFRS · UK GAAP · Charity audit · Risk assessment · Data analytics",
    services: [["Statutory audit", "For companies and charities.", "Quote"], ["Controls review", "Where your processes could fail.", "From £3,500"], ["Audit readiness", "Preparation before your first audit.", "From £2,000"]],
    stats: [["70+", "audits led"], ["£2bn", "of revenue audited"], ["ACA", "qualified"]],
    quote: ["The smoothest audit we’ve had. Henrik’s team asked for everything once, clearly and early.", "Finance Director", "Audit client"],
    experience: [["Audit Manager", "Deloitte", "2017", "Present"], ["Audit Senior", "Deloitte", "2012", "2017"]],
    education: [["Chartered Accountant (ACA)", "ICAEW", "2012"]],
  }, ["prospectus", "datasheet"]),
  role("financial-analyst", "Financial Analyst", "financial analysts", "finance", ["FP&A analyst", "investment analyst", "equity analyst", "finance analyst"], {
    title: "Senior FP&A Analyst", tagline: "Models people trust and forecasts that come true.",
    bio: ["I build the budget, forecast and board reporting for a 300-person software company.", "My forecasts have landed within 3% of actuals for eight quarters running."],
    skills: "Financial modelling · Forecasting · Budgeting · Variance analysis · SQL · Excel · Power BI · Board reporting",
    services: [["Three-statement model", "Built for fundraising or planning.", ""], ["Board pack", "Monthly reporting template and commentary.", ""], ["Forecast review", "How accurate your forecast really is.", ""]],
    stats: [["±3%", "forecast accuracy"], ["8", "quarters running"], ["CFA", "Level II"]],
    quote: ["Henrik’s models are the ones the board actually reads.", "CFO", "Kontor Software"],
    experience: [["Senior FP&A Analyst", "Kontor Software", "2021", "Present"], ["Financial Analyst", "Fable Foods", "2018", "2021"]],
    education: [["MSc Finance", "Copenhagen Business School", "2018"]],
  }, ["prospectus", "signal"]),

  // ——— People & recruiting (Berlin, €) ———
  role("recruiter", "Recruiter", "recruiters", "hr", ["recruitment consultant", "talent acquisition", "headhunter", "technical recruiter", "agency recruiter"], {
    title: "Technical Recruiter", tagline: "Great engineers, hired quickly and kindly.",
    bio: ["I recruit engineers and product people for growing tech companies in Berlin and across Europe.", "Candidates hear back from me within two days, every time."],
    skills: "Technical recruiting · Sourcing · Interviewing · Offer negotiation · Employer branding · Greenhouse · LinkedIn Recruiter",
    services: [["Contingent search", "You pay only when someone starts.", "18% of salary"], ["Embedded recruiter", "Three days a week in your team.", "From €5,500 / month"], ["Interview training", "Half day for hiring managers.", "€1,200"]],
    stats: [["220", "hires"], ["31", "days median time to hire"], ["92%", "offer acceptance"]],
    quote: ["Ruth found our first three engineers in six weeks, and all three are still here.", "Founder", "Client"],
    experience: [["Technical Recruiter", "Independent", "2021", "Present"], ["Talent Acquisition Partner", "N26", "2016", "2021"]],
    education: [["MA Sociology", "Freie Universität Berlin", "2015"]],
  }, ["rolodex", "quota"]),
  role("hr-business-partner", "HR Business Partner", "HR business partners", "hr", ["HRBP", "people partner", "HR generalist", "HR advisor"], {
    title: "Senior People Partner", tagline: "Helping managers manage well, and people do their best work.",
    bio: ["I partner with leaders across engineering and product on performance, restructures, pay and employee relations.", "I bring data to people decisions and common sense to policies."],
    skills: "Employee relations · Performance management · Organisation design · Reward · Coaching · German labour law",
    services: [["Fractional HR partner", "Two days a week.", "From €3,800 / month"], ["Performance framework", "Reviews and career levels.", "€6,500"], ["Restructure support", "Planning and consultation.", "Quote"]],
    stats: [["500", "employees supported"], ["−38%", "regretted attrition"], ["12", "managers coached"]],
    quote: ["Ruth helped me through my hardest decision as a manager, with care for everyone involved.", "Engineering Director", "Talo"],
    experience: [["Senior People Partner", "Talo", "2020", "Present"], ["HR Business Partner", "N26", "2016", "2020"]],
    education: [["CIPD Level 7", "CIPD", "2020"]],
  }, ["rolodex", "practice"]),
  role("learning-development", "Learning & Development Manager", "L&D managers", "hr", ["L&D", "training manager", "corporate trainer", "leadership development"], {
    title: "Learning & Development Lead", tagline: "Training people actually use the week after.",
    bio: ["I design leadership and skills programmes for a 600-person company: first-time managers, feedback and onboarding.", "I measure what changes at work, not just how many people attended."],
    skills: "Programme design · Facilitation · Leadership development · Onboarding · Coaching · E-learning · Evaluation",
    services: [["First-time manager programme", "Six sessions over three months.", "€9,000"], ["Workshop", "Feedback or difficult conversations, half day.", "€1,500"], ["Onboarding redesign", "From offer to day ninety.", "Quote"]],
    stats: [["1,400", "people trained"], ["4.8/5", "average rating"], ["+22 pts", "manager effectiveness"]],
    quote: ["Ruth’s programme changed how our managers give feedback. People noticed within weeks.", "VP People", "Client"],
    experience: [["Learning & Development Lead", "Talo", "2021", "Present"], ["Trainer", "N26", "2017", "2021"]],
    education: [["Certified Professional Coach", "ICF", "2020"]],
  }, ["rolodex", "syllabus"]),

  // ——— Property (Portland, $) ———
  role("real-estate-agent", "Real Estate Agent", "real estate agents", "realestate", ["realtor", "estate agent", "real estate broker", "listing agent", "buyer’s agent"], {
    title: "Realtor®, Brooks & Field", tagline: "Southeast Portland homes, sold with honest pricing and very good photographs.",
    bio: ["I’ve sold homes in Southeast Portland for twelve years. I price carefully, prepare houses properly and tell sellers the truth about what buyers will notice.", "For buyers, I know which streets flood, which schools have waitlists and which sellers will take a quick close."],
    skills: "Richmond · Sellwood · Hawthorne · Mt. Tabor · Woodstock · Ladd’s Addition · Brooklyn · Eastmoreland",
    services: [["Selling your home", "Pricing study, staging plan, photography and weekly updates.", "Fee agreed upfront"], ["Buying a home", "Tours, inspections and negotiation.", "Paid at closing"], ["Free market report", "What your home would sell for this month.", "Free"]],
    stats: [["64", "homes sold in 2024"], ["9", "median days on market"], ["101.8%", "of list price"]],
    quote: ["Hannah was right about the price to the dollar. We closed in nineteen days.", "Dana & Lee M.", "Sold in Richmond"],
    experience: [["Principal Broker", "Brooks & Field Real Estate", "2019", "Present"], ["Broker", "Eastside Realty Group", "2013", "2019"]],
    education: [["Licensed Principal Broker", "Oregon Real Estate Agency", "2013"]],
    keepWork: true,
  }, ["open-house", "practice"]),
  role("letting-agent", "Letting Agent", "letting agents", "realestate", ["leasing agent", "rental agent", "lettings negotiator", "property letting"], {
    title: "Leasing Agent", tagline: "Good tenants for owners, good homes for renters.",
    bio: ["I lease apartments and houses across Portland’s east side, from first viewing to signed lease.", "I screen tenants carefully and match people to homes they’ll want to stay in."],
    skills: "Tenant screening · Viewings · Lease negotiation · Rent pricing · Fair housing · Marketing listings",
    services: [["Find a tenant", "Marketing, viewings, screening and lease.", "One month’s rent"], ["Rent review", "What your property should rent for.", "Free"], ["Lease renewal", "Renewal terms negotiated.", "$250"]],
    stats: [["310", "leases signed"], ["11", "days average to let"], ["94%", "tenants renew"]],
    quote: ["Hannah filled our duplex in a week with tenants who’ve now been there three years.", "Owner", "Client"],
    experience: [["Leasing Agent", "Brooks & Field Real Estate", "2020", "Present"], ["Leasing Consultant", "Eastside Apartments", "2016", "2020"]],
    education: [["Licensed Property Manager", "Oregon Real Estate Agency", "2017"]],
    keepWork: true,
  }, ["open-house", "practice"]),
  role("property-manager", "Property Manager", "property managers", "realestate", ["block manager", "building manager", "landlord services", "HOA manager"], {
    title: "Property Manager", tagline: "Your rentals looked after like they were mine.",
    bio: ["I manage 140 rental homes for private owners: rent collection, repairs, inspections and tenant questions.", "Owners get a monthly statement and a call back the same day."],
    skills: "Rent collection · Maintenance · Inspections · Tenant relations · Compliance · Budgets · AppFolio",
    services: [["Full management", "Everything from tenant-find to repairs.", "8% of rent"], ["Inspection", "Twice-yearly with a photo report.", "$120"], ["Make-ready", "Turnover between tenants.", "Quote"]],
    stats: [["140", "homes managed"], ["99.2%", "rent collected"], ["4-hour", "repair response"]],
    quote: ["I live in Seattle and never worry about my Portland houses.", "Owner", "Client since 2020"],
    experience: [["Property Manager", "Brooks & Field Property Management", "2019", "Present"], ["Assistant Property Manager", "Eastside Apartments", "2015", "2019"]],
    education: [["Licensed Property Manager", "Oregon Real Estate Agency", "2016"]],
    keepWork: true,
  }, ["open-house", "practice"]),

  // ——— Marketing (Barcelona, €) ———
  role("digital-marketer", "Digital Marketing Specialist", "digital marketers", "marketing", ["digital marketing", "performance marketer", "PPC specialist", "paid ads", "growth marketer"], {
    title: "Performance Marketing Specialist", tagline: "Ads that pay for themselves, measured honestly.",
    bio: ["I run paid search and social for e-commerce and B2B brands, with budgets from €5k to €200k a month.", "I report on revenue and profit, not clicks."],
    skills: "Google Ads · Meta Ads · LinkedIn Ads · Analytics · Conversion tracking · Landing pages · A/B testing",
    services: [["Ads audit", "What’s wasting money and what to scale.", "€1,200"], ["Managed campaigns", "Search and social, monthly.", "From €1,800 / month"], ["Tracking set-up", "Analytics and conversions done properly.", "€900"]],
    stats: [["4.1×", "average return on ad spend"], ["€14m", "ad spend managed"], ["−32%", "cost per lead"]],
    quote: ["Sofia cut our ad bill by a third and sales went up.", "Founder", "E-commerce client"],
    experience: [["Performance Marketing Specialist", "Independent", "2021", "Present"], ["Digital Marketing Executive", "Talo", "2018", "2021"]],
    education: [["Google Ads & Analytics certifications", "Google", "2024"]],
  }, ["campaign", "signal"]),
  role("seo-specialist", "SEO Specialist", "SEO specialists", "marketing", ["SEO consultant", "search engine optimisation", "SEO manager", "technical SEO"], {
    title: "SEO Consultant", tagline: "More of the right visitors from Google, without tricks.",
    bio: ["I help companies grow organic traffic with technical fixes, better content and links earned honestly.", "Every project starts with an audit and a plan you can follow even if you never hire me again."],
    skills: "Technical SEO · Keyword research · Content strategy · Site migrations · Local SEO · Search Console · Screaming Frog",
    services: [["SEO audit", "Technical and content audit with priorities.", "€1,800"], ["Monthly SEO", "Strategy, content briefs and fixes.", "From €1,500 / month"], ["Site migration", "Protecting traffic when you change platform.", "Quote"]],
    stats: [["+210%", "organic traffic, average"], ["60+", "sites audited"], ["0", "penalties"]],
    quote: ["Organic is now our biggest source of leads, and it costs us nothing per click.", "Marketing Director", "Client"],
    experience: [["SEO Consultant", "Independent", "2020", "Present"], ["SEO Manager", "Talo", "2016", "2020"]],
    education: [["BA Journalism", "Universitat Pompeu Fabra", "2014"]],
  }, ["signal", "campaign"]),
  role("social-media-manager", "Social Media Manager", "social media managers", "marketing", ["social media", "community manager", "content creator", "influencer marketing"], {
    title: "Social Media Manager", tagline: "Social channels people follow because they want to.",
    bio: ["I plan, shoot and post content for lifestyle and food brands on Instagram, TikTok and LinkedIn.", "I grew one restaurant group from 4k to 120k followers in eighteen months."],
    skills: "Content planning · Short-form video · Community management · Influencer partnerships · Analytics · Canva · CapCut",
    services: [["Social audit", "What’s working and a 90-day plan.", "€650"], ["Monthly management", "Content, posting and community.", "From €1,200 / month"], ["Content day", "A day of shooting for a month of posts.", "€900"]],
    stats: [["120k", "followers grown for one client"], ["8.4%", "average engagement"], ["30+", "brands"]],
    quote: ["Our bookings jumped the month Sofia took over our Instagram.", "Owner", "Restaurant group"],
    experience: [["Social Media Manager", "Independent", "2021", "Present"], ["Content Executive", "Fable Foods", "2018", "2021"]],
    education: [["BA Audiovisual Communication", "Universitat de Barcelona", "2017"]],
  }, ["campaign", "lookbook"]),
  role("content-marketer", "Content Marketer", "content marketers", "marketing", ["content strategist", "content manager", "copywriter", "content writer"], {
    title: "Content Marketing Manager", tagline: "Articles, guides and newsletters people actually finish.",
    bio: ["I plan and write content for B2B software companies: guides, case studies, newsletters and webinars.", "I measure content by the leads and customers it brings, and I cut what doesn’t work."],
    skills: "Content strategy · Long-form writing · Editing · Case studies · Newsletters · SEO writing · Interviews",
    services: [["Content strategy", "Topics, formats and a quarterly calendar.", "€2,800"], ["Case study", "Interview, writing and design brief.", "€900"], ["Newsletter", "Written and sent every fortnight.", "From €1,100 / month"]],
    stats: [["38%", "newsletter open rate"], ["+3×", "content-sourced leads"], ["200+", "articles"]],
    quote: ["Sofia’s case studies are the first thing our sales team sends to prospects.", "VP Sales", "Client"],
    experience: [["Content Marketing Manager", "Northwind Pay", "2021", "Present"], ["Content Writer", "Talo", "2018", "2021"]],
    education: [["BA Journalism", "Universitat Pompeu Fabra", "2016"]],
  }, ["quarterly", "broadsheet"]),
  role("pr-specialist", "PR & Communications Specialist", "PR specialists", "marketing", ["public relations", "communications manager", "press officer", "comms"], {
    title: "PR & Communications Manager", tagline: "Stories journalists want to write, told truthfully.",
    bio: ["I run press and communications for consumer and tech brands: launches, founder profiles and crisis communications.", "I have good relationships with journalists because I never waste their time."],
    skills: "Media relations · Press releases · Crisis communications · Thought leadership · Internal comms · Media training",
    services: [["Launch campaign", "Story, press list and outreach.", "From €3,500"], ["Monthly PR retainer", "Ongoing coverage and opportunities.", "From €2,200 / month"], ["Media training", "Half day for spokespeople.", "€1,200"]],
    stats: [["400+", "articles secured"], ["FT · TechCrunch", "recent coverage"], ["12", "years in PR"]],
    quote: ["Sofia got our founder into three national papers in the week we launched.", "CEO", "Client"],
    experience: [["PR & Communications Manager", "Independent", "2020", "Present"], ["Account Director", "Barcelona PR agency", "2014", "2020"]],
    education: [["BA Journalism", "Universitat Pompeu Fabra", "2012"]],
  }, ["broadsheet", "keynote"]),

  // ——— Public service (Nairobi persona, $) ———
  role("social-worker", "Social Worker", "social workers", "nonprofit", ["child protection social worker", "case worker", "family support worker", "community worker"], {
    title: "Senior Social Worker, Children & Families", tagline: "Keeping children safe and families together wherever possible.",
    bio: ["I work with families facing crisis: neglect, domestic violence, addiction and housing loss.", "I supervise newly qualified social workers and lead our family group conferencing service."],
    skills: "Child protection · Family support · Risk assessment · Family group conferencing · Court reports · Supervision",
    services: [["Independent assessment", "Parenting and risk assessments for courts.", "Quote"], ["Training", "Safeguarding for schools and charities.", "Quote"], ["Supervision", "For social workers in their first year.", "Quote"]],
    stats: [["11", "years in practice"], ["600+", "families supported"], ["14", "social workers supervised"]],
    quote: ["She never gave up on us, even when we’d given up on ourselves.", "Parent", "Family support"],
    experience: [["Senior Social Worker", "Nairobi County Children’s Services", "2019", "Present"], ["Social Worker", "Child Welfare Society", "2014", "2019"]],
    education: [["BA Social Work", "University of Nairobi", "2013"]],
    name: "Joseph Mwangi",
  }, ["field-report", "sanctuary"]),
  role("fundraiser", "Fundraiser", "fundraisers", "nonprofit", ["fundraising manager", "development director", "grant writer", "major gifts"], {
    title: "Head of Fundraising", tagline: "Raising money for work that matters, and keeping donors for life.",
    bio: ["I lead fundraising for a clean-water charity: foundations, major donors and corporate partners.", "I’ve grown income from $2.1M to $7.2M a year in five years, with donors who stay."],
    skills: "Major gifts · Trusts & foundations · Grant writing · Corporate partnerships · Donor stewardship · Campaigns",
    services: [["Fundraising strategy", "A three-year plan with targets.", "Quote"], ["Grant writing", "Proposals for foundations.", "From $1,500"], ["Board training", "Making the ask, for trustees.", "$1,200"]],
    stats: [["$2.1M → $7.2M", "annual income"], ["87%", "donor retention"], ["40", "foundations funding us"]],
    quote: ["Joseph is the reason we fund for ten years instead of three.", "Programme Officer", "Foundation donor"],
    experience: [["Head of Fundraising", "Maji Kesho", "2020", "Present"], ["Grants Manager", "WaterWorks East Africa", "2015", "2020"]],
    education: [["Certificate in Fundraising", "Chartered Institute of Fundraising", "2016"]],
  }, ["field-report", "annual-report"]),
  role("policy-officer", "Policy Officer", "policy officers", "nonprofit", ["civil servant", "policy advisor", "public servant", "government", "public affairs"], {
    title: "Senior Policy Adviser, Water & Sanitation", tagline: "Evidence turned into policy that works on the ground.",
    bio: ["I advise the ministry on water and sanitation policy: drafting strategies, briefing ministers and working with county governments.", "Before government I ran programmes in the field, which keeps my advice practical."],
    skills: "Policy analysis · Ministerial briefings · Legislation · Stakeholder engagement · Public finance · Evaluation",
    services: [["Policy review", "Independent review of a policy or programme.", "Quote"], ["Briefing papers", "Clear analysis for decision-makers.", "Quote"], ["Speaking", "Conferences and panels.", "Quote"]],
    stats: [["3", "national strategies drafted"], ["47", "counties engaged"], ["12", "years in water policy"]],
    quote: ["Joseph’s briefings are the ones ministers read to the end.", "Permanent Secretary", "Ministry of Water"],
    experience: [["Senior Policy Adviser", "Ministry of Water & Sanitation", "2021", "Present"], ["Programme Director", "Maji Kesho", "2015", "2021"]],
    education: [["MSc Public Policy", "University of Nairobi", "2014"]],
  }, ["field-report", "seminar"]),
];
