import { role } from "./types";

/**
 * Doctors, dentists, nurses and other clinicians. Based on the Barcelona
 * clinic persona; fees in euros. Hospitals named here are fictional.
 */
const DR = "Dr. Lucía Ferrer";
const NAME = "Lucía Ferrer";
const H = "Hospital Universitari Mediterrani";
const MD: [string, string, string] = ["Doctor of Medicine (MD)", "Universitat de Barcelona", "2012"];

export const HEALTH_ROLES = [
  role("gp", "General Practitioner", "GPs and family doctors", "healthcare", ["GP", "doctor", "family doctor", "family physician", "primary care doctor", "general practice"], {
    name: DR, title: "General Practitioner", tagline: "Unhurried appointments, plain explanations and a plan you can follow.",
    bio: ["I’m a family doctor looking after adults and children for everything from a cough to long-term conditions like diabetes and high blood pressure.", "Appointments are thirty minutes, because most problems need more than ten."],
    skills: "Family medicine · Chronic disease · Women’s health · Children’s health · Mental health · Health checks · Minor procedures · Vaccinations",
    services: [["Consultation", "Thirty minutes, in person or by video.", "€70"], ["Annual health check", "Bloods, ECG, blood pressure and a written summary.", "€160"], ["Follow-up", "Within six weeks of a consultation.", "€45"]],
    stats: [["30", "minute appointments"], ["11", "years in practice"], ["3", "languages"]],
    quote: ["The first doctor who explained my blood pressure readings instead of just handing me a prescription.", "Jordi P.", "Patient"],
    experience: [["General Practitioner", "Consulta Ferrer, Eixample", "2020", "Present"], ["Specialist Registrar, Family Medicine", H, "2014", "2018"]],
    education: [MD, ["Specialist training, Family & Community Medicine", H, "2018"]],
    availability: "Accepting new patients · English, Spanish, Catalan",
  }, ["clinic", "practice"]),
  role("paediatrician", "Paediatrician", "paediatricians", "healthcare", ["pediatrician", "children’s doctor", "child doctor", "kids doctor", "neonatologist"], {
    name: DR, title: "Consultant Paediatrician", tagline: "Calm, careful care for children, and answers parents can understand.",
    bio: ["I look after babies, children and teenagers, from newborn checks to asthma, allergies and growth worries.", "I explain things to children in their own words and give parents a written plan to take home."],
    skills: "General paediatrics · Newborn checks · Asthma & allergy · Growth & development · Vaccinations · Adolescent health · Feeding problems",
    services: [["Paediatric consultation", "Forty-five minutes, with a written plan for parents.", "€95"], ["Newborn check", "A full examination in the first weeks, at home or in clinic.", "€120"], ["Allergy assessment", "History, skin-prick testing and an action plan.", "€140"]],
    stats: [["14", "years with children"], ["45", "minute appointments"], ["4.9★", "from 310 families"]],
    quote: ["She talked to our son, not over him. He left asking when he could come back.", "Parent", "Patient family"],
    experience: [["Consultant Paediatrician", "Clínica Infantil Diagonal", "2019", "Present"], ["Paediatric Registrar", "Hospital Infantil del Mar", "2014", "2019"]],
    education: [MD, ["Specialist training, Paediatrics", "Hospital Infantil del Mar", "2019"]],
    availability: "New patients from birth to 16",
  }, ["clinic", "exercise-book"]),
  role("general-surgeon", "General Surgeon", "general surgeons", "healthcare", ["surgeon", "laparoscopic surgeon", "hernia surgeon", "gallbladder surgeon"], {
    name: DR, title: "Consultant General & Laparoscopic Surgeon", tagline: "Keyhole surgery explained clearly, done carefully, followed up personally.",
    bio: ["I specialise in hernia, gallbladder and abdominal wall surgery, almost all of it keyhole, with most patients home the same day.", "I see every patient before and after their operation myself."],
    skills: "Laparoscopic surgery · Hernia repair · Gallbladder surgery · Abdominal wall reconstruction · Day-case surgery · Enhanced recovery",
    services: [["Surgical consultation", "Examination, scans reviewed and options explained.", "€150"], ["Hernia repair", "Day-case keyhole surgery, all-inclusive package.", "From €3,200"], ["Gallbladder removal", "Laparoscopic cholecystectomy, one night’s stay.", "From €4,100"]],
    stats: [["2,400+", "operations"], ["92%", "home the same day"], ["16", "years operating"]],
    quote: ["Back at work in a week, with three tiny scars. She called me herself the next morning.", "Patient", "Hernia repair, 2024"],
    experience: [["Consultant General Surgeon", H, "2017", "Present"], ["Surgical Registrar", "Hospital del Litoral", "2011", "2017"]],
    education: [MD, ["Specialist training, General & Digestive Surgery", "Hospital del Litoral", "2017"]],
  }, ["clinic", "practice"]),
  role("orthopaedic-surgeon", "Orthopaedic Surgeon", "orthopaedic surgeons", "healthcare", ["orthopedic surgeon", "knee surgeon", "hip surgeon", "sports surgeon", "spine surgeon"], {
    name: DR, title: "Consultant Orthopaedic Surgeon, Knee & Sports Injury", tagline: "Getting you back to what you love doing, with surgery only when it helps.",
    bio: ["I treat knee problems and sports injuries, from ligament tears to arthritis. About half the people I see don’t need an operation, and I tell them so.", "When surgery is right, I plan the rehab with your physio before we start."],
    skills: "Knee surgery · ACL reconstruction · Meniscus repair · Knee replacement · Arthroscopy · Sports injuries · Cartilage repair",
    services: [["Knee assessment", "Examination, MRI review and a clear plan.", "€160"], ["ACL reconstruction", "Package including surgery, brace and two follow-ups.", "From €6,800"], ["Second opinion", "A written opinion on a proposed operation.", "€180"]],
    stats: [["1,900", "knee operations"], ["50%", "of patients treated without surgery"], ["Team surgeon", "Barcelona Rugby Club"]],
    quote: ["Two other surgeons wanted to operate. She sent me to a physio instead, and I ran a marathon eight months later.", "Patient", "Runner"],
    experience: [["Consultant Orthopaedic Surgeon", H, "2016", "Present"], ["Fellow, Knee & Sports Surgery", "Hospital del Litoral", "2014", "2016"]],
    education: [MD, ["Specialist training, Orthopaedic Surgery & Traumatology", "Hospital del Litoral", "2014"]],
  }, ["clinic", "training-log"]),
  role("cardiologist", "Cardiologist", "cardiologists", "healthcare", ["heart doctor", "heart specialist", "cardiology", "interventional cardiologist"], {
    name: DR, title: "Consultant Cardiologist", tagline: "Heart care that starts with listening, not just a scan.",
    bio: ["I see people with chest pain, palpitations, high blood pressure and heart failure, and athletes who want their heart checked before they compete.", "I do the echo myself in the same appointment, so you leave with an answer."],
    skills: "Echocardiography · Chest pain · Arrhythmia · Heart failure · Hypertension · Sports cardiology · Cardiac prevention",
    services: [["Cardiology consultation", "With ECG and echocardiogram in the same visit.", "€190"], ["Athlete heart screen", "ECG, echo and exercise test before competition.", "€260"], ["24-hour heart monitor", "Holter fitted and reported.", "€140"]],
    stats: [["9,000+", "echocardiograms"], ["Same-day", "results"], ["13", "years in cardiology"]],
    quote: ["I came in worried and left with a diagnosis, a plan and a drawing of my heart that finally made sense.", "Patient", "Arrhythmia clinic"],
    experience: [["Consultant Cardiologist", H, "2018", "Present"], ["Cardiology Registrar", "Hospital del Litoral", "2013", "2018"]],
    education: [MD, ["Specialist training, Cardiology", "Hospital del Litoral", "2018"]],
  }, ["clinic", "prospectus"]),
  role("dermatologist", "Dermatologist", "dermatologists", "healthcare", ["skin doctor", "skin specialist", "dermatology", "mole check", "acne doctor"], {
    name: DR, title: "Consultant Dermatologist", tagline: "Skin, hair and nails, diagnosed properly and treated kindly.",
    bio: ["I treat acne, eczema, psoriasis and hair loss, and I check moles and skin cancers with dermoscopy and mole mapping.", "I’ll always tell you which treatments are worth paying for and which aren’t."],
    skills: "Medical dermatology · Mole mapping · Skin cancer · Acne · Eczema & psoriasis · Hair loss · Minor skin surgery",
    services: [["Dermatology consultation", "Thirty minutes with a written treatment plan.", "€110"], ["Full-body mole check", "Dermoscopy of every mole, with photos for next time.", "€150"], ["Skin lesion removal", "Minor surgery with histology.", "From €220"]],
    stats: [["40,000+", "moles checked"], ["12", "years in dermatology"], ["Same week", "appointments"]],
    quote: ["After years of creams that didn’t work, my skin has been clear for eighteen months.", "Patient", "Acne clinic"],
    experience: [["Consultant Dermatologist", "Clínica Dermatològica Eixample", "2018", "Present"], ["Dermatology Registrar", H, "2014", "2018"]],
    education: [MD, ["Specialist training, Dermatology & Venereology", H, "2018"]],
  }, ["clinic", "lookbook"]),
  role("psychiatrist", "Psychiatrist", "psychiatrists", "healthcare", ["psychiatry", "mental health doctor", "adhd psychiatrist", "child psychiatrist"], {
    name: DR, title: "Consultant Psychiatrist", tagline: "Careful assessment, honest options and time to talk them through.",
    bio: ["I assess and treat adults with depression, anxiety, bipolar disorder and ADHD. First appointments are ninety minutes.", "I combine medication with talking therapy where it helps, and I work closely with your GP."],
    skills: "Adult psychiatry · ADHD assessment · Depression · Anxiety · Bipolar disorder · Medication reviews · Perinatal mental health",
    services: [["Initial assessment", "Ninety minutes with a written report and plan.", "€250"], ["Follow-up", "Medication review and progress, 45 minutes.", "€130"], ["Adult ADHD assessment", "Structured assessment with questionnaires and report.", "€550"]],
    stats: [["90", "minute first appointments"], ["15", "years in psychiatry"], ["Video", "or in person"]],
    quote: ["She was the first person who took the time to understand the whole picture.", "Patient", "Adult ADHD service"],
    experience: [["Consultant Psychiatrist", "Centre de Salut Mental Eixample", "2017", "Present"], ["Psychiatry Registrar", H, "2012", "2017"]],
    education: [MD, ["Specialist training, Psychiatry", H, "2017"]],
  }, ["sanctuary", "clinic"]),
  role("obgyn", "Obstetrician & Gynaecologist", "obstetricians and gynaecologists", "healthcare", ["gynecologist", "gynaecologist", "obstetrician", "OBGYN", "women’s health doctor", "fertility doctor"], {
    name: DR, title: "Consultant Obstetrician & Gynaecologist", tagline: "Pregnancy and women’s health care from someone who stays with you.",
    bio: ["I look after women through pregnancy and birth, and see patients for periods, endometriosis, fertility questions and menopause.", "If you’re pregnant with me, I aim to be at your birth."],
    skills: "Pregnancy care · Birth · High-risk pregnancy · Endometriosis · Fertility · Menopause · Gynaecological ultrasound",
    services: [["Gynaecology consultation", "With ultrasound if needed.", "€120"], ["Pregnancy care package", "All antenatal visits and scans from 12 weeks.", "From €1,900"], ["Menopause clinic", "Symptoms, options and HRT explained.", "€120"]],
    stats: [["2,000+", "babies delivered"], ["16", "years in practice"], ["One", "doctor from scan to birth"]],
    quote: ["She was there at 3am, as calm as at our first scan. We couldn’t have asked for more.", "Parents", "Birth, 2024"],
    experience: [["Consultant Obstetrician & Gynaecologist", "Clínica Maternal Barcelona", "2016", "Present"], ["Registrar, Obstetrics & Gynaecology", H, "2011", "2016"]],
    education: [MD, ["Specialist training, Obstetrics & Gynaecology", H, "2016"]],
  }, ["clinic", "sanctuary"]),
  role("anaesthetist", "Anaesthetist", "anaesthetists", "healthcare", ["anesthesiologist", "anaesthesia", "pain doctor", "pain management"], {
    name: DR, title: "Consultant Anaesthetist & Pain Specialist", tagline: "Safe anaesthesia, and long-term pain taken seriously.",
    bio: ["I give anaesthetics for orthopaedic and day-case surgery and run a clinic for people living with long-term back and nerve pain.", "I meet every patient before their operation to explain what will happen and answer their worries."],
    skills: "General anaesthesia · Regional anaesthesia · Nerve blocks · Chronic pain · Back pain injections · Pre-operative assessment",
    services: [["Pain clinic consultation", "Assessment and a written plan.", "€140"], ["Image-guided injection", "Spinal or nerve injection with follow-up call.", "From €480"], ["Pre-operative assessment", "For patients with complex health needs.", "€120"]],
    stats: [["15,000+", "anaesthetics given"], ["14", "years in anaesthesia"], ["Pain clinic", "every Tuesday"]],
    quote: ["Nobody had explained my pain before. Six months on, I’m walking the dog again.", "Patient", "Pain clinic"],
    experience: [["Consultant Anaesthetist", H, "2017", "Present"], ["Anaesthesia Registrar", "Hospital del Litoral", "2012", "2017"]],
    education: [MD, ["Specialist training, Anaesthesiology & Pain Medicine", "Hospital del Litoral", "2017"]],
  }, ["clinic", "datasheet"]),
  role("radiologist", "Radiologist", "radiologists", "healthcare", ["radiology", "imaging doctor", "interventional radiologist", "MRI"], {
    name: DR, title: "Consultant Musculoskeletal Radiologist", tagline: "Clear scans, clear reports and a call when it matters.",
    bio: ["I report MRI, ultrasound and CT scans of muscles, joints and bones, and perform ultrasound-guided injections.", "I write reports that other doctors and patients can actually understand."],
    skills: "MRI · Ultrasound · CT · Musculoskeletal imaging · Sports imaging · Guided injections · Teleradiology",
    services: [["Second-opinion report", "A full re-read of your MRI or CT within 48 hours.", "€180"], ["Diagnostic ultrasound", "Scan and report in one appointment.", "€120"], ["Guided injection", "Ultrasound-guided joint or tendon injection.", "€260"]],
    stats: [["60,000+", "scans reported"], ["48h", "second opinions"], ["12", "years in radiology"]],
    quote: ["Her reports are the clearest I receive. I know exactly what to do next.", "Orthopaedic Surgeon", "Referring colleague"],
    experience: [["Consultant Radiologist", H, "2018", "Present"], ["Radiology Registrar", "Hospital del Litoral", "2014", "2018"]],
    education: [MD, ["Specialist training, Radiology", "Hospital del Litoral", "2018"]],
  }, ["datasheet", "clinic"]),
  role("emergency-physician", "Emergency Medicine Doctor", "emergency doctors", "healthcare", ["A&E doctor", "ER doctor", "emergency physician", "urgent care doctor"], {
    name: DR, title: "Emergency Medicine Consultant", tagline: "Calm decisions in the worst hour of someone’s week.",
    bio: ["I lead shifts in a busy city emergency department, from cardiac arrests to sprained ankles, and teach junior doctors resuscitation.", "Outside the hospital I run trauma training for mountain rescue teams."],
    skills: "Resuscitation · Trauma · Emergency ultrasound · Paediatric emergencies · Team leadership · Medical education",
    services: [["Resuscitation training", "One-day course for clinical teams.", "€1,400"], ["Event medical cover", "Doctor-led cover for sporting events.", "Quote"], ["Expert opinion", "Written opinions on emergency care.", "€220 / hour"]],
    stats: [["110,000", "attendances a year in our department"], ["13", "years in emergency medicine"], ["300+", "doctors trained"]],
    quote: ["The calmest voice in the resus room. Everyone does their best work when she’s leading.", "Charge Nurse", "Emergency department"],
    experience: [["Emergency Medicine Consultant", H, "2017", "Present"], ["Emergency Registrar", "Hospital del Litoral", "2012", "2017"]],
    education: [MD, ["Specialist training, Emergency Medicine", "Hospital del Litoral", "2017"]],
  }, ["clinic", "site-board"]),
  role("ophthalmologist", "Ophthalmologist", "ophthalmologists", "healthcare", ["eye doctor", "eye surgeon", "cataract surgeon", "eye specialist"], {
    name: DR, title: "Consultant Ophthalmologist, Cataract & Glaucoma", tagline: "Clearer sight, and the time to explain every option.",
    bio: ["I perform cataract surgery and look after people with glaucoma and macular disease.", "Cataract surgery takes about twenty minutes; I spend longer than that explaining it beforehand."],
    skills: "Cataract surgery · Glaucoma · Macular degeneration · Diabetic eye disease · Lens implants · Laser treatment",
    services: [["Eye consultation", "Full examination with scans.", "€140"], ["Cataract surgery", "Per eye, including lens and follow-up.", "From €2,400"], ["Glaucoma review", "Pressure, fields and nerve scan.", "€120"]],
    stats: [["6,500+", "cataract operations"], ["20", "minute surgery"], ["Same-week", "appointments"]],
    quote: ["I can read the menu without glasses for the first time in twenty years.", "Patient", "Cataract surgery"],
    experience: [["Consultant Ophthalmologist", "Institut Oftalmològic Barcelona", "2017", "Present"], ["Ophthalmology Registrar", H, "2013", "2017"]],
    education: [MD, ["Specialist training, Ophthalmology", H, "2017"]],
  }, ["clinic", "practice"]),
  role("neurologist", "Neurologist", "neurologists", "healthcare", ["brain doctor", "headache specialist", "migraine doctor", "epilepsy", "neurology"], {
    name: DR, title: "Consultant Neurologist", tagline: "Headaches, seizures and memory worries, investigated thoroughly.",
    bio: ["I see adults with migraine, epilepsy, multiple sclerosis, Parkinson’s and memory problems.", "I give each new patient an hour, because the history is usually where the answer is."],
    skills: "Migraine · Epilepsy · Multiple sclerosis · Parkinson’s disease · Memory clinic · Nerve conduction studies",
    services: [["Neurology consultation", "An hour, with a written summary.", "€180"], ["Headache clinic", "Diagnosis and a treatment plan for migraine.", "€160"], ["Memory assessment", "Testing and a family meeting.", "€320"]],
    stats: [["60", "minute first appointments"], ["14", "years in neurology"], ["3", "research trials led"]],
    quote: ["Ten years of migraines, and she was the first to find what was triggering them.", "Patient", "Headache clinic"],
    experience: [["Consultant Neurologist", H, "2017", "Present"], ["Neurology Registrar", "Hospital del Litoral", "2012", "2017"]],
    education: [MD, ["Specialist training, Neurology", "Hospital del Litoral", "2017"]],
  }, ["clinic", "seminar"]),
  role("oncologist", "Oncologist", "oncologists", "healthcare", ["cancer doctor", "cancer specialist", "medical oncologist", "breast cancer doctor"], {
    name: DR, title: "Consultant Medical Oncologist, Breast Cancer", tagline: "Expert cancer treatment, with you at the centre of every decision.",
    bio: ["I treat women and men with breast cancer, from early disease to advanced cancer, and lead clinical trials of new treatments.", "I make sure every patient knows their options and has a named nurse they can call."],
    skills: "Breast cancer · Chemotherapy · Targeted therapy · Immunotherapy · Clinical trials · Second opinions",
    services: [["Oncology consultation", "Review of your results and treatment options.", "€220"], ["Second opinion", "A written opinion on a proposed treatment plan.", "€300"], ["Clinical trial screening", "Whether a trial could be right for you.", "No charge"]],
    stats: [["12", "clinical trials led"], ["15", "years in oncology"], ["40+", "published papers"]],
    quote: ["She explained everything twice and never once made us feel rushed.", "Patient’s husband", "Breast unit"],
    experience: [["Consultant Medical Oncologist", "Institut Oncològic Mediterrani", "2016", "Present"], ["Oncology Registrar", H, "2011", "2016"]],
    education: [MD, ["PhD, Cancer Biology", "Universitat de Barcelona", "2015"]],
  }, ["clinic", "seminar"]),
  role("dentist", "Dentist", "dentists", "healthcare", ["dental surgeon", "family dentist", "cosmetic dentist", "dental clinic"], {
    name: DR, title: "Dentist & Practice Owner", tagline: "Gentle dentistry for nervous patients and busy families.",
    bio: ["I run a small practice in Eixample offering check-ups, fillings, crowns, implants and whitening.", "Many of my patients haven’t seen a dentist in years because they were scared. I take it slowly and explain every step."],
    skills: "General dentistry · Nervous patients · Implants · Crowns & bridges · Whitening · Invisalign · Children’s dentistry",
    services: [["Check-up & clean", "Examination, X-rays and hygienist clean.", "€85"], ["Tooth-coloured filling", "One surface.", "From €90"], ["Dental implant", "Implant, abutment and crown.", "From €1,650"]],
    stats: [["2,800", "patients"], ["4.9★", "from 640 reviews"], ["Same-day", "emergency appointments"]],
    quote: ["I hadn’t been to a dentist in eight years. Now I actually don’t mind going.", "Patient", "Nervous patient programme"],
    experience: [["Principal Dentist", "Clínica Dental Ferrer", "2018", "Present"], ["Associate Dentist", "Clínica Dental Diagonal", "2013", "2018"]],
    education: [["Degree in Dentistry (DDS)", "Universitat de Barcelona", "2013"], ["Master’s in Oral Implantology", "Universitat Internacional de Catalunya", "2016"]],
  }, ["clinic", "practice"]),
  role("orthodontist", "Orthodontist", "orthodontists", "healthcare", ["braces", "invisalign provider", "teeth straightening"], {
    name: DR, title: "Specialist Orthodontist", tagline: "Straighter smiles, planned carefully and finished properly.",
    bio: ["I straighten teeth for children and adults with fixed braces and clear aligners.", "Every treatment starts with a 3D scan, so you can see the result before you begin."],
    skills: "Fixed braces · Clear aligners · Invisalign · Children’s orthodontics · Adult orthodontics · Retainers",
    services: [["Orthodontic assessment", "Examination, 3D scan and treatment options.", "€80"], ["Clear aligner treatment", "Full course including retainers.", "From €3,400"], ["Fixed braces", "Full course including retainers.", "From €2,900"]],
    stats: [["1,800", "smiles finished"], ["3D", "planning for every case"], ["Platinum", "aligner provider"]],
    quote: ["My daughter actually enjoyed her appointments. The result is better than we hoped.", "Parent", "Patient family"],
    experience: [["Specialist Orthodontist", "Ortodòncia Ferrer", "2017", "Present"], ["Associate Orthodontist", "Clínica Dental Diagonal", "2014", "2017"]],
    education: [["Degree in Dentistry (DDS)", "Universitat de Barcelona", "2011"], ["Master’s in Orthodontics", "Universitat de Barcelona", "2014"]],
  }, ["clinic", "lookbook"]),
  role("nurse", "Registered Nurse", "nurses", "healthcare", ["RN", "nurse", "staff nurse", "ward nurse", "ICU nurse", "theatre nurse"], {
    name: NAME, title: "Senior Staff Nurse, Intensive Care", tagline: "Expert, steady care at the bedside, and a hand to hold for families.",
    bio: ["I’ve been an intensive care nurse for nine years, caring for patients after major surgery, trauma and serious infection.", "I mentor student nurses and lead our unit’s work on family visiting and patient diaries."],
    skills: "Critical care · Ventilation · Sepsis care · Patient safety · Family support · Mentoring · Infection control",
    services: [["Private nursing", "Short-term nursing at home after surgery.", "€38 / hour"], ["Clinical teaching", "Critical care skills sessions for nursing teams.", "€320 / day"], ["Mentoring", "Support for newly qualified nurses.", "Free"]],
    stats: [["9", "years in intensive care"], ["40+", "students mentored"], ["Nurse of the Year", "2024"]],
    quote: ["She noticed my father was frightened before any of us did, and stayed with him.", "Patient’s daughter", "Intensive care unit"],
    experience: [["Senior Staff Nurse, ICU", H, "2019", "Present"], ["Staff Nurse, Surgical Ward", H, "2016", "2019"]],
    education: [["Bachelor’s in Nursing", "Universitat de Barcelona", "2016"], ["Master’s in Critical Care Nursing", "Universitat Pompeu Fabra", "2020"]],
    availability: "Open to senior nurse and clinical educator roles",
  }, ["clinic", "sanctuary"]),
  role("nurse-practitioner", "Nurse Practitioner", "nurse practitioners", "healthcare", ["NP", "advanced nurse practitioner", "ANP", "advanced practice nurse"], {
    name: NAME, title: "Advanced Nurse Practitioner", tagline: "Same-day appointments with a nurse who can diagnose and prescribe.",
    bio: ["I run same-day clinics in a busy practice: infections, injuries, rashes and the things that can’t wait a week.", "I can examine, diagnose, prescribe and refer, and I know when a doctor needs to see you instead."],
    skills: "Minor illness · Minor injury · Prescribing · Women’s health · Long-term conditions · Health promotion",
    services: [["Same-day appointment", "Twenty minutes for an urgent problem.", "€45"], ["Contraception clinic", "Advice, implants and coils.", "€60"], ["Travel health", "Vaccinations and advice.", "From €35"]],
    stats: [["12,000+", "patients seen"], ["11", "years nursing"], ["Prescriber", "since 2019"]],
    quote: ["Seen the same morning, sorted the same morning.", "Patient", "Same-day clinic"],
    experience: [["Advanced Nurse Practitioner", "Centre de Salut Eixample", "2019", "Present"], ["Practice Nurse", "Centre de Salut Gràcia", "2015", "2019"]],
    education: [["Bachelor’s in Nursing", "Universitat de Barcelona", "2014"], ["Master’s in Advanced Nursing Practice", "Universitat de Barcelona", "2019"]],
  }, ["clinic", "practice"]),
  role("midwife", "Midwife", "midwives", "healthcare", ["independent midwife", "birth midwife", "doula", "home birth"], {
    name: NAME, title: "Independent Midwife", tagline: "One midwife through pregnancy, birth and those first weeks at home.",
    bio: ["I care for women having babies at home or in hospital, from the first appointment to six weeks after birth.", "You’ll have my number, and it will be me who comes when labour starts."],
    skills: "Antenatal care · Home birth · Water birth · Birth planning · Breastfeeding support · Postnatal care",
    services: [["Full care package", "Pregnancy, birth and six weeks after.", "€3,600"], ["Birth preparation", "Two sessions for you and your partner.", "€180"], ["Breastfeeding visit", "At home, ninety minutes.", "€90"]],
    stats: [["420", "births attended"], ["13", "years as a midwife"], ["1", "midwife, start to finish"]],
    quote: ["Lucía made our home birth feel safe and calm. We still talk about her every week.", "Parents", "Home birth, 2025"],
    experience: [["Independent Midwife", "Néixer a Casa", "2018", "Present"], ["Hospital Midwife", H, "2012", "2018"]],
    education: [["Bachelor’s in Nursing", "Universitat de Barcelona", "2009"], ["Specialist training, Midwifery", H, "2012"]],
  }, ["sanctuary", "clinic"]),
  role("physiotherapist", "Physiotherapist", "physiotherapists", "healthcare", ["physical therapist", "physio", "PT", "sports physio", "rehab"], {
    name: NAME, title: "Chartered Physiotherapist, Sports & Spine", tagline: "Hands-on treatment and a plan you can do at home.",
    bio: ["I treat back and neck pain, sports injuries and recovery after surgery, using hands-on treatment and exercise.", "Every patient leaves the first session with a written exercise plan and a timeline."],
    skills: "Sports injuries · Back & neck pain · Post-surgical rehab · Running injuries · Exercise therapy · Dry needling",
    services: [["Initial assessment", "Fifty minutes with treatment and exercise plan.", "€65"], ["Follow-up session", "Forty minutes.", "€50"], ["Running assessment", "Video gait analysis and a strength plan.", "€90"]],
    stats: [["5,000+", "patients treated"], ["10", "years as a physio"], ["Team physio", "masters swimming squad"]],
    quote: ["Back running pain-free after a year of trying everything else.", "Patient", "Runner"],
    experience: [["Chartered Physiotherapist", "Fisio Ferrer", "2019", "Present"], ["Physiotherapist", H, "2015", "2019"]],
    education: [["Bachelor’s in Physiotherapy", "Universitat Ramon Llull", "2015"], ["Master’s in Sports Physiotherapy", "Universitat de Barcelona", "2017"]],
  }, ["clinic", "training-log"]),
  role("pharmacist", "Pharmacist", "pharmacists", "healthcare", ["community pharmacist", "clinical pharmacist", "chemist", "pharmacy owner"], {
    name: NAME, title: "Community Pharmacist & Owner", tagline: "Advice without an appointment, from someone who knows your medicines.",
    bio: ["I run a neighbourhood pharmacy in Gràcia. Most days I’m answering questions about medicines, checking blood pressure and helping people manage long-term conditions.", "I also run a medication review service for older patients taking five or more medicines."],
    skills: "Medicine reviews · Minor ailments · Blood pressure checks · Vaccinations · Diabetes support · Travel health",
    services: [["Medication review", "Thirty minutes going through every medicine you take.", "€30"], ["Flu & travel vaccines", "Walk in, no appointment needed.", "From €25"], ["Blood pressure check", "With advice and a record for your doctor.", "Free"]],
    stats: [["600", "people helped every week"], ["14", "years as a pharmacist"], ["Open", "late every weekday"]],
    quote: ["Lucía spotted that two of my mother’s medicines were working against each other.", "Customer", "Medication review"],
    experience: [["Pharmacist & Owner", "Farmàcia Ferrer, Gràcia", "2017", "Present"], ["Hospital Pharmacist", H, "2011", "2017"]],
    education: [["Degree in Pharmacy", "Universitat de Barcelona", "2011"]],
  }, ["clinic", "practice"]),
  role("psychologist", "Psychologist", "psychologists", "healthcare", ["clinical psychologist", "counselling psychologist", "child psychologist", "CBT therapist"], {
    name: NAME, title: "Clinical Psychologist", tagline: "Evidence-based therapy at a pace that suits you.",
    bio: ["I work with adults on anxiety, depression, trauma and stress, using CBT, EMDR and compassion-focused therapy.", "We start with an assessment so we both know what we’re working on and how we’ll know it’s helping."],
    skills: "CBT · EMDR · Anxiety · Depression · Trauma · Burnout · Assessment · Online therapy",
    services: [["Assessment session", "Ninety minutes, with a written formulation.", "€110"], ["Therapy session", "Fifty minutes, weekly or fortnightly.", "€80"], ["EMDR session", "Ninety minutes for trauma work.", "€120"]],
    stats: [["12", "years in practice"], ["2", "languages"], ["Online", "or in person"]],
    quote: ["Practical, warm and never preachy. I have tools I still use every day.", "Client", "2024"],
    experience: [["Clinical Psychologist", "Consulta Psicològica Ferrer", "2018", "Present"], ["Clinical Psychologist", H, "2013", "2018"]],
    education: [["Degree in Psychology", "Universitat Autònoma de Barcelona", "2010"], ["Specialist training, Clinical Psychology (PIR)", H, "2013"]],
  }, ["sanctuary", "practice"]),
  role("optometrist", "Optometrist", "optometrists", "healthcare", ["optician", "eye test", "contact lenses", "eye care"], {
    name: NAME, title: "Optometrist & Practice Owner", tagline: "Thorough eye tests and glasses that suit you.",
    bio: ["I run an independent optician’s in Eixample. Every eye test includes a retinal photo and pressure check, and lasts forty minutes.", "I specialise in contact lenses for difficult prescriptions and in children’s eye care."],
    skills: "Eye examinations · Contact lenses · Myopia control · Children’s vision · Dry eye · Frame styling",
    services: [["Comprehensive eye test", "Forty minutes, with retinal photography.", "€55"], ["Contact lens fitting", "Including trial lenses and follow-up.", "€80"], ["Myopia control for children", "Assessment and annual programme.", "€390 / year"]],
    stats: [["40", "minute eye tests"], ["11", "years in practice"], ["3,000+", "patients"]],
    quote: ["The first optician who managed to fit me with contact lenses I can actually wear.", "Patient", "Contact lens clinic"],
    experience: [["Optometrist & Owner", "Òptica Ferrer", "2019", "Present"], ["Optometrist", "Visió Diagonal", "2014", "2019"]],
    education: [["Degree in Optics & Optometry", "Universitat Politècnica de Catalunya", "2014"]],
  }, ["clinic", "lookbook"]),
  role("dietitian", "Dietitian", "dietitians", "healthcare", ["nutritionist", "registered dietitian", "sports nutritionist", "diet"], {
    name: NAME, title: "Registered Dietitian", tagline: "Food advice based on evidence, not fads.",
    bio: ["I help people with diabetes, gut problems, food allergies and weight concerns eat in a way that works for their life.", "No meal-replacement shakes, no forbidden foods, just a realistic plan."],
    skills: "Diabetes · IBS & low-FODMAP · Food allergy · Sports nutrition · Weight management · Eating disorders",
    services: [["Initial consultation", "An hour reviewing your diet and health.", "€75"], ["Follow-up", "Thirty minutes, with plan adjustments.", "€45"], ["Low-FODMAP programme", "Three sessions over eight weeks.", "€180"]],
    stats: [["2,000+", "clients"], ["10", "years practising"], ["Evidence-based", "always"]],
    quote: ["For the first time in years, I’m not scared of eating out.", "Client", "IBS programme"],
    experience: [["Registered Dietitian", "Nutrició Ferrer", "2019", "Present"], ["Hospital Dietitian", H, "2015", "2019"]],
    education: [["Degree in Human Nutrition & Dietetics", "Universitat de Barcelona", "2015"]],
  }, ["sanctuary", "clinic"]),
  role("occupational-therapist", "Occupational Therapist", "occupational therapists", "healthcare", ["OT", "paediatric OT", "hand therapist"], {
    name: NAME, title: "Paediatric Occupational Therapist", tagline: "Helping children do the everyday things that matter to them.",
    bio: ["I work with children who find handwriting, dressing, coordination or sensory overload hard, often alongside autism or dyspraxia.", "Therapy happens through play, and I always give parents and teachers something to try at home and in class."],
    skills: "Sensory processing · Fine motor skills · Handwriting · Dyspraxia · Autism · School support · Assessments",
    services: [["OT assessment", "Standardised assessment and written report.", "€240"], ["Therapy session", "Fifty minutes of play-based therapy.", "€65"], ["School visit", "Observation and advice for teachers.", "€150"]],
    stats: [["600+", "children supported"], ["9", "years as an OT"], ["School visits", "included"]],
    quote: ["Our son now ties his own shoelaces and asks to write birthday cards.", "Parent", "Patient family"],
    experience: [["Paediatric Occupational Therapist", "Teràpia Infantil Ferrer", "2019", "Present"], ["Occupational Therapist", "Hospital Infantil del Mar", "2015", "2019"]],
    education: [["Degree in Occupational Therapy", "Universitat Autònoma de Barcelona", "2015"]],
  }, ["exercise-book", "clinic"]),
  role("speech-therapist", "Speech & Language Therapist", "speech and language therapists", "healthcare", ["speech therapist", "SLT", "speech pathologist", "speech-language pathologist", "logopedist"], {
    name: NAME, title: "Speech & Language Therapist", tagline: "Helping children and adults find their words.",
    bio: ["I work with children who are late to talk, stammer or have speech sound difficulties, and with adults after a stroke.", "Sessions are practical and fun, and families always leave with activities for the week."],
    skills: "Language delay · Speech sounds · Stammering · Bilingual children · Aphasia after stroke · Assessments",
    services: [["Assessment", "Ninety minutes with a written report.", "€150"], ["Therapy session", "Forty-five minutes, clinic or online.", "€60"], ["Parent workshop", "Four evenings on building language at home.", "€140"]],
    stats: [["700+", "clients"], ["11", "years in practice"], ["3", "languages"]],
    quote: ["Six months ago our daughter had ten words. Now she doesn’t stop talking.", "Parent", "Patient family"],
    experience: [["Speech & Language Therapist", "Logopèdia Ferrer", "2018", "Present"], ["Speech Therapist", H, "2014", "2018"]],
    education: [["Degree in Speech Therapy (Logopèdia)", "Universitat de Barcelona", "2014"]],
  }, ["exercise-book", "sanctuary"]),
  role("paramedic", "Paramedic", "paramedics", "healthcare", ["EMT", "ambulance", "emergency medical technician", "first responder"], {
    name: NAME, title: "Advanced Paramedic", tagline: "First on scene, and steady when it counts.",
    bio: ["I’ve worked on emergency ambulances for twelve years, the last five as an advanced paramedic on the critical care desk.", "I teach first aid in schools and run event medical cover at weekends."],
    skills: "Pre-hospital care · Trauma · Cardiac arrest · Critical care transfer · Major incidents · First-aid teaching",
    services: [["Event medical cover", "Paramedic-led cover for sports and festivals.", "Quote"], ["First-aid training", "Half-day course for schools and workplaces.", "€380"], ["Defibrillator training", "Ninety-minute session for staff.", "€150"]],
    stats: [["12", "years on the road"], ["9,000+", "emergency calls"], ["2,000", "people trained in first aid"]],
    quote: ["She kept my dad alive and kept us calm. We’ll never forget her.", "Family", "Cardiac arrest call, 2024"],
    experience: [["Advanced Paramedic", "Servei d’Emergències Mèdiques", "2020", "Present"], ["Paramedic", "Servei d’Emergències Mèdiques", "2013", "2020"]],
    education: [["Higher Diploma, Emergency Health Technician", "Institut Joan d’Àustria", "2013"], ["Advanced Paramedic Practice", "Universitat de Barcelona", "2020"]],
  }, ["site-board", "clinic"]),
  role("veterinarian", "Veterinarian", "vets", "healthcare", ["vet", "veterinary surgeon", "animal doctor", "small animal vet", "equine vet"], {
    name: DR, title: "Veterinary Surgeon & Clinic Owner", tagline: "Kind, careful care for dogs, cats and the people who love them.",
    bio: ["I run a small-animal clinic in Gràcia with two other vets and four nurses. We do everything from vaccinations to orthopaedic surgery.", "We take our time with nervous pets and always explain costs before treatment."],
    skills: "Small animal medicine · Soft tissue surgery · Orthopaedics · Dentistry · Senior pet care · Fear-free handling",
    services: [["Consultation", "Twenty minutes, with a full health check.", "€45"], ["Annual health plan", "Vaccines, checks and parasite control.", "€19 / month"], ["Dental clean", "Under anaesthetic, with X-rays.", "From €280"]],
    stats: [["4,500", "patients (and their owners)"], ["14", "years in practice"], ["Fear-free", "certified"]],
    quote: ["Our anxious greyhound actually wags his tail at the vet now.", "Owner", "Clinic client"],
    experience: [["Veterinary Surgeon & Owner", "Clínica Veterinària Gràcia", "2018", "Present"], ["Veterinary Surgeon", "Hospital Veterinari Diagonal", "2011", "2018"]],
    education: [["Degree in Veterinary Medicine", "Universitat Autònoma de Barcelona", "2011"]],
  }, ["clinic", "practice"]),
];
