import { role } from "./types";

/** Managers of every kind, plus office and admin roles. Based on the Birmingham and London personas; prices in pounds. */
const CMI: [string, string, string] = ["Level 7 Diploma in Strategic Management", "Chartered Management Institute", "2020"];

export const MANAGEMENT_ROLES = [
  role("project-manager", "Project Manager", "project managers", "management", ["PM", "project lead", "PMP", "Prince2", "delivery manager"], {
    title: "Senior Project Manager", tagline: "Projects that land on time, on budget, and with everyone still talking.",
    bio: ["I deliver complex projects in logistics and retail: new sites, system rollouts and moves that can’t stop the business.", "I keep plans simple, risks visible and stakeholders informed before they have to ask."],
    skills: "Project planning · Risk management · Budgets · Stakeholder management · Agile & Waterfall · PRINCE2 · Jira · MS Project",
    services: [["Project rescue", "A two-week review and recovery plan for a project in trouble.", "£5,500"], ["Interim project manager", "Hands-on delivery for three to twelve months.", "From £600 / day"], ["PMO set-up", "Templates, reporting and governance that people use.", "Quote"]],
    stats: [["34", "projects delivered"], ["£62m", "total budgets"], ["94%", "on time"]],
    quote: ["Rebecca’s weekly one-page update was the only report the board actually read.", "Programme Director", "Midland Fresh Foods"],
    experience: [["Senior Project Manager", "Midland Fresh Foods", "2021", "Present"], ["Project Manager", "Severn Logistics", "2016", "2021"]],
    education: [["PRINCE2 Practitioner & PMP", "Axelos / PMI", "2017"], ["BSc Business & Management", "Aston University", "2013"]],
  }, ["prospectus", "annual-report", "practice"]),
  role("programme-manager", "Programme Manager", "programme managers", "management", ["program manager", "portfolio manager", "transformation manager", "PMO lead"], {
    title: "Transformation Programme Manager", tagline: "Large change, broken into pieces people can actually deliver.",
    bio: ["I lead multi-year transformation programmes: several projects, one goal and a lot of people to bring along.", "Most recently I ran a £24m supply chain modernisation across nine sites."],
    skills: "Programme governance · Benefits realisation · Change management · Portfolio planning · Vendor management · Board reporting",
    services: [["Programme health check", "An independent view of scope, risk and benefits.", "£7,500"], ["Interim programme lead", "Six to eighteen months.", "From £850 / day"], ["Benefits framework", "How you’ll prove the programme was worth it.", "Quote"]],
    stats: [["£24m", "programme delivered"], ["9", "sites transformed"], ["£6.1m", "annual savings"]],
    quote: ["She turned an overwhelming programme into a plan the whole company understood.", "Chief Operating Officer", "Client"],
    experience: [["Transformation Programme Manager", "Midland Fresh Foods", "2021", "Present"], ["Senior Project Manager", "Severn Logistics", "2016", "2021"]],
    education: [["Managing Successful Programmes (MSP)", "Axelos", "2019"], CMI],
  }, ["annual-report", "prospectus"]),
  role("operations-manager", "Operations Manager", "operations managers", "management", ["ops manager", "head of operations", "operations director", "COO", "warehouse manager"], {
    title: "Operations Manager", tagline: "I make busy organisations run smoothly, quietly and on budget.",
    bio: ["I’ve managed operations for twelve years, in logistics, healthcare and retail. I like messy processes, honest numbers and teams who know what good looks like.", "My work is mostly invisible when it’s done well: orders that arrive, rotas that work, costs that stay where they should."],
    skills: "Operations management · Process improvement · Budgeting · People leadership · Lean · Supplier management · KPIs · Change management",
    services: [["Operations review", "Two weeks on site, then a written plan with costs.", "£6,500"], ["Interim operations manager", "Hands-on cover for three to nine months.", "From £650 / day"], ["Lean training", "Two days for team leaders.", "£2,400"]],
    stats: [["420", "people led"], ["£38m", "budget"], ["96%", "same-day dispatch"]],
    quote: ["Rebecca made the hardest year in our history feel organised.", "Managing Director", "Midland Fresh Foods"],
    experience: [["Operations Manager", "Midland Fresh Foods", "2021", "Present"], ["Operations Team Leader", "Severn Logistics", "2016", "2021"]],
    education: [["BSc Business & Management", "Aston University", "2013"], CMI],
  }, ["annual-report", "field-report", "practice"]),
  role("general-manager", "General Manager", "general managers", "management", ["GM", "managing director", "business manager", "branch manager", "country manager"], {
    title: "General Manager", tagline: "Responsible for the whole business: people, customers and the numbers.",
    bio: ["I run a £45m business unit with 260 people across sales, operations and customer service.", "I took it from a loss to a 9% margin in three years, mainly by fixing service and keeping good people."],
    skills: "P&L ownership · Strategy · Team leadership · Commercial negotiation · Customer experience · Turnarounds",
    services: [["Business turnaround", "A 100-day plan for an underperforming unit.", "Quote"], ["Non-executive director", "Board seat for growing companies.", "From £1,500 / month"], ["Mentoring", "For first-time general managers.", "£250 / session"]],
    stats: [["£45m", "revenue"], ["−3% → 9%", "operating margin"], ["260", "people"]],
    quote: ["Rebecca turned our worst-performing division into the one everyone wants to work in.", "Group CEO", "Midland Fresh Foods"],
    experience: [["General Manager", "Midland Fresh Foods, Food Service", "2022", "Present"], ["Operations Manager", "Midland Fresh Foods", "2018", "2022"]],
    education: [["MBA", "Warwick Business School", "2019"]],
  }, ["annual-report", "keynote"]),
  role("office-manager", "Office Manager", "office managers", "management", ["office administrator", "workplace manager", "practice administrator"], {
    title: "Office Manager", tagline: "A workplace that just works, from Wi-Fi to welcome packs.",
    bio: ["I run a 90-person office: facilities, suppliers, new starters, budgets and the company’s social calendar.", "If something in the building breaks, I usually know before anyone else."],
    skills: "Office operations · Facilities · Supplier contracts · Onboarding · Budgets · Health & safety · Events · Google Workspace",
    services: [["Office set-up", "Everything for a new office, from leases to coffee machines.", "Quote"], ["Interim office manager", "Cover for leave or a move.", "£280 / day"], ["Supplier review", "Cut costs on cleaning, catering and printing.", "£1,200"]],
    stats: [["90", "people supported"], ["£180k", "saved on suppliers"], ["1", "office move, zero downtime"]],
    quote: ["Sofia made our new office feel like home in a week.", "Head of People", "Northwind Pay"],
    experience: [["Office Manager", "Northwind Pay", "2020", "Present"], ["Office Coordinator", "Atelier Nove", "2017", "2020"]],
    education: [["IOSH Managing Safely", "IOSH", "2021"], ["BA Italian & History", "University of Sussex", "2016"]],
    name: "Sofia Marchetti", base: "admin",
  }, ["practice", "prospectus"]),
  role("engineering-manager", "Engineering Manager", "engineering managers", "management", ["software engineering manager", "head of engineering", "VP engineering", "tech lead manager", "CTO"], {
    base: "developer", title: "Engineering Manager, Platform", tagline: "Teams that ship steadily, sleep at night and keep growing.",
    bio: ["I manage two platform teams, twelve engineers in all. I hire, coach, set direction with product and still review the important pull requests.", "My teams cut incidents by two thirds while shipping more than before."],
    skills: "People management · Hiring · Technical strategy · Delivery · Incident management · Career frameworks · Go · Kubernetes",
    services: [["Engineering team review", "Process, architecture and morale, with a written plan.", "€6,000"], ["Interim engineering manager", "Three to six months.", "From €800 / day"], ["First-time manager coaching", "Six sessions.", "€1,200"]],
    stats: [["12", "engineers managed"], ["−65%", "incidents"], ["5", "promotions on my teams"]],
    quote: ["The best manager I’ve had. She gave me room to grow and the cover to fail safely.", "Senior Engineer", "Her team"],
    experience: [["Engineering Manager, Platform", "Northwind Pay", "2022", "Present"], ["Staff Software Engineer", "Northwind Pay", "2019", "2022"]],
    education: [["MSc Informatics Engineering", "University of Porto", "2014"]],
  }, ["blueprint", "terminal", "annual-report"]),
  role("marketing-manager", "Marketing Manager", "marketing managers", "management", ["head of marketing", "marketing lead", "CMO", "marketing director"], {
    base: "marketing", title: "Marketing Manager", tagline: "Marketing that sales trusts and finance can measure.",
    bio: ["I lead a team of six across brand, content, paid and events for a B2B software company.", "I plan around revenue, not vanity metrics, and I report honestly when something doesn’t work."],
    skills: "Marketing strategy · Team leadership · Demand generation · Brand · Budget planning · Attribution · HubSpot · Events",
    services: [["Marketing plan", "A 12-month plan tied to revenue targets.", "€5,500"], ["Fractional marketing lead", "Two days a week.", "From €4,000 / month"], ["Campaign review", "What’s working, what to stop.", "€2,200"]],
    stats: [["+64%", "marketing-sourced pipeline"], ["6", "people in my team"], ["€1.2m", "budget managed"]],
    quote: ["The first marketing lead our sales team asked to keep.", "VP Sales", "Client"],
    experience: [["Marketing Manager", "Northwind Pay", "2022", "Present"], ["Senior Marketing Executive", "Talo", "2018", "2022"]],
    education: [["CIM Diploma in Professional Marketing", "Chartered Institute of Marketing", "2020"]],
  }, ["campaign", "annual-report"]),
  role("hr-manager", "HR Manager", "HR managers", "management", ["people manager", "head of people", "HR director", "personnel manager"], {
    base: "hr", title: "HR Manager", tagline: "Fair policies, good managers and a workplace people want to stay in.",
    bio: ["I look after HR for a 400-person company: employee relations, policies, pay reviews and training for managers.", "I’d rather fix a problem with a good conversation than a long process."],
    skills: "Employee relations · Employment law · Policies · Pay & reward · Wellbeing · Manager training · Workday",
    services: [["HR health check", "Contracts, policies and risks reviewed.", "€3,500"], ["Fractional HR manager", "Two days a week.", "From €3,200 / month"], ["Manager training", "Difficult conversations, one day.", "€2,000"]],
    stats: [["400", "employees supported"], ["−40%", "staff turnover"], ["0", "tribunal claims lost"]],
    quote: ["Ruth handled our restructure with real care. People still thank her.", "Chief Executive", "Client"],
    experience: [["HR Manager", "Talo", "2020", "Present"], ["HR Business Partner", "N26", "2016", "2020"]],
    education: [["CIPD Level 7 Advanced Diploma", "CIPD", "2021"]],
  }, ["practice", "brief"]),
  role("finance-manager", "Finance Manager", "finance managers", "management", ["financial controller", "head of finance", "finance director", "FP&A manager"], {
    base: "finance", title: "Financial Controller", tagline: "Accurate numbers, on time, explained in plain English.",
    bio: ["I run the finance team for a 300-person company: month-end, audit, cash, budgets and the board pack.", "I closed the books in five days instead of fifteen and haven’t missed a deadline since."],
    skills: "Month-end close · Audit · Budgeting · Cash management · Board reporting · IFRS · NetSuite · Team leadership",
    services: [["Finance process review", "Close, controls and systems.", "£4,500"], ["Interim financial controller", "Three to nine months.", "From £700 / day"], ["Audit preparation", "Everything ready before the auditors arrive.", "Quote"]],
    stats: [["5", "day month-end"], ["£48m", "turnover"], ["0", "audit adjustments, 2 years running"]],
    quote: ["Henrik made our audit the calmest it has ever been.", "CFO", "Client"],
    experience: [["Financial Controller", "Fable Foods", "2021", "Present"], ["Finance Manager", "Kontor Software", "2017", "2021"]],
    education: [["Chartered Accountant (ACA)", "ICAEW", "2012"]],
  }, ["prospectus", "annual-report"]),
  role("store-manager", "Retail Store Manager", "store managers", "management", ["shop manager", "retail manager", "branch manager", "area manager"], {
    title: "Store Manager", tagline: "A shop that’s busy, tidy and a good place to work.",
    bio: ["I manage a 40-person flagship store: sales, stock, visual merchandising and the team.", "I turned it from the region’s lowest-rated store for service into the highest in eighteen months."],
    skills: "Retail operations · Sales targets · Visual merchandising · Stock control · Recruitment · Rotas · Customer experience",
    services: [["Store turnaround", "A 90-day plan for an underperforming shop.", "Quote"], ["Team training", "Service and selling, one day.", "£950"], ["Visual merchandising", "Window and floor refresh.", "From £600"]],
    stats: [["£6.8m", "annual sales"], ["+19%", "like-for-like growth"], ["#1", "for service in the region"]],
    quote: ["Rebecca is in the shop, on the floor, every day. The team would do anything for her.", "Area Manager", "Northway Retail"],
    experience: [["Store Manager", "Northway Retail, Birmingham Flagship", "2020", "Present"], ["Assistant Store Manager", "Northway Retail, Coventry", "2016", "2020"]],
    education: [["Retail Management Apprenticeship (Level 5)", "Northway Retail Academy", "2018"]],
  }, ["quota", "site-board"]),
  role("restaurant-manager", "Restaurant Manager", "restaurant managers", "management", ["front of house manager", "general manager restaurant", "bar manager", "hospitality manager"], {
    base: "food", title: "Restaurant General Manager", tagline: "A full room, a happy kitchen and numbers that add up.",
    bio: ["I run a 90-cover restaurant: front of house, bookings, wine list, staffing and the P&L.", "I’ve cut staff turnover in half by fixing rotas and paying tips fairly."],
    skills: "Front of house · P&L · Rotas · Wine list · Bookings · Hiring & training · Health & safety · Licensing",
    services: [["Opening support", "Hiring, training and systems for a new restaurant.", "Quote"], ["Service training", "Front of house, one day.", "£850"], ["Profitability review", "Menu, labour and supplier costs.", "£2,200"]],
    stats: [["90", "covers"], ["−52%", "staff turnover"], ["4.8★", "guest rating"]],
    quote: ["Every guest feels like a regular when he’s on the floor.", "Owner", "Maíz, Soho"],
    experience: [["Restaurant General Manager", "Maíz, Soho", "2021", "Present"], ["Assistant Manager", "Brindisa Kitchen", "2017", "2021"]],
    education: [["WSET Level 3 Award in Wines", "Wine & Spirit Education Trust", "2019"], ["Personal Licence Holder", "Westminster City Council", "2017"]],
    name: "Tomás Ibarra", keepWork: true,
  }, ["carte", "practice"]),
  role("hotel-manager", "Hotel Manager", "hotel managers", "management", ["hotel general manager", "front office manager", "guest relations manager", "hospitality"], {
    title: "Hotel General Manager", tagline: "Guests who come back, and staff who stay.",
    bio: ["I run a 120-room city-centre hotel with a restaurant, bar and conference rooms.", "Guest scores rose from 8.1 to 9.2 under my management, and so did profit."],
    skills: "Hotel operations · Revenue management · Guest experience · Events & conferences · P&L · Team leadership",
    services: [["Hotel performance review", "Rooms, rates, reviews and staffing.", "Quote"], ["Interim general manager", "Three to six months.", "From £700 / day"], ["Service training", "For front office and housekeeping teams.", "£1,100"]],
    stats: [["120", "rooms"], ["8.1 → 9.2", "guest score"], ["86%", "average occupancy"]],
    quote: ["The calmest hotel manager I’ve worked with. Nothing is ever a problem.", "Events client", "Corporate conference"],
    experience: [["Hotel General Manager", "The Mailbox Hotel, Birmingham", "2021", "Present"], ["Front Office Manager", "Grand Severn Hotel", "2016", "2021"]],
    education: [["BA International Hospitality Management", "Oxford Brookes University", "2013"]],
  }, ["practice", "carte"]),
  role("construction-manager", "Construction Manager", "construction managers", "management", ["site manager", "project manager construction", "building manager", "contracts manager"], {
    base: "trades", title: "Construction Site Manager", tagline: "Safe sites, finished on time, handed over without a snagging list.",
    bio: ["I manage residential and commercial builds from groundworks to handover: subcontractors, programme, quality and safety.", "My sites have had no reportable accidents in six years."],
    skills: "Site management · Health & safety · Programming · Subcontractor management · Quality control · CDM · Snagging",
    services: [["Site management", "Full-time site manager for your build.", "From £400 / day"], ["Pre-start review", "Programme, risks and logistics checked.", "£1,800"], ["Health & safety audit", "Site inspection and written report.", "£650"]],
    stats: [["£48m", "of buildings delivered"], ["0", "reportable accidents in 6 years"], ["22", "projects handed over"]],
    quote: ["Sean’s sites are the tidiest and safest we’ve ever seen, and he finishes on time.", "Director", "Developer client"],
    experience: [["Site Manager", "Avon Build", "2018", "Present"], ["Assistant Site Manager", "Severn Construction", "2012", "2018"]],
    education: [["SMSTS & CSCS Black Card", "CITB", "2018"], ["HNC Construction Management", "City of Bristol College", "2014"]],
    name: "Sean Gallagher",
  }, ["site-board", "datasheet"]),
  role("facilities-manager", "Facilities Manager", "facilities managers", "management", ["FM", "estates manager", "building services manager", "property operations"], {
    title: "Facilities Manager", tagline: "Buildings that are safe, compliant and quietly well run.",
    bio: ["I look after six buildings for a healthcare provider: maintenance, cleaning, security, energy and compliance.", "I cut energy use by 23% without anyone feeling colder."],
    skills: "Planned maintenance · Compliance · Contractor management · Energy management · Health & safety · CAFM · Budgets",
    services: [["Compliance audit", "Fire, water, gas and electrical, in one report.", "£1,500"], ["Interim facilities manager", "Three to nine months.", "From £450 / day"], ["Energy review", "Where you’re wasting money.", "£1,200"]],
    stats: [["6", "buildings"], ["−23%", "energy use"], ["100%", "statutory compliance"]],
    quote: ["Since Rebecca joined, I haven’t had a single facilities complaint reach my desk.", "Chief Executive", "Healthcare provider"],
    experience: [["Facilities Manager", "Midlands Community Health", "2020", "Present"], ["Assistant Facilities Manager", "Northway Retail", "2015", "2020"]],
    education: [["IWFM Level 5 Diploma in Workplace & Facilities Management", "IWFM", "2019"]],
  }, ["datasheet", "practice"]),
  role("supply-chain-manager", "Supply Chain Manager", "supply chain managers", "management", ["logistics manager", "procurement manager", "purchasing manager", "inventory manager"], {
    title: "Supply Chain Manager", tagline: "The right stock, in the right place, without tying up cash.",
    bio: ["I manage planning, purchasing and logistics for a food business with 900 product lines and 140 suppliers.", "I reduced stock levels by £4m while improving availability on shelf."],
    skills: "Demand planning · Procurement · Supplier negotiation · Inventory · Logistics · S&OP · SAP · Excel",
    services: [["Supply chain review", "Stock, suppliers and service levels.", "£5,000"], ["Supplier negotiation", "Renewing your biggest contracts.", "Quote"], ["S&OP set-up", "A monthly planning process that works.", "£4,200"]],
    stats: [["−£4m", "stock held"], ["98.6%", "availability"], ["140", "suppliers"]],
    quote: ["Rebecca fixed our availability problem and freed up cash at the same time.", "Finance Director", "Midland Fresh Foods"],
    experience: [["Supply Chain Manager", "Midland Fresh Foods", "2020", "Present"], ["Demand Planner", "Severn Logistics", "2015", "2020"]],
    education: [["MCIPS, Chartered Procurement & Supply", "CIPS", "2019"]],
  }, ["prospectus", "datasheet"]),
  role("customer-service-manager", "Customer Service Manager", "customer service managers", "management", ["contact centre manager", "customer experience manager", "support manager", "call centre manager"], {
    title: "Customer Service Manager", tagline: "Fast answers, real fixes and customers who feel listened to.",
    bio: ["I run a 60-person contact centre handling phone, email and chat for 400,000 customers.", "Satisfaction went from 71% to 92% after we stopped counting call length and started counting problems solved."],
    skills: "Contact centre operations · Customer experience · Quality · Workforce planning · Complaints · Zendesk · Coaching",
    services: [["Service review", "Calls, tickets and processes reviewed.", "£3,500"], ["Complaints training", "Handling difficult customers, one day.", "£1,100"], ["Interim service manager", "Three to six months.", "From £450 / day"]],
    stats: [["71% → 92%", "customer satisfaction"], ["60", "advisors"], ["−45%", "complaints"]],
    quote: ["She made the team proud of working in customer service again.", "Team Leader", "Her team"],
    experience: [["Customer Service Manager", "Midland Energy", "2019", "Present"], ["Team Leader", "Midland Energy", "2015", "2019"]],
    education: [["CCXP, Certified Customer Experience Professional", "CXPA", "2021"]],
  }, ["practice", "quota"]),
  role("brand-manager", "Brand Manager", "brand managers", "management", ["product marketing manager", "category manager", "brand marketing"], {
    base: "marketing", title: "Senior Brand Manager", tagline: "Brands people recognise, trust and choose again.",
    bio: ["I manage a portfolio of three food and drink brands: positioning, packaging, campaigns and launches.", "I launched a new range that became the category’s fastest seller in its first year."],
    skills: "Brand strategy · Product launches · Packaging · Consumer insight · Campaigns · Agency management · Category management",
    services: [["Brand positioning workshop", "One day, with a written positioning.", "€3,800"], ["Launch plan", "Everything needed to launch a new product.", "Quote"], ["Agency review", "Choosing the right creative partner.", "€2,500"]],
    stats: [["3", "brands managed"], ["€22m", "brand revenue"], ["#1", "new launch in category"]],
    quote: ["Sofia knows our shopper better than anyone in the business.", "Category Buyer", "Retail partner"],
    experience: [["Senior Brand Manager", "Fable Foods", "2021", "Present"], ["Brand Manager", "Brook Drinks Co.", "2017", "2021"]],
    education: [["MSc Marketing", "ESADE", "2015"]],
  }, ["campaign", "pitch"]),
  role("it-manager", "IT Manager", "IT managers", "management", ["head of IT", "IT director", "systems manager", "infrastructure manager", "CIO"], {
    base: "developer", title: "IT Manager", tagline: "Reliable systems, secure data and a helpdesk people don’t dread.",
    bio: ["I run IT for a 350-person company across three offices: networks, devices, security, cloud and the helpdesk.", "I moved us to the cloud in six months and passed our first ISO 27001 audit."],
    skills: "IT operations · Cybersecurity · Microsoft 365 · Azure · Networks · ISO 27001 · Vendor management · Helpdesk",
    services: [["IT health check", "Systems, security and costs reviewed.", "€3,500"], ["Cloud migration", "Planning and managing the move.", "Quote"], ["Security readiness", "Getting ready for ISO 27001 or Cyber Essentials.", "€4,800"]],
    stats: [["350", "people supported"], ["99.95%", "uptime"], ["ISO 27001", "certified"]],
    quote: ["Since Ines took over, IT problems simply stopped being a topic in leadership meetings.", "COO", "Northwind Pay"],
    experience: [["IT Manager", "Northwind Pay", "2020", "Present"], ["Systems Administrator", "Porto Digital", "2014", "2020"]],
    education: [["CISSP", "ISC2", "2021"]],
  }, ["datasheet", "terminal"]),
  role("practice-manager", "Practice Manager", "practice managers", "management", ["clinic manager", "surgery manager", "medical practice manager", "dental practice manager"], {
    base: "healthcare", name: "Lucía Ferrer", title: "Practice Manager, Medical Clinic", tagline: "A clinic that runs on time, so doctors can focus on patients.",
    bio: ["I manage a busy private clinic with eight doctors: appointments, staff, billing, insurers and compliance.", "Waiting times are down by half since we redesigned the booking system."],
    skills: "Clinic operations · Patient experience · Billing & insurers · Rotas · Compliance · Data protection · Recruitment",
    services: [["Clinic operations review", "Bookings, billing and patient flow.", "€3,000"], ["Interim practice manager", "Three to six months.", "From €400 / day"], ["New clinic set-up", "Systems and staff for opening day.", "Quote"]],
    stats: [["8", "doctors supported"], ["−50%", "waiting time"], ["€4.2m", "annual billing"]],
    quote: ["Lucía is the reason our clinic runs on time.", "Medical Director", "Clinic"],
    experience: [["Practice Manager", "Consulta Ferrer, Eixample", "2019", "Present"], ["Patient Services Manager", "Hospital Universitari Mediterrani", "2014", "2019"]],
    education: [["Master’s in Healthcare Management", "Universitat Pompeu Fabra", "2016"]],
  }, ["clinic", "practice"]),

  // ——— Office & admin ———
  role("executive-assistant", "Executive Assistant", "executive assistants", "admin", ["EA", "PA", "personal assistant", "chief of staff", "executive PA"], {
    title: "Executive Assistant to the CEO", tagline: "I keep a busy leader’s week calm, so they can do the work only they can do.",
    bio: ["I’ve supported chief executives for nine years, in a fintech, a charity and a design studio. Diaries, travel, board papers, events and the hundred small things that keep an office running.", "I’m discreet, very organised and the person people come to when they don’t know who else to ask."],
    skills: "Diary management · Travel planning · Board papers · Event planning · Office management · Google Workspace · Microsoft 365 · Discretion",
    services: [["Virtual executive assistance", "Diary, inbox and travel, ten hours a week.", "From £450 / month"], ["Event organising", "Offsites, dinners and conferences.", "Quote"], ["Board support", "Papers, minutes and logistics.", "Quote"]],
    stats: [["9", "years supporting CEOs"], ["140", "person retreat organised"], ["3", "languages"]],
    quote: ["Sofia runs my week better than I could.", "Chief Executive", "Northwind Pay"],
    experience: [["Executive Assistant to the CEO", "Northwind Pay", "2021", "Present"], ["Executive Assistant", "City Harvest (charity)", "2018", "2021"]],
    education: [["BA Italian & History", "University of Sussex", "2016"]],
  }, ["practice", "prospectus"]),
  role("virtual-assistant", "Virtual Assistant", "virtual assistants", "admin", ["VA", "online business manager", "remote assistant", "freelance assistant"], {
    title: "Virtual Assistant", tagline: "Your inbox, diary and admin, handled, so you can get back to work.",
    bio: ["I support six founders and small business owners remotely: email, scheduling, invoicing, travel and customer service.", "Clients usually get back eight to ten hours a week."],
    skills: "Inbox management · Scheduling · Invoicing · Customer service · Social media scheduling · Notion · Xero · Canva",
    services: [["Starter package", "Ten hours a month.", "£280 / month"], ["Growth package", "Twenty-five hours a month.", "£650 / month"], ["One-off projects", "Tidying a CRM, planning a launch.", "£30 / hour"]],
    stats: [["6", "regular clients"], ["8–10", "hours a week saved"], ["24h", "response time"]],
    quote: ["I finally take weekends off. Sofia is the best investment I’ve made in the business.", "Founder", "Client"],
    experience: [["Virtual Assistant", "Self-employed", "2022", "Present"], ["Executive Assistant", "City Harvest (charity)", "2018", "2022"]],
    education: [["BA Italian & History", "University of Sussex", "2016"]],
  }, ["practice", "rolodex"]),
  role("administrator", "Office Administrator", "office administrators", "admin", ["admin assistant", "administrative assistant", "receptionist", "secretary", "office coordinator"], {
    title: "Office Administrator", tagline: "Organised, reliable and the first friendly face people meet.",
    bio: ["I keep a busy architecture office running: reception, post, supplies, meeting rooms, invoices and new starters.", "I like systems that save everyone time, and I build them in spreadsheets when there isn’t one."],
    skills: "Reception · Scheduling · Invoicing · Data entry · Supplies · Minute-taking · Microsoft 365 · Customer service",
    services: [["Temporary admin cover", "Daily or weekly.", "£22 / hour"], ["Office systems set-up", "Filing, booking and supplies.", "Quote"], ["Minute-taking", "For board and team meetings.", "£120 / meeting"]],
    stats: [["6", "years in office admin"], ["40", "people supported"], ["2", "languages"]],
    quote: ["Sofia notices what needs doing and does it before anyone asks.", "Office Manager", "Atelier Nove"],
    experience: [["Office Administrator", "Atelier Nove", "2021", "Present"], ["Receptionist", "Kensington Dental", "2018", "2021"]],
    education: [["Level 3 Business Administration", "Westminster Kingsway College", "2018"]],
  }, ["practice", "exercise-book"]),
];
