import { role } from "./types";

/** Sales, from first calls to the board. Based on the Chicago sales persona; prices in US dollars. */
export const SALES_ROLES = [
  role("sdr", "Sales Development Representative", "sales development reps", "sales", ["SDR", "BDR", "business development representative", "lead generation", "cold calling"], {
    title: "Sales Development Representative", tagline: "I open the conversations that turn into pipeline.",
    bio: ["I book first meetings for the enterprise team: research, cold calls, short emails and a lot of follow-up. I’ve been top of the SDR board four quarters out of six.", "I’m working towards a closing role and learning from every call I sit in on."],
    skills: "Outbound prospecting · Cold calling · Email sequencing · Discovery · Salesforce · Outreach · LinkedIn Sales Navigator · Objection handling",
    services: [["Account research", "One-page briefs on target accounts before the first touch.", ""], ["Outbound campaigns", "Multi-touch sequences written for one industry at a time.", ""], ["Event follow-up", "Every badge scan called within 48 hours.", ""]],
    stats: [["138%", "of meeting target, FY25"], ["$3.1M", "pipeline sourced"], ["#1", "SDR board, 4 quarters"]],
    quote: ["Jordan’s meetings show up, and they’re the right people. My win rate on his pipeline is double the team average.", "Enterprise AE", "Clarity Health Systems"],
    experience: [["Sales Development Representative", "Clarity Health Systems", "2023", "Present"], ["Customer Service Advisor", "Midwest Bank", "2021", "2023"]],
    education: [["BA Communication", "DePaul University", "2021"]],
    availability: "Ready for an Account Executive role",
  }, ["quota", "practice", "keynote"]),
  role("account-executive", "Account Executive", "account executives", "sales", ["AE", "closer", "B2B sales", "SaaS sales"], {
    title: "Account Executive, Mid-Market", tagline: "I sell software people actually use after they buy it.",
    bio: ["I run full sales cycles for mid-market companies: discovery, demo, business case, negotiation and handover to customer success.", "Most of my deals close in 60–90 days, and most of my customers expand in their first year."],
    skills: "Full-cycle sales · Discovery · Demos · Business cases · Negotiation · MEDDICC · Salesforce · Gong",
    services: [["Discovery workshop", "An hour mapping your process before anyone sees a demo.", ""], ["Tailored demo", "Your data, your workflow, no generic slides.", ""], ["Business case", "A one-page ROI case your finance team can check.", ""]],
    stats: [["121%", "of quota, FY25"], ["$1.4M", "closed last year"], ["74", "days average cycle"]],
    quote: ["The only rep who asked about our month-end close before showing us anything. We signed in seven weeks.", "Controller", "Mid-market customer"],
    experience: [["Account Executive, Mid-Market", "Brightline Software", "2022", "Present"], ["Sales Development Representative", "Brightline Software", "2020", "2022"]],
    education: [["BS Marketing", "University of Illinois Chicago", "2020"]],
  }, ["quota", "practice"]),
  role("enterprise-ae", "Enterprise Account Executive", "enterprise account executives", "sales", ["strategic account executive", "enterprise sales", "key account"], {
    title: "Enterprise Account Executive", tagline: "I sell complex software to careful buyers, and they renew.",
    bio: ["I sell clinical-workflow software to hospital networks: long cycles, many stakeholders and procurement teams who read every clause.", "I win by understanding the buyer’s problem better than they expect and by being straight about what our product won’t do."],
    skills: "Enterprise sales · MEDDICC · Executive selling · Procurement · Negotiation · Forecasting · Salesforce · Partner selling",
    services: [["Executive briefing", "A 30-minute session with your leadership on the problem, not the product.", ""], ["Pilot design", "A measured 90-day pilot with success criteria agreed upfront.", ""], ["Procurement support", "Security reviews, contracts and references handled in one place.", ""]],
    stats: [["142%", "of quota, FY25"], ["3×", "President’s Club"], ["$9.6M", "closed in 3 years"]],
    quote: ["Jordan was the only vendor who asked to meet our charge nurses. That’s why we signed.", "VP Operations", "Hospital network customer"],
    experience: [["Enterprise Account Executive", "Clarity Health Systems", "2021", "Present"], ["Account Executive", "Brightline Software", "2018", "2021"]],
    education: [["BS Business Administration", "University of Illinois Urbana-Champaign", "2016"]],
    keepWork: true,
  }, ["quota", "practice"]),
  role("account-manager", "Account Manager", "account managers", "sales", ["key account manager", "client manager", "relationship manager", "farmer"], {
    title: "Key Account Manager", tagline: "I look after customers so well they buy more without being sold to.",
    bio: ["I manage 28 of our largest customers: quarterly reviews, renewals, expansion and the occasional escalation at 7am.", "My accounts renew at 98% and grew 31% last year, mostly because I know their business as well as ours."],
    skills: "Account planning · Renewals · Upselling · Quarterly business reviews · Stakeholder mapping · Escalations · HubSpot · Gainsight",
    services: [["Quarterly review", "What you got, what it was worth and what’s next, on one page.", ""], ["Expansion plan", "Where more seats or modules would pay for themselves.", ""], ["Renewal", "No surprises: terms agreed 90 days before the date.", ""]],
    stats: [["98%", "gross renewal rate"], ["+31%", "account growth"], ["28", "key accounts"]],
    quote: ["Jordan knows our roadmap almost better than we do. Every renewal has been a ten-minute call.", "Head of Operations", "Key account"],
    experience: [["Key Account Manager", "Clarity Health Systems", "2021", "Present"], ["Account Manager", "Brightline Software", "2017", "2021"]],
    education: [["BA Economics", "Loyola University Chicago", "2017"]],
  }, ["quota", "practice"]),
  role("sales-manager", "Sales Manager", "sales managers", "sales", ["team lead sales", "regional sales manager", "area sales manager", "first-line manager"], {
    title: "Regional Sales Manager", tagline: "I build sales teams that hit their number without burning out.",
    bio: ["I lead a team of nine account executives across the Midwest. I hire carefully, coach every week and forecast honestly.", "Eight of my reps have hit President’s Club and four have been promoted into leadership."],
    skills: "Sales leadership · Hiring · Coaching · Forecasting · Pipeline reviews · Territory planning · Compensation design · Salesforce",
    services: [["Pipeline review", "A weekly hour per rep: what’s real, what’s stuck, what’s next.", ""], ["Rep onboarding", "A 60-day ramp plan with call shadowing and certification.", ""], ["Territory plan", "Accounts split fairly by potential, not by history.", ""]],
    stats: [["112%", "team attainment, FY25"], ["9", "account executives"], ["±4%", "forecast accuracy"]],
    quote: ["The best manager I’ve had. He made me better on every call without taking over a single one.", "Account Executive", "His team"],
    experience: [["Regional Sales Manager", "Clarity Health Systems", "2022", "Present"], ["Enterprise Account Executive", "Clarity Health Systems", "2019", "2022"], ["Account Executive", "Brightline Software", "2016", "2019"]],
    education: [["MBA", "University of Chicago Booth", "2021"]],
  }, ["quota", "annual-report", "practice"]),
  role("sales-director", "Sales Director", "sales directors", "sales", ["VP of sales", "head of sales", "chief revenue officer", "CRO", "commercial director"], {
    title: "VP of Sales", tagline: "Predictable revenue from a team people want to join.",
    bio: ["I run a 40-person sales organisation selling to healthcare and financial services. I took the company from $8M to $31M in annual recurring revenue.", "I care about three things: hiring well, forecasting honestly and selling only what we can deliver."],
    skills: "Revenue leadership · Go-to-market strategy · Board reporting · Forecasting · Sales operations · Hiring · Pricing · Enterprise deals",
    services: [["Go-to-market review", "Where your next million in revenue will come from, and what it costs.", ""], ["Sales leadership coaching", "Monthly sessions for first-time sales leaders.", ""], ["Board advisor", "Revenue strategy for early-stage companies.", ""]],
    stats: [["$8M → $31M", "ARR in four years"], ["40", "people in sales"], ["±3%", "forecast accuracy"]],
    quote: ["Jordan turned sales from the part of the board meeting we dreaded into the part we trusted.", "CEO", "Clarity Health Systems"],
    experience: [["VP of Sales", "Clarity Health Systems", "2021", "Present"], ["Director of Sales", "Brightline Software", "2017", "2021"], ["Regional Sales Manager", "Brightline Software", "2014", "2017"]],
    education: [["MBA", "Northwestern Kellogg", "2014"]],
  }, ["annual-report", "keynote", "quota"]),
  role("sales-engineer", "Sales Engineer", "sales engineers", "sales", ["solutions engineer", "pre-sales", "presales consultant", "solutions consultant"], {
    title: "Senior Solutions Engineer", tagline: "I make the demo work, and then make the product work for you.",
    bio: ["I’m the technical half of the sales team: discovery calls, live demos, proofs of concept and the security questionnaire nobody else wants.", "Before sales I was a backend engineer, so I can talk to your developers in their language."],
    skills: "Technical discovery · Demos · Proofs of concept · Integrations · APIs · Security reviews · SQL · Python",
    services: [["Technical deep-dive", "Two hours with your engineers on architecture and integration.", ""], ["Proof of concept", "Your data, your systems, agreed success criteria.", ""], ["Security review", "Questionnaires, pen-test reports and calls with your security team.", ""]],
    stats: [["$12M", "pipeline supported"], ["78%", "POC win rate"], ["140+", "security reviews"]],
    quote: ["Jordan answered every question our architects threw at him, live, with no slides.", "CTO", "Enterprise customer"],
    experience: [["Senior Solutions Engineer", "Clarity Health Systems", "2021", "Present"], ["Backend Engineer", "Brightline Software", "2016", "2021"]],
    education: [["BS Computer Science", "Purdue University", "2016"]],
  }, ["quota", "practice"]),
  role("customer-success-manager", "Customer Success Manager", "customer success managers", "sales", ["CSM", "customer success", "client success", "onboarding manager"], {
    title: "Customer Success Manager", tagline: "Customers who get value stay. I make sure they get it.",
    bio: ["I onboard and look after 45 mid-market customers, from the kickoff call to the renewal two years later.", "I measure myself on adoption and outcomes, not on how many calls I take."],
    skills: "Onboarding · Adoption · Health scores · Renewals · Churn prevention · Training · Gainsight · Zendesk",
    services: [["Onboarding", "A 30-day plan to get your team live and using it.", ""], ["Health check", "Usage, outcomes and risks, reviewed every quarter.", ""], ["Team training", "Live sessions for new joiners and power users.", ""]],
    stats: [["96%", "logo retention"], ["+18 pts", "adoption in 90 days"], ["45", "customers"]],
    quote: ["Our team went from tolerating the tool to asking for more licences. That was Jordan.", "Director of Operations", "Customer"],
    experience: [["Customer Success Manager", "Brightline Software", "2021", "Present"], ["Implementation Specialist", "Brightline Software", "2019", "2021"]],
    education: [["BA Psychology", "University of Wisconsin–Madison", "2019"]],
  }, ["practice", "quota"]),
  role("medical-sales-rep", "Medical & Pharmaceutical Sales Rep", "medical sales reps", "sales", ["pharmaceutical sales", "pharma rep", "medical device sales", "medical rep", "territory manager"], {
    title: "Medical Device Territory Manager", tagline: "I help surgeons and theatre teams get the most from the devices they choose.",
    bio: ["I cover orthopaedic accounts across northern Illinois: product training, theatre support during cases and contract renewals with hospital procurement.", "I’ve been in more than 900 operating theatres, and I know when to speak and when to stay quiet."],
    skills: "Territory management · Clinical selling · Theatre support · Product training · Tenders · Key opinion leaders · CRM · Compliance",
    services: [["In-theatre support", "Case coverage for new devices until the team is confident.", ""], ["Staff training", "Hands-on sessions for nurses and theatre staff.", ""], ["Evaluations", "Structured product trials with agreed outcomes.", ""]],
    stats: [["134%", "of territory target"], ["900+", "cases supported"], ["Rep of the Year", "2024"]],
    quote: ["Jordan knows the kit better than the manual and never gets in the way of the surgeon.", "Theatre Manager", "Regional hospital"],
    experience: [["Territory Manager, Orthopaedics", "Stryde Medical", "2020", "Present"], ["Pharmaceutical Sales Representative", "Midwest Pharma", "2016", "2020"]],
    education: [["BS Biology", "University of Iowa", "2016"]],
  }, ["quota", "practice"]),
  role("insurance-agent", "Insurance Agent", "insurance agents", "sales", ["insurance broker", "life insurance", "insurance advisor", "financial representative"], {
    title: "Independent Insurance Agent", tagline: "The right cover, explained in plain English, before you need it.",
    bio: ["I help families and small businesses in Chicago compare home, auto, life and business insurance from 14 carriers.", "I review every client’s cover each year and I pick up the phone when there’s a claim."],
    skills: "Home & auto · Life insurance · Small business cover · Claims support · Policy reviews · Licensed in IL & IN",
    services: [["Free cover review", "I look at what you have and tell you what’s missing.", "Free"], ["Small business package", "Liability, property and workers’ comp in one place.", "Quote"], ["Annual check-in", "Your cover updated for a new car, house or baby.", "Included"]],
    stats: [["1,200", "households covered"], ["14", "carriers compared"], ["4.9★", "from 260 reviews"]],
    quote: ["When the basement flooded, Jordan was on the phone with the adjuster before I’d found a towel.", "Homeowner", "Client since 2019"],
    experience: [["Independent Insurance Agent", "Reyes Insurance Group", "2018", "Present"], ["Agent", "State Mutual", "2014", "2018"]],
    education: [["Illinois Property & Casualty and Life licences", "Illinois Department of Insurance", "2014"]],
  }, ["practice", "site-board"]),
  role("car-sales", "Car Sales Executive", "car sales executives", "sales", ["auto sales", "car salesman", "dealership sales", "automotive sales"], {
    title: "Sales Executive, New & Used", tagline: "No pressure, no games, and the paperwork done in an hour.",
    bio: ["I sell new and used cars at a family-owned dealership in Naperville. Most of my customers come back, and send their kids.", "I’ll tell you if the car you want isn’t the right one for you."],
    skills: "New & used sales · Trade-in valuations · Finance & leasing · Test drives · Customer follow-up · CRM",
    services: [["Test drive at home", "Bring the car to you for a weekend.", "Free"], ["Trade-in valuation", "A written price in 20 minutes.", "Free"], ["Finance options", "Lease, loan or cash, compared side by side.", ""]],
    stats: [["212", "cars sold last year"], ["61%", "repeat & referral customers"], ["Top seller", "8 months of 12"]],
    quote: ["The easiest car purchase I’ve ever made. He talked me out of the bigger model and saved me $6,000.", "Customer", "2025"],
    experience: [["Sales Executive", "Prairie Motors", "2019", "Present"], ["Service Advisor", "Prairie Motors", "2016", "2019"]],
    education: [["Certified Sales Professional", "National Automobile Dealers Association", "2020"]],
  }, ["site-board", "quota"]),
  role("retail-sales", "Retail Sales Associate", "retail sales associates", "sales", ["shop assistant", "sales assistant", "store associate", "retail sales"], {
    title: "Senior Sales Associate", tagline: "I help people find the thing they came in for, and leave happy.",
    bio: ["I work on the floor at a specialist outdoor store: fitting boots, advising on kit and running the loyalty programme.", "I train new starters and I’m the go-to person for anything technical."],
    skills: "Customer service · Product knowledge · Visual merchandising · Point of sale · Stock management · Training new staff",
    services: [["Boot fitting", "A proper fitting with a walk on the test ramp.", "Free"], ["Kit advice", "What you need for the trip, and what you don’t.", "Free"], ["Personal shopping", "Book a quiet hour before opening.", "By appointment"]],
    stats: [["118%", "of sales target"], ["4.9★", "customer rating"], ["12", "new starters trained"]],
    quote: ["Jordan spent forty minutes finding boots that fit my wide feet. Three hundred miles later, no blisters.", "Customer", "Review"],
    experience: [["Senior Sales Associate", "Lakefront Outdoors", "2022", "Present"], ["Sales Associate", "Lakefront Outdoors", "2020", "2022"]],
    education: [["Associate Degree, Business", "Harold Washington College", "2020"]],
  }, ["practice", "quota"]),
  role("field-sales", "Field Sales Representative", "field sales reps", "sales", ["outside sales", "territory sales", "sales rep", "travelling salesperson", "B2B sales rep"], {
    title: "Field Sales Representative", tagline: "I’m on the road so my customers don’t have to chase anyone.",
    bio: ["I sell building supplies to contractors and merchants across five counties. I visit 25 customers a week and know most of them by first name.", "I won the region’s biggest account last year by turning up every Tuesday for eight months."],
    skills: "Territory planning · Relationship selling · Trade accounts · Price negotiation · Product demos · Route planning · CRM",
    services: [["Site visits", "On site with samples and prices, when it suits you.", ""], ["Trade account set-up", "Credit terms and pricing agreed in a week.", ""], ["Project quotes", "Whole-job pricing for larger builds.", ""]],
    stats: [["$2.8M", "territory revenue"], ["+22%", "year on year"], ["25", "visits a week"]],
    quote: ["Jordan turns up when he says he will and fixes problems before we know we have them.", "Owner", "General contractor"],
    experience: [["Field Sales Representative", "Great Lakes Building Supply", "2019", "Present"], ["Inside Sales", "Great Lakes Building Supply", "2016", "2019"]],
    education: [["BA Business", "Northern Illinois University", "2016"]],
  }, ["quota", "site-board"]),
  role("partner-manager", "Channel & Partner Manager", "partner managers", "sales", ["channel sales", "partnerships manager", "alliances", "reseller manager"], {
    title: "Channel Partner Manager", tagline: "I build partnerships that sell for us while we sleep.",
    bio: ["I recruit, train and grow resellers and consulting partners across North America. Partners now source a third of our new revenue.", "I treat partners like customers: clear terms, quick answers and shared plans."],
    skills: "Channel strategy · Partner recruitment · Enablement · Co-selling · Joint business plans · Deal registration · PRM tools",
    services: [["Partner programme design", "Tiers, margins and rules of engagement.", ""], ["Enablement", "Certification courses for partner sales and delivery teams.", ""], ["Joint planning", "Quarterly business plans with each top partner.", ""]],
    stats: [["34%", "of new revenue via partners"], ["46", "active partners"], ["$5.2M", "partner-sourced, FY25"]],
    quote: ["Jordan made us feel like an extension of his team. We doubled our practice in two years.", "Managing Partner", "Consulting partner"],
    experience: [["Channel Partner Manager", "Clarity Health Systems", "2021", "Present"], ["Account Executive", "Brightline Software", "2017", "2021"]],
    education: [["BA Political Science", "University of Michigan", "2017"]],
  }, ["quota", "practice"]),
];
