import { role } from "./types";

/** Teaching, trades, beauty, food, events, engineering, tech, wellness and creative work. */
const QTS: [string, string, string] = ["PGCE with Qualified Teacher Status", "Leeds Beckett University", "2016"];
const TRADE_INS = "£5m public liability insurance";

export const WORK_ROLES = [
  // ——— Teaching (Leeds, £) ———
  role("primary-teacher", "Primary School Teacher", "primary teachers", "education", ["primary teacher", "elementary teacher", "KS2 teacher", "year 6 teacher", "reception teacher"], {
    title: "Year 4 Teacher & Maths Lead", tagline: "Children who can’t wait to show you what they’ve learned.",
    bio: ["I teach Year 4 in a Leeds primary and lead maths across the school.", "My classroom is noisy in the good way: lots of talk, lots of hands-on maths, and reading every single day."],
    skills: "Primary maths · Phonics · Reading for pleasure · Behaviour · SEND support · Curriculum planning · Parent partnerships",
    services: [["KS2 maths tutoring", "One hour, in person or online.", "£35 / hour"], ["11+ preparation", "Small-group sessions.", "£25 / session"], ["Maths CPD", "Twilight training for primary staff.", "£300"]],
    stats: [["93%", "reaching expected standard in maths"], ["8", "years teaching"], ["30", "children every year"]],
    quote: ["Our daughter used to cry about maths. Now she does times tables for fun.", "Parent", "Year 4"],
    experience: [["Year 4 Teacher & Maths Lead", "Meanwood Primary School", "2019", "Present"], ["Year 2 Teacher", "Chapel Allerton Primary", "2016", "2019"]],
    education: [["BA Primary Education with QTS", "Leeds Trinity University", "2016"]],
  }, ["exercise-book", "margin-notes", "syllabus"]),
  role("secondary-teacher", "Secondary School Teacher", "secondary teachers", "education", ["high school teacher", "secondary teacher", "science teacher", "maths teacher", "english teacher"], {
    title: "Secondary Science Teacher & Head of Year 9", tagline: "I teach teenagers that they are better at science than they think.",
    bio: ["I’ve taught science in a Leeds comprehensive for nine years. I like practical lessons, low-stakes quizzing and the moment a quiet student explains something to the rest of the class.", "I also tutor GCSE and A-level Chemistry online."],
    skills: "GCSE Chemistry · A-level Chemistry · KS3 Science · Practical work · Retrieval practice · Pastoral leadership",
    services: [["GCSE Chemistry tutoring", "One hour online.", "£45 / hour"], ["A-level Chemistry tutoring", "Exam technique and past papers.", "£55 / hour"], ["Teacher training", "Half-day INSET on retrieval practice.", "£450"]],
    stats: [["94%", "grade 4+ in GCSE Chemistry"], ["9", "years teaching"], ["41k", "resource downloads"]],
    quote: ["Miss Mensah never makes you feel stupid for asking.", "Year 10 student", "Roundhay Park Academy"],
    experience: [["Teacher of Science & Head of Year 9", "Roundhay Park Academy", "2019", "Present"], ["Teacher of Science", "Hunslet Moor High School", "2016", "2019"]],
    education: [["BSc Chemistry", "University of Leeds", "2014"], QTS],
  }, ["exercise-book", "margin-notes", "syllabus"]),
  role("private-tutor", "Private Tutor", "tutors", "education", ["tutor", "online tutor", "home tutor", "GCSE tutor", "maths tutor", "exam coach"], {
    title: "GCSE & A-level Maths Tutor", tagline: "Calm, patient tutoring that turns ‘I can’t’ into ‘I get it’.",
    bio: ["I tutor GCSE and A-level maths one-to-one, online and in Leeds. I was a secondary teacher for seven years before tutoring full time.", "Parents get a short note after every session saying what we covered and what to practise."],
    skills: "GCSE Maths · A-level Maths · Further Maths · Exam technique · Maths anxiety · Online tutoring",
    services: [["GCSE Maths", "One hour, online or in person.", "£45 / hour"], ["A-level Maths", "One hour, online.", "£55 / hour"], ["Exam bootcamp", "Five sessions over the Easter holidays.", "£200"]],
    stats: [["+2", "grades average improvement"], ["140", "students tutored"], ["5.0★", "from 60 parent reviews"]],
    quote: ["From a 3 to a 7 in eight months. He actually smiles when he does maths now.", "Parent", "GCSE student"],
    experience: [["Private Tutor", "Self-employed", "2023", "Present"], ["Teacher of Maths", "Roundhay Park Academy", "2016", "2023"]],
    education: [["BSc Mathematics", "University of York", "2015"], QTS],
  }, ["exercise-book", "margin-notes", "practice"]),
  role("sen-teacher", "SEN Teacher", "SEN teachers", "education", ["special needs teacher", "SENCO", "special education teacher", "learning support teacher"], {
    title: "SENCO & Specialist Teacher", tagline: "Every child can learn. My job is finding how.",
    bio: ["I coordinate special educational needs in a secondary school and teach small groups with dyslexia, autism and ADHD.", "I work closely with families and make sure plans are actually followed in every classroom."],
    skills: "SEN coordination · Dyslexia · Autism · ADHD · EHCPs · Access arrangements · Staff training",
    services: [["Dyslexia assessment", "Full diagnostic assessment and report.", "£480"], ["Specialist tutoring", "One hour, literacy or numeracy.", "£50 / hour"], ["Staff training", "Inclusive classrooms, half day.", "£500"]],
    stats: [["160", "students on our SEN register"], ["11", "years teaching"], ["NASENCO", "qualified"]],
    quote: ["For the first time, school understands our son, and he’s happy to go.", "Parent", "Year 8"],
    experience: [["SENCO", "Roundhay Park Academy", "2020", "Present"], ["Learning Support Teacher", "Hunslet Moor High School", "2014", "2020"]],
    education: [QTS, ["National Award for SEN Coordination", "University of Leeds", "2021"]],
  }, ["exercise-book", "margin-notes", "sanctuary"]),
  role("music-teacher", "Music Teacher", "music teachers", "education", ["piano teacher", "guitar teacher", "singing teacher", "violin teacher", "music tutor"], {
    title: "Piano & Theory Teacher", tagline: "Lessons that build confident, curious musicians.",
    bio: ["I teach piano and music theory to children and adults, from first notes to Grade 8 and diploma.", "Lessons mix exam pieces with music students choose, so practice doesn’t feel like homework."],
    skills: "Piano · Music theory · ABRSM exams · Composition · Adult beginners · Ensemble coaching",
    services: [["Piano lesson", "Thirty or forty-five minutes, weekly.", "£22 / £32"], ["Theory course", "Grade 5 theory in ten lessons.", "£280"], ["Adult beginners", "Four-lesson starter pack.", "£110"]],
    stats: [["100%", "exam pass rate"], ["40", "students"], ["12", "years teaching"]],
    quote: ["My son passed Grade 5 with distinction and still loves practising.", "Parent", "Student"],
    experience: [["Piano Teacher", "Self-employed", "2014", "Present"], ["Peripatetic Music Teacher", "Leeds Music Service", "2012", "2018"]],
    education: [["BMus Music", "Leeds Conservatoire", "2012"]],
  }, ["liner-notes", "margin-notes", "exercise-book"]),
  role("language-teacher", "Language Teacher", "language teachers", "education", ["ESL teacher", "English teacher", "Spanish teacher", "French teacher", "TEFL teacher"], {
    title: "English & Spanish Teacher", tagline: "Speak from the first lesson, with grammar that makes sense.",
    bio: ["I teach English to adults and Spanish to teenagers and adults, online and in Leeds.", "Lessons are built around real conversations, with grammar explained only when you need it."],
    skills: "English as a foreign language · Spanish · IELTS · Business English · Conversation · GCSE Spanish",
    services: [["Conversation lesson", "One hour online.", "£30"], ["IELTS preparation", "Ten-lesson course.", "£320"], ["Business English", "For teams, per hour.", "£55"]],
    stats: [["600+", "students taught"], ["7.5", "average IELTS score"], ["CELTA", "qualified"]],
    quote: ["I passed IELTS with 8.0 and got my nursing registration.", "Student", "IELTS course"],
    experience: [["Language Teacher", "Self-employed", "2018", "Present"], ["Teacher of Spanish", "Roundhay Park Academy", "2015", "2018"]],
    education: [["CELTA", "Cambridge English", "2017"], QTS],
  }, ["exercise-book", "margin-notes", "practice"]),
  role("lecturer", "University Lecturer", "lecturers", "education", ["professor", "college lecturer", "academic", "teaching fellow", "FE lecturer"], {
    title: "Senior Lecturer in Chemistry Education", tagline: "Teaching that sticks, backed by research.",
    bio: ["I lecture first-year chemistry and run the university’s teacher training course for science graduates.", "My research is on how students learn practical skills."],
    skills: "Lecturing · Curriculum design · Assessment · Teacher education · Educational research · Supervision",
    services: [["Guest lecture", "On practical science education.", "Quote"], ["Curriculum review", "For schools and colleges.", "Quote"], ["Keynote", "Conferences for teachers.", "Quote"]],
    stats: [["400", "students a year"], ["18", "papers published"], ["National Teaching Fellow", "2024"]],
    quote: ["The best lecturer I had. She made a 300-seat room feel like a seminar.", "Former student", "BSc Chemistry"],
    experience: [["Senior Lecturer", "University of Leeds", "2021", "Present"], ["Teacher of Science", "Roundhay Park Academy", "2016", "2021"]],
    education: [["PhD Chemistry Education", "University of Leeds", "2020"]],
  }, ["seminar", "margin-notes", "syllabus"]),
  role("driving-instructor", "Driving Instructor", "driving instructors", "education", ["ADI", "driving school", "driving teacher"], {
    title: "Approved Driving Instructor", tagline: "Calm lessons, first-time passes and safe drivers for life.",
    bio: ["I teach learners in north Leeds in a dual-control automatic.", "Nervous drivers are my speciality. We go at your pace."],
    skills: "Manual & automatic · Nervous drivers · Intensive courses · Motorway lessons · Pass Plus · Refresher lessons",
    services: [["Single lesson", "Ninety minutes.", "£54"], ["Block of 10 hours", "Paid upfront.", "£340"], ["Intensive course", "Twenty hours in two weeks.", "£760"]],
    stats: [["78%", "first-time pass rate"], ["900+", "pupils passed"], ["5.0★", "from 220 reviews"]],
    quote: ["I was terrified of driving. Grace got me through first time.", "Pupil", "Passed 2025"],
    experience: [["Approved Driving Instructor", "Mensah School of Motoring", "2017", "Present"]],
    education: [["Approved Driving Instructor (ADI)", "DVSA", "2017"]],
  }, ["site-board", "margin-notes", "practice"]),
  role("headteacher", "Headteacher", "headteachers", "education", ["head teacher", "principal", "school leader", "deputy head", "assistant head"], {
    title: "Headteacher", tagline: "A school where every child is known and every teacher wants to stay.",
    bio: ["I lead a 900-pupil secondary school in Leeds. We moved from Requires Improvement to Good in three years.", "I teach a Year 7 science class every week, because leaders should still teach."],
    skills: "School leadership · School improvement · Curriculum · Staff development · Safeguarding · Budgets · Governance",
    services: [["School improvement review", "Two days in school with a written report.", "Quote"], ["Leadership coaching", "For new heads and deputies.", "Quote"], ["Speaking", "Conferences and trust events.", "Quote"]],
    stats: [["900", "pupils"], ["RI → Good", "inspection"], ["−60%", "teacher turnover"]],
    quote: ["She knows every child’s name, and every teacher feels backed.", "Chair of Governors", "Roundhay Park Academy"],
    experience: [["Headteacher", "Roundhay Park Academy", "2022", "Present"], ["Deputy Headteacher", "Hunslet Moor High School", "2018", "2022"]],
    education: [["NPQH", "Department for Education", "2021"], QTS],
  }, ["annual-report", "margin-notes", "exercise-book"]),

  // ——— Trades (Bristol, £) ———
  ...([
    ["electrician", "Electrician", "electricians", ["sparky", "electrical contractor", "domestic electrician"], "Electrician · Gallagher Electrical", "Safe, tidy electrical work, done when we said it would be.", "Full rewires · Consumer units · EV chargers · Solar PV & batteries · Fault finding · EICRs", [["Electrical safety check (EICR)", "Full test with written report.", "From £180"], ["Consumer unit upgrade", "RCBO board, tested and certified.", "From £650"], ["EV charger installed", "7kW smart charger, certified.", "From £899"]], "NICEIC Approved Contractor"],
    ["plumber", "Plumber", "plumbers", ["plumbing", "emergency plumber", "bathroom fitter"], "Plumber · Gallagher Plumbing", "Leaks fixed fast, bathrooms fitted properly.", "Leaks & repairs · Bathroom fitting · Boiler swaps · Unvented cylinders · Power flushing · Emergency call-outs", [["Call-out", "First hour, Bristol area.", "£75"], ["Bathroom installation", "Supply and fit, fixed quote.", "From £5,500"], ["Power flush", "Cleaner radiators, lower bills.", "£420"]], "WaterSafe approved plumber"],
    ["carpenter", "Carpenter & Joiner", "carpenters", ["joiner", "cabinet maker", "fitted furniture", "chippy"], "Carpenter & Joiner · Gallagher Joinery", "Fitted furniture, doors and stairs, made to last.", "Fitted wardrobes · Alcove shelving · Doors & frames · Staircases · Kitchens · Flooring · Bespoke furniture", [["Alcove units", "Cupboards and shelves, painted.", "From £1,400"], ["Fitted wardrobe", "Made to measure, floor to ceiling.", "From £2,200"], ["Door hanging", "Per internal door.", "£95"]], "City & Guilds Site Carpentry"],
    ["builder", "Builder", "builders", ["building contractor", "general builder", "extensions", "renovations", "loft conversion"], "Builder · Gallagher Build", "Extensions and renovations, finished on time and on budget.", "Extensions · Loft conversions · Renovations · Structural alterations · Project management · Building regs", [["Free site visit", "Ideas, rough costs and timeline.", "Free"], ["Single-storey extension", "Fixed-price quote after drawings.", "From £45,000"], ["Loft conversion", "Dormer, including stairs and en-suite.", "From £52,000"]], "Federation of Master Builders member"],
    ["roofer", "Roofer", "roofers", ["roofing contractor", "roof repairs", "flat roofing"], "Roofer · Gallagher Roofing", "Roofs that keep the weather out for decades.", "Roof repairs · Re-roofing · Flat roofs · Chimneys · Guttering · Leadwork · Velux windows", [["Roof inspection", "With drone photos and written report.", "£120"], ["Repair", "Slipped tiles, flashing, leaks.", "From £180"], ["Flat roof replacement", "EPDM rubber, 20-year guarantee.", "From £2,400"]], "NFRC member"],
    ["painter-decorator", "Painter & Decorator", "painters and decorators", ["decorator", "painter", "wallpapering", "house painter"], "Painter & Decorator · Gallagher Decorating", "Sharp lines, clean floors and walls you’ll love.", "Interior painting · Exterior painting · Wallpapering · Woodwork · Spraying · Period properties", [["Room repaint", "Walls, ceiling and woodwork.", "From £450"], ["Exterior repaint", "Three-bed house, including prep.", "From £3,200"], ["Wallpapering", "Per feature wall.", "From £280"]], "Dulux Select Decorator"],
    ["heating-engineer", "Heating & Gas Engineer", "heating engineers", ["gas engineer", "boiler engineer", "HVAC technician", "heat pump installer"], "Heating Engineer · Gallagher Heating", "Warm homes, efficient boilers and honest advice on heat pumps.", "Boiler installation · Boiler servicing · Heat pumps · Gas safety certificates · Radiators · Smart controls", [["Boiler service", "Annual service and safety check.", "£95"], ["Landlord gas certificate", "CP12 for one appliance.", "£80"], ["New combi boiler", "Supply and fit, 10-year warranty.", "From £2,600"]], "Gas Safe registered · MCS heat pump installer"],
    ["landscaper", "Landscaper & Gardener", "landscapers", ["gardener", "landscape gardener", "garden design", "tree surgeon"], "Landscaper · Gallagher Gardens", "Gardens designed, built and looked after.", "Garden design · Patios · Fencing · Lawns · Planting · Maintenance · Decking", [["Garden design", "Plan and planting list.", "From £600"], ["Patio", "Porcelain or sandstone, fixed quote.", "From £3,800"], ["Maintenance", "Fortnightly visits.", "From £120 / month"]], "Royal Horticultural Society Level 3"],
    ["mechanic", "Mechanic", "mechanics", ["car mechanic", "auto technician", "garage", "MOT"], "Mechanic · Gallagher Motors", "Honest repairs, fair prices and no surprise bills.", "Servicing · MOT repairs · Diagnostics · Brakes & clutches · Hybrid & EV · Air conditioning", [["Full service", "Oil, filters and 60-point check.", "From £189"], ["Diagnostics", "Fault codes read and explained.", "£60"], ["MOT", "Including free retest.", "£54.85"]], "IMI accredited technician"],
    ["cleaner", "Cleaner", "cleaners", ["cleaning business", "house cleaner", "office cleaning", "end of tenancy cleaning"], "Cleaning · Gallagher Clean", "Spotless homes and offices, by people you can trust.", "Regular home cleaning · Deep cleans · End of tenancy · Office cleaning · Carpet cleaning · Eco products", [["Regular clean", "Weekly or fortnightly.", "£22 / hour"], ["Deep clean", "Three-bed house.", "From £280"], ["End of tenancy", "Deposit-back guarantee.", "From £320"]], "Fully vetted & insured team"],
    ["locksmith", "Locksmith", "locksmiths", ["emergency locksmith", "lock change", "security"], "Locksmith · Gallagher Locks", "Locked out? With you in 30 minutes, at a fixed price.", "Emergency entry · Lock changes · uPVC door repairs · Security upgrades · Safes · Key cutting", [["Emergency entry", "Non-destructive where possible.", "From £85"], ["Lock change", "British Standard lock fitted.", "From £110"], ["Security survey", "Home security advice.", "Free"]], "Master Locksmiths Association member"],
    ["tiler", "Tiler", "tilers", ["wall tiler", "floor tiler", "bathroom tiler"], "Tiler · Gallagher Tiling", "Straight lines and clean grout, every time.", "Bathrooms · Kitchens · Floor tiling · Large-format tiles · Wet rooms · Natural stone", [["Bathroom tiling", "Walls and floor, standard bathroom.", "From £1,600"], ["Kitchen splashback", "Supply and fit.", "From £380"], ["Floor tiling", "Per square metre.", "From £45"]], "City & Guilds Wall & Floor Tiling"],
  ] as const).map(([id, label, plural, aliases, title, tagline, skills, services, accreditation]) => role(id, label, plural, "trades", [...aliases], {
    title, tagline,
    bio: [`I’m a fully qualified ${label.toLowerCase()} with twenty years’ experience across Bristol and North Somerset. We’re a small team and I see every job myself, from quote to finish.`, "Dust sheets down, clear written quotes before we start, and we turn up when we say we will."],
    skills, services: services.map((service) => [...service] as [string, string, string]),
    stats: [["20", "years’ experience"], ["1,400+", "jobs done"], ["4.9★", "from 312 reviews"]],
    quote: ["Turned up at 8 every day, left it cleaner than they found it, and finished a day early.", "Kate H.", "Customer, Bishopston"],
    experience: [[`Owner & lead ${label.toLowerCase()}`, title.split(" · ")[1] ?? "Self-employed", "2012", "Present"], [label, "SW Building Services", "2005", "2012"]],
    education: [[accreditation, "Industry accreditation", ""], [TRADE_INS, "Fully insured", ""]],
  }, ["site-board", "practice"])),

  // ——— Beauty (London, £) ———
  role("hairdresser", "Hairdresser", "hairdressers", "beauty", ["hair stylist", "colourist", "hair salon", "hair colorist"], {
    title: "Hair Colourist & Stylist", tagline: "Colour that grows out beautifully.",
    bio: ["I’m a colourist with fourteen years behind the chair, specialising in lived-in blondes, copper and colour correction.", "Every new client starts with a consultation and strand test."],
    skills: "Balayage · Lived-in blonde · Copper & red · Colour correction · Grey blending · Precision cuts",
    services: [["Consultation & strand test", "Redeemable against your first colour.", "£25"], ["Balayage", "Hand-painted, with toner and blow-dry.", "From £195"], ["Cut & finish", "Wash, precision cut and style.", "£75"]],
    stats: [["14", "years colouring"], ["90%", "of clients rebook"], ["LFW", "backstage team"]],
    quote: ["Three salons said my hair couldn’t go copper. Chloé did it in two sessions.", "Jess R.", "Client"],
    experience: [["Owner & Senior Colourist", "Chloé Martin Studio", "2020", "Present"], ["Senior Colourist", "Salon Rive Gauche, Paris", "2012", "2020"]],
    education: [["Master Colourist", "L’Oréal Professionnel Academy", "2015"]],
    keepWork: true,
  }, ["lookbook", "practice"]),
  role("barber", "Barber", "barbers", "beauty", ["barbershop", "men’s hairdresser", "fade specialist"], {
    title: "Barber & Shop Owner", tagline: "Sharp fades, proper hot towel shaves and good conversation.",
    bio: ["I run a four-chair barbershop in Shoreditch. Skin fades, scissor cuts, beard work and traditional shaves.", "Walk-ins welcome before noon; book online for the afternoon."],
    skills: "Skin fades · Scissor cuts · Beard sculpting · Hot towel shaves · Afro & textured hair · Kids’ cuts",
    services: [["Haircut", "Including wash and style.", "£32"], ["Skin fade", "With line-up.", "£35"], ["Hot towel shave", "Traditional straight razor.", "£30"]],
    stats: [["4", "chairs"], ["12", "years cutting"], ["4.9★", "from 1,100 reviews"]],
    quote: ["Best fade in east London, and the chat is free.", "Regular", "Review"],
    experience: [["Owner", "Martin & Co. Barbers", "2019", "Present"], ["Senior Barber", "Brick Lane Barbers", "2013", "2019"]],
    education: [["NVQ Level 3 Barbering", "Hackney Community College", "2013"]],
    name: "Chloé Martin", keepWork: true,
  }, ["lookbook", "site-board"]),
  role("makeup-artist", "Makeup Artist", "makeup artists", "beauty", ["MUA", "bridal makeup", "makeup", "special effects makeup"], {
    title: "Bridal & Editorial Makeup Artist", tagline: "Makeup that looks like you on your best day.",
    bio: ["I do bridal, editorial and red-carpet makeup in London and across Europe.", "Every bride gets a trial, a timeline and a touch-up kit for the evening."],
    skills: "Bridal makeup · Editorial · Skin prep · Mature skin · All skin tones · Airbrush · Lashes",
    services: [["Bridal trial", "Two hours in the studio.", "£150"], ["Wedding day", "Bride, on location.", "From £420"], ["Event makeup", "Ninety minutes.", "£140"]],
    stats: [["600+", "brides"], ["Vogue · Elle", "editorial credits"], ["11", "years"]],
    quote: ["I looked like me, only rested and glowing. It lasted until 2am.", "Bride", "2025"],
    experience: [["Makeup Artist", "Self-employed", "2016", "Present"], ["Makeup Artist", "Department store beauty counter", "2013", "2016"]],
    education: [["Diploma in Makeup Artistry", "London College of Fashion", "2014"]],
    keepWork: true,
  }, ["lookbook", "monograph"]),
  role("nail-technician", "Nail Technician", "nail technicians", "beauty", ["nail artist", "nail tech", "manicurist", "gel nails"], {
    title: "Nail Technician & Artist", tagline: "Healthy nails, clean work and art that lasts three weeks.",
    bio: ["I do structured gel manicures, extensions and hand-painted nail art from a private studio in Shoreditch.", "Nail health comes first: no drills on natural nails, ever."],
    skills: "Structured gel · BIAB · Extensions · Hand-painted art · Russian manicure · Pedicures",
    services: [["BIAB manicure", "With cuticle work.", "£48"], ["Gel extensions", "Full set.", "From £65"], ["Nail art", "Per nail.", "From £3"]],
    stats: [["3 weeks", "average wear"], ["8", "years"], ["4.9★", "from 540 reviews"]],
    quote: ["My natural nails have never been stronger, and the art is unreal.", "Client", "Review"],
    experience: [["Owner", "Martin Nails Studio", "2020", "Present"], ["Nail Technician", "Shoreditch nail bar", "2017", "2020"]],
    education: [["VTCT Level 3 Nail Technology", "London College of Beauty Therapy", "2017"]],
    name: "Chloé Martin",
  }, ["lookbook", "practice"]),
  role("beauty-therapist", "Beauty Therapist", "beauty therapists", "beauty", ["esthetician", "aesthetician", "facialist", "skin therapist", "aesthetics practitioner"], {
    title: "Skin Therapist & Facialist", tagline: "Results-led facials and honest skincare advice.",
    bio: ["I treat acne, pigmentation and sensitive skin with advanced facials, peels and microneedling.", "I’ll always suggest the simplest routine that works."],
    skills: "Advanced facials · Chemical peels · Microneedling · Acne · Pigmentation · Skin consultations",
    services: [["Skin consultation", "Analysis and a home routine.", "£40"], ["Signature facial", "Seventy-five minutes.", "£110"], ["Course of 3 peels", "For pigmentation.", "£300"]],
    stats: [["10", "years in skin"], ["2,000+", "facials"], ["Level 4", "skin specialist"]],
    quote: ["The only facialist who ever cleared my skin.", "Client", "Acne programme"],
    experience: [["Skin Therapist", "Chloé Martin Studio", "2020", "Present"], ["Beauty Therapist", "Hotel spa, Mayfair", "2015", "2020"]],
    education: [["Level 4 Laser & Skin Therapy", "VTCT", "2019"]],
    name: "Chloé Martin",
  }, ["lookbook", "sanctuary"]),
  role("lash-brow-technician", "Lash & Brow Technician", "lash and brow technicians", "beauty", ["lash tech", "brow artist", "microblading", "lash extensions"], {
    title: "Lash & Brow Artist", tagline: "Natural lashes and brows that frame your face.",
    bio: ["I specialise in lash lifts, classic and hybrid extensions, brow lamination and microblading.", "I map every set to your face shape, so it looks like you."],
    skills: "Lash extensions · Lash lift · Brow lamination · Microblading · Brow mapping · Tinting",
    services: [["Lash lift & tint", "Lasts six to eight weeks.", "£60"], ["Classic lash set", "Infills every three weeks.", "£85"], ["Brow lamination", "With shape and tint.", "£55"]],
    stats: [["7", "years"], ["4.9★", "from 620 reviews"], ["Award", "finalist 2024"]],
    quote: ["I wake up looking awake. Best money I spend all month.", "Client", "Review"],
    experience: [["Lash & Brow Artist", "Chloé Martin Studio", "2020", "Present"], ["Lash Technician", "Lash bar, Soho", "2018", "2020"]],
    education: [["Accredited Lash & Brow Courses", "Industry training academy", "2018"]],
    name: "Chloé Martin",
  }, ["lookbook", "practice"]),
  role("tattoo-artist", "Tattoo Artist", "tattoo artists", "beauty", ["tattooist", "tattoo studio", "fine line tattoo"], {
    title: "Tattoo Artist, Fine Line & Botanical", tagline: "Delicate tattoos designed for you and made to age well.",
    bio: ["I tattoo fine-line botanical and illustrative pieces from a private studio in east London.", "Every design is drawn for the client, never reused."],
    skills: "Fine line · Botanical · Illustrative · Single needle · Cover-up consultation · Custom design",
    services: [["Consultation", "Thirty minutes, redeemable.", "£30"], ["Small tattoo", "Up to 5cm.", "From £120"], ["Day session", "Larger pieces.", "£700"]],
    stats: [["9", "years tattooing"], ["Books", "open quarterly"], ["Licensed", "studio"]],
    quote: ["She drew exactly what I couldn’t describe.", "Client", "Botanical sleeve"],
    experience: [["Resident Artist", "Studio Nine, Hackney", "2018", "Present"], ["Apprentice", "East End Tattoo", "2016", "2018"]],
    education: [["BA Illustration", "Camberwell College of Arts", "2015"]],
    name: "Chloé Martin", keepWork: true,
  }, ["lookbook", "sketchbook"]),

  // ——— Food (London, £) ———
  role("private-chef", "Private Chef", "private chefs", "food", ["personal chef", "chef at home", "supper club"], {
    title: "Private Chef", tagline: "A restaurant-quality dinner, cooked in your kitchen.",
    bio: ["I cook private dinners for eight to forty people, in homes, villas and holiday lets.", "I shop, cook, serve and clear, and I plan every menu around your guests’ tastes and allergies."],
    skills: "Private dining · Menu planning · Allergen planning · Live-fire cooking · Wine pairing · Chalet & villa cooking",
    services: [["Private dinner", "Seven courses, served and cleared.", "From £95 per guest"], ["Weekend in residence", "All meals for a group.", "From £1,400"], ["Cooking class", "Hands-on, for up to eight.", "£480"]],
    stats: [["400+", "dinners cooked"], ["14", "years cooking"], ["5.0★", "from 180 hosts"]],
    quote: ["Our guests are still talking about it. He left the kitchen spotless.", "Host", "40th birthday"],
    experience: [["Private Chef", "Self-employed", "2023", "Present"], ["Head Chef", "Maíz, Soho", "2019", "2023"]],
    education: [["Professional Chef Diploma", "Westminster Kingsway College", "2012"]],
    keepWork: true,
  }, ["carte", "mise", "practice"]),
  role("head-chef", "Head Chef", "head chefs", "food", ["chef", "executive chef", "sous chef", "chef de cuisine", "line cook"], {
    title: "Head Chef", tagline: "Seasonal cooking, a calm kitchen and food costs under control.",
    bio: ["I run a 70-cover kitchen and a team of twelve. The menu changes every week with what our farms send us.", "I care as much about a happy, well-trained brigade as about what goes on the plate."],
    skills: "Menu development · Kitchen management · Food costing · Training · Seasonal sourcing · Food safety · Butchery",
    services: [["Menu consultancy", "Recipes, costings and training.", "From £2,200"], ["Kitchen review", "Systems, waste and margins.", "£1,500"], ["Guest chef", "Pop-up dinners.", "Quote"]],
    stats: [["70", "covers"], ["28%", "food cost"], ["Bib Gourmand", "3 years"]],
    quote: ["The calmest, best-run kitchen I’ve worked in.", "Sous Chef", "His brigade"],
    experience: [["Head Chef", "Maíz, Soho", "2019", "Present"], ["Sous Chef", "Brindisa Kitchen", "2015", "2019"]],
    education: [["Professional Chef Diploma", "Westminster Kingsway College", "2012"]],
    keepWork: true,
  }, ["carte", "mise", "practice"]),
  role("baker", "Baker", "bakers", "food", ["bakery owner", "sourdough baker", "cake maker", "artisan baker"], {
    title: "Baker & Bakery Owner", tagline: "Slow sourdough and honest pastries, baked before sunrise.",
    bio: ["I run a small neighbourhood bakery in Hackney: long-fermented sourdough, laminated pastries and seasonal cakes.", "We supply six local cafés and sell out most Saturdays by eleven."],
    skills: "Sourdough · Viennoiserie · Celebration cakes · Wholesale · Heritage grains · Bakery management",
    services: [["Celebration cake", "Order a week ahead.", "From £45"], ["Wholesale bread", "Daily delivery to cafés.", "Price list"], ["Sourdough class", "Three hours, take your starter home.", "£85"]],
    stats: [["1,200", "loaves a week"], ["6", "cafés supplied"], ["48h", "fermentation"]],
    quote: ["The best sourdough in London, and I’ve tried most of them.", "Food writer", "Weekend magazine"],
    experience: [["Owner & Head Baker", "Comal Bakery, Hackney", "2021", "Present"], ["Baker", "E5 Bakehouse", "2017", "2021"]],
    education: [["Level 3 Professional Bakery", "National Bakery School", "2017"]],
  }, ["carte", "mise", "site-board"]),
  role("pastry-chef", "Pastry Chef", "pastry chefs", "food", ["patissier", "pâtissier", "dessert chef", "chocolatier"], {
    title: "Pastry Chef", tagline: "Desserts with as much care as the main course.",
    bio: ["I lead pastry at a modern restaurant: plated desserts, petits fours, ice creams and bread for service.", "I also make wedding cakes to order."],
    skills: "Plated desserts · Viennoiserie · Chocolate work · Ice cream · Sugar work · Wedding cakes",
    services: [["Wedding cake", "Tasting and design.", "From £450"], ["Dessert menu", "Development for restaurants.", "From £1,500"], ["Masterclass", "Pastry for home bakers.", "£120"]],
    stats: [["11", "years in pastry"], ["80", "desserts a night"], ["Finalist", "National Chocolate Awards"]],
    quote: ["The dessert was the course our whole table remembered.", "Guest", "Review"],
    experience: [["Pastry Chef", "Maíz, Soho", "2020", "Present"], ["Pastry Chef de Partie", "Hotel kitchen, Mayfair", "2015", "2020"]],
    education: [["Diplôme de Pâtisserie", "Le Cordon Bleu London", "2014"]],
    keepWork: true,
  }, ["carte", "mise", "lookbook"]),
  role("caterer", "Caterer", "caterers", "food", ["catering company", "event catering", "wedding catering", "corporate catering"], {
    title: "Event Caterer", tagline: "Generous food for weddings, parties and offices, served on time.",
    bio: ["I cater weddings, parties and corporate events for 40 to 400 guests across London and the south east.", "Every menu is tasted with you beforehand, and every allergy is labelled."],
    skills: "Weddings · Corporate events · Canapés · Sharing feasts · BBQ & live fire · Dietary requirements",
    services: [["Canapé reception", "Six canapés per guest.", "From £18 per guest"], ["Wedding feast", "Sharing platters, three courses.", "From £58 per guest"], ["Office lunch", "Delivered and set up.", "From £14 per head"]],
    stats: [["300+", "events"], ["400", "largest wedding"], ["5★", "food hygiene rating"]],
    quote: ["Generous, delicious and beautifully served. Our guests went back for thirds.", "Bride & groom", "Wedding, 2025"],
    experience: [["Founder", "Comal Catering", "2021", "Present"], ["Head Chef", "Maíz, Soho", "2019", "2021"]],
    education: [["Level 3 Food Safety", "Royal Society for Public Health", "2020"]],
    keepWork: true,
  }, ["carte", "mise", "practice"]),
  role("bartender", "Bartender", "bartenders", "food", ["mixologist", "bar manager", "cocktail bartender", "sommelier", "barista"], {
    title: "Head Bartender", tagline: "Good drinks, good company and a bar that runs itself.",
    bio: ["I run the bar at a Soho restaurant: cocktail menu, training, stock and the late shift.", "I also do private bartending and cocktail classes."],
    skills: "Cocktail development · Bar management · Agave spirits · Training · Stock control · Private events",
    services: [["Private bartender", "Five hours, with menu.", "From £350"], ["Cocktail class", "Ninety minutes, up to twelve.", "£480"], ["Menu consultancy", "For new bars.", "Quote"]],
    stats: [["9", "years behind the bar"], ["Top 50", "bars list, 2024"], ["40+", "bartenders trained"]],
    quote: ["The best margarita in London, and he remembers everyone’s name.", "Regular", "Review"],
    experience: [["Head Bartender", "Maíz, Soho", "2020", "Present"], ["Bartender", "Cocktail bar, Shoreditch", "2016", "2020"]],
    education: [["WSET Level 2 Spirits", "Wine & Spirit Education Trust", "2018"]],
  }, ["carte", "mise", "liner-notes"]),

  // ——— Events (Cotswolds, £) ———
  role("wedding-planner", "Wedding Planner", "wedding planners", "events", ["wedding coordinator", "destination wedding planner"], {
    title: "Wedding Planner", tagline: "Calm, beautiful days, planned down to the last place card.",
    bio: ["I plan weddings in the Cotswolds and across Europe: country houses, barns, gardens and the occasional Italian hillside.", "My couples get one planner from first coffee to last dance."],
    skills: "Full wedding planning · Destination weddings · Venue sourcing · Design & styling · Supplier management · Budgeting",
    services: [["Full planning", "Venue search to last dance.", "From £6,500"], ["Partial planning", "Suppliers, design and timeline.", "From £3,800"], ["On-the-day coordination", "From eight weeks out.", "£1,450"]],
    stats: [["160", "weddings planned"], ["11", "years"], ["6", "countries"]],
    quote: ["We didn’t make a single decision on the day. Olivia had thought of everything.", "Ana & Kofi", "Married June 2025"],
    experience: [["Founder & Lead Planner", "Olivia Bennett Events", "2014", "Present"], ["Events Manager", "Barnsley House Hotel", "2010", "2014"]],
    education: [["UK Alliance of Wedding Planners", "Member", "2016"]],
    keepWork: true,
  }, ["monograph", "carte", "horizon"]),
  role("event-planner", "Event Planner", "event planners", "events", ["event manager", "conference organiser", "corporate events", "party planner"], {
    title: "Corporate Event Planner", tagline: "Conferences and parties that run to the minute.",
    bio: ["I plan conferences, offsites and company parties for 50 to 2,000 people.", "Clients get one budget, one timeline and one number to call."],
    skills: "Conferences · Offsites · Venue sourcing · Production · Budgets · Delegate management · Run-of-show",
    services: [["Conference management", "Venue, production and delegates.", "Quote"], ["Company offsite", "Two days, fully planned.", "From £4,500"], ["Christmas party", "Venue, food and entertainment.", "From £2,500"]],
    stats: [["300+", "events"], ["2,000", "largest conference"], ["0", "missed start times"]],
    quote: ["The smoothest conference we’ve ever run.", "Head of Marketing", "Client"],
    experience: [["Event Planner", "Olivia Bennett Events", "2014", "Present"], ["Events Manager", "Barnsley House Hotel", "2010", "2014"]],
    education: [["BA Events Management", "Oxford Brookes University", "2010"]],
    keepWork: true,
  }, ["keynote", "carte"]),
  role("florist", "Florist", "florists", "events", ["wedding florist", "flower shop", "floral designer"], {
    title: "Wedding & Event Florist", tagline: "Seasonal, garden-style flowers grown and arranged with care.",
    bio: ["I design flowers for weddings and events using British-grown, seasonal stems, many from my own cutting garden.", "No floral foam, ever."],
    skills: "Wedding flowers · Installations · Seasonal British flowers · Foam-free design · Workshops",
    services: [["Bridal bouquet", "Seasonal, hand-tied.", "From £150"], ["Wedding flowers", "Full design, consultation first.", "From £1,800"], ["Wreath workshop", "December evenings.", "£75"]],
    stats: [["200+", "weddings"], ["80%", "British-grown stems"], ["Foam-free", "always"]],
    quote: ["The flowers were the first thing every guest mentioned.", "Bride", "Wedding, 2024"],
    experience: [["Founder", "Bennett Flowers", "2016", "Present"], ["Florist", "Cotswold florist", "2012", "2016"]],
    education: [["Level 3 Floristry", "Capel Manor College", "2012"]],
    keepWork: true,
  }, ["monograph", "lookbook"]),

  // ——— Engineering (Glasgow, £) ———
  ...([
    ["civil-engineer", "Civil Engineer", "civil engineers", ["infrastructure engineer", "highways engineer", "drainage engineer"], "Chartered Civil Engineer", "Roads, drainage and flood defences that serve communities for generations.", "Highways · Drainage · Flood defence · Earthworks · Site supervision · Civil 3D", "MEng Civil Engineering", "CEng MICE"],
    ["mechanical-engineer", "Mechanical Engineer", "mechanical engineers", ["design engineer", "manufacturing engineer", "product engineer"], "Senior Mechanical Design Engineer", "Products designed to be made, tested and trusted.", "Mechanical design · CAD (SolidWorks) · FEA · Design for manufacture · Prototyping · Tolerancing", "MEng Mechanical Engineering", "CEng MIMechE"],
    ["electrical-engineer", "Electrical Engineer", "electrical engineers", ["power engineer", "controls engineer", "building services engineer"], "Chartered Electrical Engineer", "Power systems that are safe, efficient and ready for net zero.", "Power distribution · HV/LV design · Renewables · Building services · Protection · AutoCAD Electrical", "MEng Electrical & Electronic Engineering", "CEng MIET"],
    ["chemical-engineer", "Chemical Engineer", "chemical engineers", ["process engineer", "process safety engineer"], "Senior Process Engineer", "Safer, cleaner, more efficient processes.", "Process design · Process safety · HAZOP · Plant optimisation · Aspen HYSYS · Decarbonisation", "MEng Chemical Engineering", "CEng MIChemE"],
    ["aerospace-engineer", "Aerospace Engineer", "aerospace engineers", ["aeronautical engineer", "stress engineer", "avionics engineer"], "Aerospace Stress Engineer", "Lighter structures that fly safely for decades.", "Stress analysis · Composites · Fatigue & damage tolerance · FEA · Certification · NASTRAN", "MEng Aeronautical Engineering", "CEng MRAeS"],
  ] as const).map(([id, label, plural, aliases, title, tagline, skills, degree, chartered]) => role(id, label, plural, "engineering", [...aliases], {
    title, tagline,
    bio: [`I’m a ${label.toLowerCase()} with fourteen years’ experience, leading designs from concept to commissioning.`, "I care about safety, cost and the material and energy we don’t use."],
    skills,
    services: [["Design review", "Independent check of drawings and calculations.", "Quote"], ["Expert witness", "Reports and evidence for disputes.", "Quote"], ["Mentoring", "For engineers working towards chartership.", "Free"]],
    stats: [["14", "years in engineering"], ["60+", "projects delivered"], [chartered.split(" ")[0]!, "chartered"]],
    quote: ["Elena found a solution that saved months and kept the budget.", "Project Director", "Client"],
    experience: [[title, "Arden Partnership", "2019", "Present"], [`Graduate ${label}`, "Atkins", "2011", "2019"]],
    education: [[degree, "University of Strathclyde", "2011"], [chartered, "Engineering Council", "2015"]],
  }, ["datasheet", "blueprint"])),

  // ——— Tech (Lisbon, €) ———
  ...([
    ["frontend-developer", "Frontend Developer", "frontend developers", ["front-end developer", "React developer", "UI engineer", "web developer"], "Senior Frontend Engineer", "Fast, accessible interfaces people enjoy using.", "TypeScript · React · Next.js · CSS · Accessibility · Design systems · Performance · Testing"],
    ["backend-developer", "Backend Developer", "backend developers", ["back-end developer", "API developer", "server engineer"], "Senior Backend Engineer", "APIs and services that stay up when traffic doesn’t stay down.", "Go · PostgreSQL · Kafka · APIs · Distributed systems · Observability · AWS"],
    ["full-stack-developer", "Full-Stack Developer", "full-stack developers", ["fullstack developer", "software developer", "web developer", "freelance developer"], "Full-Stack Developer", "From database to button, built properly and shipped quickly.", "TypeScript · React · Node.js · PostgreSQL · Next.js · AWS · Stripe · Testing"],
    ["mobile-developer", "Mobile Developer", "mobile developers", ["iOS developer", "Android developer", "app developer", "React Native developer"], "Senior Mobile Engineer", "Apps that feel native, load fast and rarely crash.", "Swift · Kotlin · React Native · SwiftUI · App Store releases · Offline-first · Performance"],
    ["devops-engineer", "DevOps Engineer", "DevOps engineers", ["SRE", "site reliability engineer", "platform engineer", "cloud engineer"], "Site Reliability Engineer", "Calm on-call, fast deploys and systems that heal themselves.", "Kubernetes · Terraform · AWS · CI/CD · Observability · Incident response · Linux · Go"],
    ["qa-engineer", "QA Engineer", "QA engineers", ["test engineer", "SDET", "quality assurance", "automation tester"], "Senior QA Automation Engineer", "Bugs caught before customers ever see them.", "Test automation · Playwright · Cypress · API testing · Performance testing · CI pipelines"],
    ["cybersecurity-analyst", "Cybersecurity Analyst", "cybersecurity professionals", ["security engineer", "penetration tester", "SOC analyst", "information security"], "Security Engineer", "Practical security that protects without slowing teams down.", "Application security · Penetration testing · Cloud security · Threat modelling · Incident response · ISO 27001"],
    ["it-support", "IT Support Specialist", "IT support specialists", ["helpdesk", "IT technician", "desktop support", "sysadmin"], "IT Support Engineer", "Friendly, fast IT help and systems that just work.", "Helpdesk · Microsoft 365 · Device management · Networking · Onboarding · Security basics"],
  ] as const).map(([id, label, plural, aliases, title, tagline, skills]) => role(id, label, plural, "developer", [...aliases], {
    title, tagline,
    bio: [`I’m a ${label.toLowerCase()} with ten years’ experience in payments and civic tech. I like boring, reliable solutions and writing things down.`, "I work best in small teams that ship often and talk to their users."],
    skills,
    services: [["Contract work", "Three to six months, remote or Lisbon.", "From €650 / day"], ["Code review", "A written review of your codebase.", "€2,400"], ["Mentoring", "For junior developers.", "€90 / hour"]],
    stats: [["10", "years building software"], ["40+", "releases a year"], ["99.95%", "uptime"]],
    quote: ["Ines leaves every codebase better than she found it.", "Engineering Manager", "Northwind Pay"],
    experience: [[title, "Northwind Pay", "2021", "Present"], [label, "Talo", "2016", "2021"]],
    education: [["MSc Informatics Engineering", "University of Porto", "2014"]],
  }, ["terminal", "blueprint", "contributions"])),

  // ——— Data (Singapore, S$) ———
  role("data-analyst", "Data Analyst", "data analysts", "data", ["business analyst", "BI analyst", "reporting analyst", "analytics"], {
    title: "Senior Data Analyst", tagline: "Numbers turned into decisions people can act on.",
    bio: ["I build dashboards and analyses for product and operations teams at a logistics company.", "I write the SQL, build the charts and explain what they mean in one paragraph."],
    skills: "SQL · Python · Tableau · Power BI · A/B testing · Data modelling · Excel · Storytelling",
    services: [["Dashboard build", "One dashboard your team will use.", "S$3,500"], ["Data audit", "What you track and what you’re missing.", "S$2,800"], ["Analytics training", "SQL for non-analysts.", "S$1,500"]],
    stats: [["120+", "dashboards"], ["S$4m", "savings identified"], ["8", "years in analytics"]],
    quote: ["Wei’s dashboard is the first thing our ops team opens every morning.", "Head of Operations", "Client"],
    experience: [["Senior Data Analyst", "Lumen Logistics", "2021", "Present"], ["Data Analyst", "GrabFood", "2017", "2021"]],
    education: [["BSc Statistics", "National University of Singapore", "2017"]],
  }, ["notebook", "signal"]),
  role("data-scientist", "Data Scientist", "data scientists", "data", ["machine learning", "statistician", "applied scientist"], {
    title: "Senior Data Scientist", tagline: "Models that move a metric, explained to the people who use them.",
    bio: ["I build forecasting and pricing models for a logistics company and work closely with product teams to put them into production.", "I care about honest evaluation more than fancy methods."],
    skills: "Python · Forecasting · Causal inference · Experimentation · scikit-learn · SQL · Airflow · Communication",
    services: [["Model review", "Is your model doing what you think?", "S$3,000"], ["Forecasting project", "Demand or capacity, end to end.", "Quote"], ["Workshop", "Experimentation for product teams.", "S$2,000"]],
    stats: [["−23%", "forecast error"], ["S$6m", "annual savings"], ["12", "models in production"]],
    quote: ["Wei’s forecasts are the reason we stopped over-hiring for peak season.", "VP Operations", "Lumen Logistics"],
    experience: [["Senior Data Scientist", "Lumen Logistics", "2021", "Present"], ["Data Scientist", "GrabFood", "2018", "2021"]],
    education: [["MSc Statistics", "National University of Singapore", "2018"]],
  }, ["notebook", "signal"]),
  role("ml-engineer", "Machine Learning Engineer", "ML engineers", "data", ["AI engineer", "MLOps engineer", "LLM engineer", "deep learning engineer"], {
    title: "Machine Learning Engineer", tagline: "AI features that work in production, not just in notebooks.",
    bio: ["I build and run ML systems: retrieval, ranking and language-model features serving millions of requests a day.", "I like measurable improvements, good evaluation sets and cheap inference."],
    skills: "PyTorch · LLMs · Retrieval & ranking · Evaluation · MLOps · Python · Kubernetes · Vector search",
    services: [["AI feature build", "From prototype to production.", "Quote"], ["Evaluation set-up", "How you’ll know the model got better.", "S$4,500"], ["Cost review", "Cutting inference costs.", "S$3,000"]],
    stats: [["30M", "requests a day"], ["−58%", "inference cost"], ["+14%", "search conversion"]],
    quote: ["Wei shipped the search improvement our users had wanted for two years.", "Head of Product", "Client"],
    experience: [["Machine Learning Engineer", "Lumen Logistics", "2022", "Present"], ["Data Scientist", "GrabFood", "2018", "2022"]],
    education: [["MSc Computer Science", "Nanyang Technological University", "2018"]],
  }, ["notebook", "terminal"]),

  // ——— Wellness (Amsterdam €, trainer in São Paulo) ———
  role("therapist", "Therapist & Counsellor", "therapists and counsellors", "wellness", ["counsellor", "psychotherapist", "counselor", "couples therapist", "mental health counsellor"], {
    title: "Psychotherapist & Counsellor", tagline: "A quiet hour for the loud parts of life.",
    bio: ["I’m a registered psychotherapist working with adults on anxiety, burnout, grief and big life changes.", "Sessions are in English, Arabic or Dutch, in person or online."],
    skills: "Anxiety · Burnout · Grief · Relationships · Life transitions · CBT · Mindfulness",
    services: [["Individual therapy", "Fifty minutes, weekly or fortnightly.", "€95"], ["Couples therapy", "Seventy-five minutes.", "€140"], ["Free introduction", "Fifteen minutes to see if we fit.", "Free"]],
    stats: [["10", "years in practice"], ["3", "languages"], ["Online", "or in person"]],
    quote: ["Maya helped me notice what my body had been saying for a year. I sleep now.", "J.", "Client"],
    experience: [["Psychotherapist", "Private practice", "2019", "Present"], ["Psychologist", "GGZ inGeest", "2014", "2019"]],
    education: [["MSc Clinical Psychology", "Vrije Universiteit Amsterdam", "2014"]],
  }, ["sanctuary", "practice"]),
  role("life-coach", "Life & Career Coach", "coaches", "wellness", ["life coach", "career coach", "executive coach", "business coach", "leadership coach"], {
    title: "Career & Executive Coach", tagline: "Clarity on what’s next, and the courage to do it.",
    bio: ["I coach people at career crossroads: new managers, career changers and leaders on the edge of burnout.", "Six sessions, one clear plan, and someone to keep you honest."],
    skills: "Career change · Leadership coaching · Confidence · Burnout recovery · Decision-making · ICF-accredited",
    services: [["Discovery call", "Thirty minutes.", "Free"], ["Six-session programme", "Over three months.", "€780"], ["Executive coaching", "For senior leaders, per month.", "€600"]],
    stats: [["300+", "clients coached"], ["ICF PCC", "credential"], ["86%", "made the change they came for"]],
    quote: ["I left a job I hated and started the business I’d talked about for years.", "Client", "Career change"],
    experience: [["Coach", "Private practice", "2018", "Present"], ["HR Manager", "Booking.com", "2012", "2018"]],
    education: [["Professional Certified Coach (PCC)", "International Coaching Federation", "2020"]],
  }, ["sanctuary", "practice", "keynote"]),
  role("yoga-teacher", "Yoga Teacher", "yoga teachers", "wellness", ["yoga instructor", "pilates instructor", "meditation teacher", "breathwork"], {
    title: "Yoga & Breathwork Teacher", tagline: "Slow, strong practice for busy bodies and minds.",
    bio: ["I teach vinyasa and yin yoga, breathwork and meditation in Amsterdam and online.", "Classes are small and beginners are always welcome."],
    skills: "Vinyasa · Yin · Breathwork · Meditation · Pregnancy yoga · Corporate classes · Retreats",
    services: [["Drop-in class", "Seventy-five minutes.", "€20"], ["Private session", "At home or online.", "€80"], ["Weekend retreat", "Two nights, all meals.", "From €420"]],
    stats: [["500h", "certified teacher"], ["9", "years teaching"], ["12", "retreats led"]],
    quote: ["The only class that switches my head off completely.", "Student", "Weekly class"],
    experience: [["Yoga Teacher", "Self-employed", "2016", "Present"], ["Studio Manager", "De Nieuwe Yogaschool", "2013", "2016"]],
    education: [["500-hour Yoga Teacher Training", "Yoga Alliance", "2017"]],
  }, ["sanctuary", "training-log"]),
  role("nutritionist", "Nutritionist", "nutritionists", "wellness", ["nutrition coach", "health coach", "holistic nutritionist"], {
    title: "Registered Nutritionist", tagline: "Eating well without rules you can’t keep.",
    bio: ["I help busy adults sort out energy, digestion and weight with simple, sustainable changes.", "No detoxes, no supplements you don’t need."],
    skills: "Gut health · Energy · Weight management · Plant-based eating · Sports nutrition · Meal planning",
    services: [["Initial consultation", "An hour, with a written plan.", "€90"], ["Follow-up", "Thirty minutes.", "€50"], ["Three-month programme", "Five sessions and messaging support.", "€390"]],
    stats: [["900+", "clients"], ["8", "years"], ["Evidence-based", "always"]],
    quote: ["More energy, fewer cravings and no more 4pm crash.", "Client", "Three-month programme"],
    experience: [["Nutritionist", "Private practice", "2018", "Present"], ["Nutrition Advisor", "Health food chain", "2015", "2018"]],
    education: [["MSc Nutrition & Health", "Wageningen University", "2015"]],
  }, ["sanctuary", "practice"]),
  role("massage-therapist", "Massage Therapist", "massage therapists", "wellness", ["sports massage", "massage", "bodywork", "deep tissue"], {
    title: "Sports & Remedial Massage Therapist", tagline: "Hands-on treatment that gets you moving freely again.",
    bio: ["I treat runners, cyclists and desk workers for tight muscles, aches and recovery.", "Every treatment ends with stretches you can do at home."],
    skills: "Sports massage · Deep tissue · Remedial massage · Myofascial release · Pregnancy massage · Stretching",
    services: [["Sports massage", "Sixty minutes.", "€70"], ["Deep tissue", "Ninety minutes.", "€95"], ["Event massage", "Pre- and post-race.", "Quote"]],
    stats: [["6,000+", "treatments"], ["10", "years"], ["4.9★", "from 300 reviews"]],
    quote: ["The best massage I’ve had, and my back pain hasn’t come back.", "Client", "Review"],
    experience: [["Massage Therapist", "Private practice", "2016", "Present"], ["Therapist", "Sports clinic", "2014", "2016"]],
    education: [["Level 5 Sports Massage Therapy", "Sports massage academy", "2014"]],
  }, ["sanctuary", "training-log"]),
  role("personal-trainer", "Personal Trainer", "personal trainers", "wellness", ["PT", "fitness coach", "strength coach", "online coach", "gym instructor"], {
    base: "trainer", title: "Strength Coach & Personal Trainer", tagline: "Get strong, stay unbroken.",
    bio: ["I coach busy adults to lift well, run further and stop getting hurt. Fourteen years coaching, from beginners to national-level rowers.", "Programmes are written for your week, your gym and your knees."],
    skills: "Strength · Mobility · Running · Injury return · Nutrition basics",
    services: [["Online coaching", "Weekly programme and video form checks.", "R$480 / month"], ["1:1 training", "In person, 60 minutes.", "R$220"], ["12-week strength block", "Fixed plan, three check-ins.", "R$990"]],
    stats: [["14", "years coaching"], ["600+", "clients"], ["212kg", "deadlift PR"]],
    quote: ["First year since 2015 without a running injury.", "Ana P.", "Client"],
    experience: [["Head Coach", "Costa Strength", "2018", "Present"], ["S&C Coach", "Brazilian rowing squad", "2019", "2021"]],
    education: [["CSCS", "NSCA", "2014"]],
  }, ["training-log", "sanctuary"]),

  // ——— Creative ———
  role("graphic-designer", "Graphic Designer", "graphic designers", "design", ["designer", "logo designer", "brand designer", "visual designer"], {
    title: "Graphic & Brand Designer", tagline: "Identities, packaging and print with a clear idea behind them.",
    bio: ["I design logos, brand identities, packaging and printed matter for independent businesses and cultural organisations.", "I work closely with clients from the first sketch to the printer."],
    skills: "Brand identity · Logo design · Packaging · Print · Typography · Illustration · Adobe CC · Figma",
    services: [["Logo & identity", "Mark, colours, type and guidelines.", "From $6k"], ["Packaging", "Per product range.", "From $4k"], ["Print design", "Brochures, posters, books.", "Quote"]],
    stats: [["120+", "brands"], ["9", "years"], ["TDC", "certificate of excellence"]],
    quote: ["Theo gave us a brand our customers describe as ‘like the shop smells’.", "Owner", "Fernhouse"],
    experience: [["Independent designer", "Studio Laurent", "2021", "Present"], ["Designer", "Pentagram", "2015", "2017"]],
    education: [["BFA Design", "Concordia University", "2015"]],
    keepWork: true,
  }, ["swiss", "specimen", "riso"]),
  role("ux-designer", "UX Designer", "UX designers", "design", ["UI designer", "product designer", "UX researcher", "interaction designer"], {
    title: "Senior Product Designer", tagline: "Interfaces that feel obvious, because the research came first.",
    bio: ["I design web and mobile products, from research and flows to polished UI and design systems.", "I stay through launch so the details survive engineering."],
    skills: "User research · Interaction design · Prototyping · Design systems · Accessibility · Figma · Usability testing",
    services: [["Design sprint", "Four weeks to a tested prototype.", "From $18k"], ["UX audit", "Where users struggle, and how to fix it.", "$4.5k"], ["Design system", "Components and documentation.", "Quote"]],
    stats: [["40+", "products shipped"], ["4.8★", "app rating"], ["9", "years"]],
    quote: ["The rare designer who makes engineering faster, not slower.", "CTO", "Stillwater"],
    experience: [["Senior Product Designer", "Studio Laurent", "2021", "Present"], ["Product Designer", "Shopify", "2017", "2021"]],
    education: [["BFA Design", "Concordia University", "2015"]],
    keepWork: true,
  }, ["swiss", "specimen"]),
  role("interior-designer", "Interior Designer", "interior designers", "architecture", ["interior architect", "interior decorator", "home stylist"], {
    title: "Interior Designer", tagline: "Calm, practical rooms with materials that age well.",
    bio: ["I design homes and small hospitality spaces: layouts, joinery, lighting and the materials that make a room feel right.", "I manage the build so you don’t have to."],
    skills: "Space planning · Joinery design · Lighting · Materials · Furniture sourcing · Project management",
    services: [["Design consultation", "Two hours at your home.", "NOK 4,500"], ["Full room design", "Drawings, schedules and sourcing.", "From NOK 45,000"], ["Project management", "Through the build.", "Quote"]],
    stats: [["70+", "projects"], ["12", "years"], ["Featured", "in Elle Decoration"]],
    quote: ["Jonas made our small flat feel twice the size.", "Client", "Apartment, Oslo"],
    experience: [["Interior Designer", "Berg Studio", "2018", "Present"], ["Designer", "Snøhetta Interiors", "2012", "2018"]],
    education: [["MA Interior Architecture", "Oslo School of Architecture and Design", "2012"]],
    keepWork: true,
  }, ["material", "plan-section"]),
  role("wedding-photographer", "Wedding Photographer", "wedding photographers", "photo", ["photographer", "portrait photographer", "family photographer", "event photographer"], {
    title: "Wedding & Portrait Photographer", tagline: "Honest, beautiful pictures of the day as it really felt.",
    bio: ["I photograph weddings and families in a documentary style, with very little posing and a lot of patience.", "You’ll get your full gallery within four weeks."],
    skills: "Documentary weddings · Portraits · Families · Elopements · Film & digital · Editing",
    services: [["Full-day wedding", "Prep to first dance, online gallery.", "From $2,800"], ["Elopement", "Up to four hours.", "From $1,400"], ["Family session", "Ninety minutes outdoors.", "$420"]],
    stats: [["220", "weddings"], ["4 weeks", "gallery delivery"], ["5.0★", "from 160 couples"]],
    quote: ["Every photo made us cry, in the best way.", "Couple", "Wedding, 2024"],
    experience: [["Photographer", "Self-employed", "2014", "Present"], ["Assistant", "Studio Valparaíso", "2011", "2014"]],
    education: [["BA Photography", "Universidad de Valparaíso", "2011"]],
    keepWork: true,
  }, ["monograph", "horizon", "darkroom"]),
  role("videographer", "Videographer", "videographers", "film", ["video producer", "filmmaker", "video editor", "wedding videographer"], {
    title: "Videographer & Editor", tagline: "Short films that people watch to the end.",
    bio: ["I shoot and edit brand films, documentaries and events, usually as a crew of one or two.", "I plan every shoot around the story, not the shot list."],
    skills: "Cinematography · Editing · Colour grading · Sound · Drone · Brand films · Documentary",
    services: [["Brand film", "Two to three minutes, one shoot day.", "From £3,500"], ["Event coverage", "Highlights film.", "From £1,200"], ["Editing", "Your footage, cut and graded.", "£350 / day"]],
    stats: [["150+", "films"], ["12M", "views"], ["10", "years"]],
    quote: ["The film did more for our brand than a year of ads.", "Marketing Director", "Client"],
    experience: [["Videographer", "Self-employed", "2016", "Present"], ["Camera Operator", "Broadcast production company", "2012", "2016"]],
    education: [["BA Film Production", "National Film and Television School", "2012"]],
    keepWork: true,
  }, ["credits", "storyboard"]),
];
