import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Clock3, Tag } from "lucide-react";
import { articles, getArticle } from "@/lib/content/articles";
import { notFound } from "next/navigation";
type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const article = getArticle(slug); if (!article) return {}; return { title: article.title, description: article.excerpt, alternates: { canonical: `/blog/${article.slug}` }, openGraph: { title: article.title, description: article.excerpt, type: "article" } }; }
export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = getArticle(slug); if (!article) notFound(); const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.excerpt, datePublished: "2026-09-20", author: { "@type": "Organization", name: "Formora" } }; return <article className="min-h-screen bg-slate-50 px-6 py-16 dark:bg-slate-950 sm:py-24"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="mx-auto max-w-3xl"><Link href="/blog" className="inline-flex items-center gap-2 text-sm font-bold text-violet-700 hover:underline dark:text-violet-300"><ArrowLeft size={16} /> Back to journal</Link><p className="mt-12 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-violet-700 dark:text-violet-300"><Tag size={14} /> {article.category}</p><h1 className="mt-4 text-4xl font-black tracking-tight text-slate-950 dark:text-white sm:text-6xl">{article.title}</h1><div className="mt-6 flex items-center gap-4 text-sm text-slate-500"><span>{article.date}</span><span className="flex items-center gap-1"><Clock3 size={14} /> {article.readTime}</span></div><div className="mt-12 space-y-6 text-lg leading-8 text-slate-700 dark:text-slate-300">{article.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></article>; }
