/**
 * The story behind each studio design, shown on its gallery page: what it
 * borrows from, and the detail worth noticing. Written to be honest about
 * references; nothing here copies another brand's layout or assets.
 */
export interface DesignStory { inspiredBy: string; notice: string }

export const DESIGN_STORIES: Record<string, DesignStory> = {
  terminal: { inspiredBy: "Unix shells and man pages: the most-read documents in software, and some of the plainest.", notice: "The bio is formatted like a manual entry, and work history reads as a git log." },
  blueprint: { inspiredBy: "Cyanotype engineering drawings, the blue prints that gave the word its meaning.", notice: "Dimension lines and a drafting grid make every project feel specified, not decorated." },
  contributions: { inspiredBy: "Developer profile pages and contribution graphs, redrawn from real years of work.", notice: "Each square in the graph is a year of the owner’s career, not a day of commits." },
  swiss: { inspiredBy: "The International Typographic Style of 1950s Zurich and Basel: grids, sans serif, one strong colour.", notice: "Huge numerals carry the structure; everything else gets out of the way." },
  specimen: { inspiredBy: "Type-foundry specimen sheets that show a typeface at every size and weight.", notice: "The owner’s name is set like a specimen, from display size down to caption." },
  salon: { inspiredBy: "Salon-style hangs in 19th-century academies, with frames stacked edge to edge.", notice: "Wall labels and an exhibition list on the back, as a gallery would print them." },
  sketchbook: { inspiredBy: "Artists’ sketchbooks: taped-in prints, pencil notes and coffee rings.", notice: "Handwritten margins make it feel personal without losing legibility." },
  riso: { inspiredBy: "Risograph zines from small-press fairs, printed one ink at a time.", notice: "Two inks overprint with a slight misregistration, like the real machines." },
  darkroom: { inspiredBy: "The photographic darkroom: safelight red, contact sheets and frame numbers.", notice: "Frames are numbered like negatives, so the photographs lead and the interface recedes." },
  horizon: { inspiredBy: "Large-format photobooks and museum walls with one image per wall.", notice: "One photograph at a time, full width, with a slow counter and museum-label captions." },
  monograph: { inspiredBy: "Artists’ monographs: plates, facing captions, a foreword and an index of works.", notice: "The index at the back lists every plate, like the last pages of a photobook." },
  broadsheet: { inspiredBy: "Newspaper front pages: mastheads, datelines and stories in columns.", notice: "The owner’s best pieces run as the day’s stories, above and below the fold." },
  quarterly: { inspiredBy: "Literary quarterlies: a contents page, drop caps, pull quotes and a colophon.", notice: "A colophon at the end credits the type, the way a printed issue does." },
  "plan-section": { inspiredBy: "Architectural drawing sets: title blocks, sheet numbers and scale bars.", notice: "Projects are issued like drawings, each with its own sheet number." },
  material: { inspiredBy: "Material libraries and sample boards in interior design studios.", notice: "Warm swatches and calm serif headlines let photography of spaces breathe." },
  seminar: { inspiredBy: "Good academic homepages: plain, fast and easy to cite.", notice: "Papers, students and teaching are one scan away, which is what visitors come for." },
  notebook: { inspiredBy: "Computational notebooks with numbered input and output cells.", notice: "A career runs top to bottom like cells, with charts as outputs." },
  signal: { inspiredBy: "Analytics dashboards and the habit of leading with the number.", notice: "Sparklines run through the career so results read at a glance." },
  campaign: { inspiredBy: "Billboards and fly-posted streets: condensed type, big numbers, no small talk.", notice: "Work is shown like posters on a wall, with results as headlines." },
  pitch: { inspiredBy: "Pitch decks: one idea per slide, page numbers and a closing ask.", notice: "It scrolls sideways, slide by slide, and ends with a clear request." },
  practice: { inspiredBy: "Independent consultancies that win on clarity and trust.", notice: "Services come with prices, and there is exactly one way to book a call." },
  "liner-notes": { inspiredBy: "Record sleeves: tracklists, credits in small caps and the vinyl itself.", notice: "The vinyl on the page can actually be dragged and spun." },
  "tour-poster": { inspiredBy: "Screen-printed gig posters with tour dates running down the page.", notice: "Chunky type and dates set like a tour, with records pinned beneath." },
  credits: { inspiredBy: "Film title sequences: letterboxed stills, slates and end-credit rolls.", notice: "Collaborators roll past as end credits, the way films thank their crew." },
  storyboard: { inspiredBy: "Production-office corkboards covered in storyboard panels.", notice: "Projects become panels with shot numbers, camera notes and arrows." },
  "annual-report": { inspiredBy: "Company annual reports: the chair’s letter, the year in numbers, milestones.", notice: "A career presented with the seriousness of a board report." },
  keynote: { inspiredBy: "Conference stages under lights, and the speaker pages organisers look for.", notice: "A booking panel for organisers sits beside the list of talks and venues." },
  syllabus: { inspiredBy: "University course catalogues and timetables.", notice: "Projects become assignments and experience becomes a timetable." },
  sanctuary: { inspiredBy: "Calm wellness studios: soft light, rounded forms and plain prices.", notice: "Slow spacing and one gentle way to get in touch, so nobody feels rushed." },
  "training-log": { inspiredBy: "Gym whiteboards and training logs with personal bests chalked up.", notice: "Programmes are priced like a gym board, with PBs front and centre." },
  brief: { inspiredBy: "Pleading paper used in courts, with numbered lines and a case caption.", notice: "Numbered paragraphs and a signature block make it read like a filing." },
  "open-house": { inspiredBy: "Estate-agent window cards, sold stamps and street signs.", notice: "The featured listing’s price tag swings, and neighbourhoods appear as street signs." },
  clinic: { inspiredBy: "Clear, calm practice websites patients can trust.", notice: "Whether you’re accepting patients is shown first, with fees and registration close by." },
  "exercise-book": { inspiredBy: "School exercise books: feint ruled lines, gold stars and red-pen marking.", notice: "Stats are gold stars and worksheets are stapled in." },
  prospectus: { inspiredBy: "Fund prospectuses: key facts boxes, dot leaders and footnotes.", notice: "A track-record table and footnoted references give it real weight." },
  "site-board": { inspiredBy: "Construction-site hoardings and the vans parked outside them.", notice: "The phone number is big enough to read from across the street." },
  carte: { inspiredBy: "Restaurant menu cards with courses, dotted leaders and prices.", notice: "Dishes sit on round plates, and booking is one line at the bottom." },
  lookbook: { inspiredBy: "Fashion magazine spreads set in giant Didone type.", notice: "Numbered looks in a broken grid, with a salon menu and one tap to book." },
  quota: { inspiredBy: "Sales scoreboards, President’s Club pennants and closed-won ledgers.", notice: "Attainment against quota is the first thing you see." },
  datasheet: { inspiredBy: "Electronic component datasheets with pinouts and maximum ratings.", notice: "The career is drawn as a chip pinout, with ratings as skills." },
  "field-report": { inspiredBy: "Charity impact reports: a full-bleed cover, the numbers that matter, a signed letter.", notice: "A dot chart shows the people reached, one dot at a time." },
  residence: { inspiredBy: "Cinematic property films and high-end listing sites.", notice: "The home drifts behind the headline, and listings glide sideways as you scroll." },
  "margin-notes": { inspiredBy: "A good teacher’s whiteboard: doodles, arrows and notes in the margin.", notice: "Doodles draw themselves as you read, and the school year unfolds as you scroll." },
  pulse: { inspiredBy: "Calm clinic waiting rooms and the steady rhythm of a heartbeat monitor.", notice: "The light breathes slowly and the heartbeat line keeps time." },
  counsel: { inspiredBy: "Old-firm letterheads and the quiet confidence of a good brief.", notice: "Headlines unmask line by line and matters stack like files as you scroll." },
  mise: { inspiredBy: "Mise en place: a chef’s station set before service, and the plate turning on the pass.", notice: "The name sits across a spinning plate, and the menu’s dotted lines draw in." },
};
