import type { SectionKey } from "@/lib/portfolio/schema";
import type { FontPairing, Palette, ProfessionId, StyleTag, TemplateDefinition } from "./types";

/** Font stacks for the families each template's stylesheet loads (see components/templates/studio/fonts). */
export const F = {
  instrument: '"Instrument Serif", Georgia, serif',
  grotesk: '"Space Grotesk Variable", system-ui, sans-serif',
  plexMono: '"IBM Plex Mono", ui-monospace, monospace',
  plexSans: '"IBM Plex Sans", system-ui, sans-serif',
  syne: '"Syne Variable", system-ui, sans-serif',
  archivo: '"Archivo Variable", system-ui, sans-serif',
  bricolage: '"Bricolage Grotesque Variable", system-ui, sans-serif',
  newsreader: '"Newsreader Variable", Georgia, serif',
  garamond: '"EB Garamond Variable", Garamond, Georgia, serif',
  cormorant: '"Cormorant Garamond", Garamond, serif',
  playfair: '"Playfair Display Variable", Georgia, serif',
  dmSerif: '"DM Serif Display", Georgia, serif',
  unbounded: '"Unbounded Variable", system-ui, sans-serif',
  interTight: '"Inter Tight Variable", system-ui, sans-serif',
  manrope: '"Manrope Variable", system-ui, sans-serif',
  caveat: '"Caveat Variable", cursive',
  caslon: '"Libre Caslon Text", Georgia, serif',
  bodoni: '"Bodoni Moda Variable", Didot, serif',
  anton: '"Anton", Impact, sans-serif',
  bigShoulders: '"Big Shoulders Display Variable", Impact, sans-serif',
  spaceMono: '"Space Mono", ui-monospace, monospace',
  vt323: '"VT323", ui-monospace, monospace',
  familjen: '"Familjen Grotesk Variable", system-ui, sans-serif',
  youngSerif: '"Young Serif", Georgia, serif',
  gloock: '"Gloock", Georgia, serif',
  literata: '"Literata Variable", Georgia, serif',
  publicSans: '"Public Sans Variable", system-ui, sans-serif',
  franklin: '"Libre Franklin Variable", system-ui, sans-serif',
  courier: '"Courier Prime", "Courier New", monospace',
  workSans: '"Work Sans Variable", system-ui, sans-serif',
  oldStandard: '"Old Standard TT", Georgia, serif',
  fraktur: '"UnifrakturMaguntia", serif',
  bowlby: '"Bowlby One", Impact, sans-serif',
  figtree: '"Figtree Variable", system-ui, sans-serif',
  crimson: '"Crimson Pro Variable", Georgia, serif',
  dmSans: '"DM Sans Variable", system-ui, sans-serif',
  fraunces: '"Fraunces Variable", Georgia, serif',
  jetbrains: '"JetBrains Mono Variable", ui-monospace, monospace',
  hanken: '"Hanken Grotesk Variable", system-ui, sans-serif',
} as const;

const p = (id: string, name: string, bg: string, fg: string, accent: string, muted: string, surface: string): Palette => ({ id, name, bg, fg, accent, muted, surface });
const f = (id: string, name: string, display: string, text: string, mono?: string): FontPairing => ({ id, name, display, text, mono });

interface StudioSpec {
  id: string; name: string; description: string; professions: ProfessionId[]; styles: StyleTag[]; mood: "light" | "dark";
  sections: SectionKey[]; palettes: Palette[]; fonts: FontPairing[]; persona: string; idealFor: string[];
}

const SPECS: StudioSpec[] = [
  // ——— Software & engineering ———
  { id: "terminal", name: "Terminal", persona: "developer", professions: ["developer", "data"], styles: ["Technical", "Minimal"], mood: "dark",
    description: "Your career as a shell session: a prompt, a man-page bio, projects as processes and a git log of jobs.",
    idealFor: ["Backend engineers", "DevOps & SRE", "Systems programmers"], sections: ["about", "projects", "experience", "skills", "highlights", "contact"],
    palettes: [p("phosphor", "Phosphor", "#0c0f0c", "#c8f7c5", "#7dff7a", "#5d7a5c", "#141a14"), p("amber", "Amber CRT", "#120d05", "#ffd9a0", "#ffb000", "#8a6a3d", "#1c150a"), p("solar", "Solarised", "#002b36", "#93a1a1", "#b58900", "#586e75", "#073642")],
    fonts: [f("jetbrains", "JetBrains Mono", F.jetbrains, F.jetbrains, F.jetbrains), f("vt323", "VT323 + Plex", F.vt323, F.plexMono, F.plexMono)] },
  { id: "changelog", name: "Changelog", persona: "developer", professions: ["developer", "student"], styles: ["Minimal", "Technical"], mood: "light",
    description: "Your career written as release notes. Every job is a version, every win is a line item.",
    idealFor: ["Product engineers", "Open-source maintainers", "Front-end developers"], sections: ["about", "experience", "projects", "highlights", "skills", "contact"],
    palettes: [p("paper", "Paper", "#fbfaf6", "#1c1b18", "#e5484d", "#7c7a72", "#f1efe7"), p("graphite", "Graphite", "#17181a", "#e8e6e1", "#4cc38a", "#8b8d91", "#202124"), p("sky", "Sky", "#f3f7fb", "#0f1d2e", "#2f6fed", "#5f7187", "#e6eef7")],
    fonts: [f("grotesk", "Space Grotesk + Plex Mono", F.grotesk, F.grotesk, F.plexMono), f("inter", "Inter Tight + JetBrains", F.interTight, F.interTight, F.jetbrains)] },
  { id: "blueprint", name: "Blueprint", persona: "developer", professions: ["developer", "architecture", "data"], styles: ["Technical", "Artsy"], mood: "dark",
    description: "A drafting-table portfolio: cyanotype grid, dimension lines, and projects drawn up like system diagrams.",
    idealFor: ["Platform engineers", "Solutions architects", "Hardware engineers"], sections: ["about", "projects", "experience", "skills", "stats", "contact"],
    palettes: [p("cyan", "Cyanotype", "#0b3a6e", "#e6f0ff", "#ffffff", "#8fb2db", "#0e4580"), p("graphite", "Graphite sheet", "#e9e7e1", "#25282c", "#d1452f", "#6f7377", "#dcd9d1"), p("night", "Night drafting", "#0d1117", "#c9d6e3", "#58a6ff", "#62748a", "#141b25")],
    fonts: [f("plex", "Plex Mono + Plex Sans", F.plexMono, F.plexSans, F.plexMono), f("space", "Space Mono", F.spaceMono, F.plexSans, F.spaceMono)] },
  { id: "manpage", name: "Manpage", persona: "developer", professions: ["developer", "academic"], styles: ["Technical", "Classic"], mood: "light",
    description: "Typeset like a Unix manual page: NAME, SYNOPSIS, DESCRIPTION. Quietly nerdy and very readable.",
    idealFor: ["Systems engineers", "Security researchers", "CLI tool authors"], sections: ["about", "skills", "projects", "experience", "highlights", "education", "contact"],
    palettes: [p("manual", "Manual", "#fdfcf8", "#111111", "#111111", "#666660", "#f2f0e8"), p("sepia", "Sepia", "#f4ecd8", "#2b2116", "#8b2f1c", "#7a6a55", "#ebe0c6"), p("vt", "VT220", "#101010", "#e6e6e6", "#e6e6e6", "#8a8a8a", "#1a1a1a")],
    fonts: [f("courier", "Courier Prime", F.courier, F.courier, F.courier), f("plex", "Plex Mono", F.plexMono, F.plexMono, F.plexMono)] },
  { id: "contributions", name: "Contributions", persona: "developer", professions: ["developer", "student", "data"], styles: ["Minimal", "Technical"], mood: "light",
    description: "A contribution graph made from your actual years of work, with repositories pinned like a profile done properly.",
    idealFor: ["Open-source developers", "Full-stack developers", "New graduates"], sections: ["about", "projects", "experience", "skills", "highlights", "education", "contact"],
    palettes: [p("moss", "Moss", "#ffffff", "#1f2328", "#1a7f37", "#656d76", "#f6f8fa"), p("dim", "Dim", "#0d1117", "#e6edf3", "#3fb950", "#7d8590", "#161b22"), p("halloween", "Ember", "#fffaf2", "#2b1d0e", "#e36209", "#8a6d4b", "#fbf0e0")],
    fonts: [f("hanken", "Hanken + JetBrains", F.hanken, F.hanken, F.jetbrains), f("plex", "Plex Sans + Mono", F.plexSans, F.plexSans, F.plexMono)] },

  // ——— Design ———
  { id: "swiss", name: "Swiss", persona: "design", professions: ["design", "marketing", "architecture"], styles: ["Bold", "Minimal"], mood: "light",
    description: "International Typographic Style: a strict grid, one red, huge numerals, and nothing that isn’t needed.",
    idealFor: ["Graphic designers", "Brand designers", "Art directors"], sections: ["about", "projects", "services", "experience", "highlights", "testimonials", "contact"],
    palettes: [p("rot", "Rot", "#f2f0eb", "#111111", "#e3241b", "#6b6b66", "#e6e3dc"), p("blau", "Blau", "#f4f4f2", "#0b0b0b", "#1f3fd6", "#6b6b6b", "#e7e7e3"), p("schwarz", "Schwarz", "#0f0f0f", "#f2f0eb", "#ff3b1f", "#8a8a85", "#1b1b1b")],
    fonts: [f("archivo", "Archivo", F.archivo, F.archivo), f("inter", "Inter Tight", F.interTight, F.interTight)] },
  { id: "index", name: "Index", persona: "design", professions: ["design", "photo", "film", "art"], styles: ["Minimal", "Editorial"], mood: "light",
    description: "A plain list of work that comes alive on hover: images follow the cursor, years line up, nothing shouts.",
    idealFor: ["Product designers", "Creative directors", "Studios"], sections: ["projects", "about", "experience", "highlights", "contact"],
    palettes: [p("bone", "Bone", "#efece6", "#141414", "#141414", "#8a877f", "#e4e0d8"), p("ink", "Ink", "#121212", "#ecebe7", "#ecebe7", "#7a7a76", "#1c1c1c"), p("clay", "Clay", "#e9ddd0", "#2a1e16", "#b4532a", "#86715f", "#dfd0bf")],
    fonts: [f("dm", "DM Sans", F.dmSans, F.dmSans), f("instrument", "Instrument Serif + DM Sans", F.instrument, F.dmSans)] },
  { id: "specimen", name: "Specimen", persona: "design", professions: ["design", "art", "marketing"], styles: ["Artsy", "Editorial"], mood: "light",
    description: "Laid out like a type-foundry specimen: glyph sizes, weights, and your work shown as if it were a typeface.",
    idealFor: ["Type designers", "Brand designers", "Illustrators"], sections: ["about", "projects", "skills", "services", "highlights", "contact"],
    palettes: [p("cream", "Cream", "#f3eee3", "#191714", "#ff4f00", "#7b746a", "#e8e1d2"), p("acid", "Acid", "#151515", "#f2f2ea", "#c6ff00", "#8a8a80", "#1f1f1f"), p("lilac", "Lilac", "#ece6f6", "#1d1530", "#5b2be0", "#76698f", "#e0d8ef")],
    fonts: [f("bricolage", "Bricolage Grotesque", F.bricolage, F.bricolage, F.plexMono), f("syne", "Syne + Grotesk", F.syne, F.grotesk, F.plexMono)] },

  // ——— Art ———
  { id: "salon", name: "Salon", persona: "art", professions: ["art", "photo"], styles: ["Artsy", "Classic"], mood: "light",
    description: "A gallery wall hung salon-style, with wall labels, a room plan and an exhibition list on the back.",
    idealFor: ["Painters", "Printmakers", "Sculptors"], sections: ["gallery", "about", "projects", "highlights", "education", "contact"],
    palettes: [p("gallery", "White cube", "#f4f2ee", "#1b1a18", "#9b2c1f", "#7d7a73", "#ffffff"), p("green", "Museum green", "#2f4a3e", "#efe9dc", "#e2b45b", "#a9b8ad", "#3a594b"), p("oxblood", "Oxblood", "#5c1d1d", "#f3e8dc", "#e9c27d", "#c99a8f", "#6b2626")],
    fonts: [f("cormorant", "Cormorant + Work Sans", F.cormorant, F.workSans), f("garamond", "EB Garamond", F.garamond, F.garamond)] },
  { id: "sketchbook", name: "Sketchbook", persona: "art", professions: ["art", "design", "student"], styles: ["Playful", "Artsy"], mood: "light",
    description: "A sketchbook spread with taped-in work, pencil notes in the margins and a hand-written bio.",
    idealFor: ["Illustrators", "Comic artists", "Art students"], sections: ["about", "gallery", "projects", "skills", "highlights", "contact"],
    palettes: [p("kraft", "Cream page", "#f5efe1", "#2a2722", "#d1495b", "#857c6c", "#fffaf0"), p("grid", "Graph paper", "#f4f7f6", "#1e2b2a", "#2a7f62", "#6a7e7a", "#ffffff"), p("night", "Night page", "#22201d", "#ece4d4", "#f2b134", "#9a8f7c", "#2d2a26")],
    fonts: [f("caveat", "Caveat + Literata", F.caveat, F.literata), f("caveat-grotesk", "Caveat + Work Sans", F.caveat, F.workSans)] },
  { id: "riso", name: "Riso", persona: "art", professions: ["art", "design", "music"], styles: ["Playful", "Artsy", "Bold"], mood: "light",
    description: "Printed in two inks: overprinted shapes, slight misregistration and grain, like a zine you’d buy at a fair.",
    idealFor: ["Illustrators", "Zine makers", "Independent publishers"], sections: ["about", "gallery", "projects", "services", "highlights", "contact"],
    palettes: [p("pink-blue", "Fluo pink & blue", "#f3eee3", "#0078bf", "#ff48b0", "#5a7fa3", "#ebe4d6"), p("yellow-green", "Yellow & green", "#f6f0e4", "#00a95c", "#ffd400", "#5a8f6f", "#ede5d3"), p("red-teal", "Red & teal", "#f1ece2", "#00838a", "#ff665e", "#5d8a8c", "#e7e0d2")],
    fonts: [f("unbounded", "Unbounded + Space Mono", F.unbounded, F.spaceMono), f("bowlby", "Bowlby + Grotesk", F.bowlby, F.grotesk)] },

  // ——— Photography ———
  { id: "darkroom", name: "Darkroom", persona: "photo", professions: ["photo", "film"], styles: ["Minimal", "Artsy"], mood: "dark",
    description: "Black walls, safelight red and frames numbered like a contact sheet. The photographs do the talking.",
    idealFor: ["Photographers", "Photojournalists", "Cinematographers"], sections: ["gallery", "about", "projects", "services", "highlights", "testimonials", "contact"],
    palettes: [p("safelight", "Safelight", "#0b0b0b", "#e9e5dc", "#e2382c", "#77736b", "#151515"), p("selenium", "Selenium", "#121418", "#dfe3e8", "#9db4c9", "#6b737d", "#1a1d22"), p("fiber", "Fibre print", "#ece8df", "#1a1917", "#a3341f", "#7f7a70", "#e2ddd1")],
    fonts: [f("grotesk", "Space Grotesk + Mono", F.grotesk, F.grotesk, F.spaceMono), f("instrument", "Instrument Serif + Grotesk", F.instrument, F.grotesk, F.spaceMono)] },
  { id: "horizon", name: "Horizon", persona: "photo", professions: ["photo", "art", "architecture"], styles: ["Minimal"], mood: "light",
    description: "One image at a time, full width, with a slow counter and captions set like museum labels.",
    idealFor: ["Landscape photographers", "Fine-art photographers", "Visual artists"], sections: ["gallery", "about", "highlights", "services", "contact"],
    palettes: [p("mist", "Mist", "#eceae5", "#1d1d1b", "#1d1d1b", "#8b8982", "#e1ded7"), p("dusk", "Dusk", "#1a1a1d", "#e7e3dc", "#d8a26b", "#7f7a73", "#232327"), p("snow", "Snow", "#fafafa", "#121212", "#3b5bdb", "#8a8a8a", "#f0f0f0")],
    fonts: [f("manrope", "Manrope", F.manrope, F.manrope), f("newsreader", "Newsreader + Manrope", F.newsreader, F.manrope)] },
  { id: "monograph", name: "Monograph", persona: "photo", professions: ["photo", "art", "writing"], styles: ["Editorial", "Classic"], mood: "light",
    description: "A photobook: plates with facing captions, a foreword, and an index of works at the back.",
    idealFor: ["Documentary photographers", "Editorial photographers", "Artists with a body of work"], sections: ["about", "gallery", "projects", "highlights", "testimonials", "contact"],
    palettes: [p("linen", "Linen", "#f1ede4", "#1f1c17", "#7e2d1a", "#857e71", "#e7e1d4"), p("charcoal", "Charcoal", "#1c1b19", "#ebe6dc", "#c49a5a", "#8b857a", "#252421"), p("chalk", "Chalk", "#fbfbf8", "#161616", "#2a4d69", "#848484", "#f0f0ec")],
    fonts: [f("caslon", "Libre Caslon", F.caslon, F.caslon), f("bodoni", "Bodoni + Work Sans", F.bodoni, F.workSans)] },

  // ——— Writing ———
  { id: "broadsheet", name: "Broadsheet", persona: "writing", professions: ["writing", "marketing", "academic"], styles: ["Classic", "Editorial"], mood: "light",
    description: "A newspaper front page: masthead, dateline, columns, and your best pieces as the day’s stories.",
    idealFor: ["Journalists", "Columnists", "Editors"], sections: ["about", "highlights", "projects", "experience", "testimonials", "contact"],
    palettes: [p("newsprint", "Newsprint", "#f1ece1", "#161512", "#a01c1c", "#6e685c", "#e6e0d1"), p("pink", "Salmon pages", "#f6e3d6", "#1b1612", "#1b1612", "#7d6656", "#f0d6c4"), p("night", "Late edition", "#161512", "#ede6d6", "#e0a64a", "#8c8577", "#1f1d19")],
    fonts: [f("oldstandard", "Old Standard + Fraktur masthead", F.oldStandard, F.oldStandard), f("newsreader", "Newsreader", F.newsreader, F.newsreader)] },
  { id: "quarterly", name: "Quarterly", persona: "writing", professions: ["writing", "academic", "art"], styles: ["Editorial", "Artsy"], mood: "light",
    description: "A literary magazine issue: contents page, drop caps, pull quotes and a colophon.",
    idealFor: ["Essayists", "Novelists", "Poets & editors"], sections: ["about", "projects", "highlights", "testimonials", "experience", "contact"],
    palettes: [p("terracotta", "Terracotta", "#f4ece2", "#221a14", "#c94f2c", "#86766a", "#ebdfd1"), p("olive", "Olive", "#eeeee2", "#1f2216", "#5d6b2f", "#7b7d6c", "#e3e3d3"), p("ink", "Midnight issue", "#16181d", "#ece6da", "#e7a868", "#868a92", "#1e2128")],
    fonts: [f("fraunces", "Fraunces + Literata", F.fraunces, F.literata), f("playfair", "Playfair + Crimson", F.playfair, F.crimson)] },

  // ——— Architecture & interiors ———
  { id: "plan-section", name: "Plan & Section", persona: "architecture", professions: ["architecture", "design"], styles: ["Technical", "Minimal"], mood: "light",
    description: "Drawing-set rigour: a title block, sheet numbers, a scale bar and projects issued like drawings.",
    idealFor: ["Architects", "Landscape architects", "Urban designers"], sections: ["about", "projects", "services", "experience", "highlights", "testimonials", "contact"],
    palettes: [p("trace", "Tracing paper", "#f3f1ea", "#1c1c1a", "#c2410c", "#7a7870", "#e8e5dc"), p("kraft", "Kraft", "#d9c9a8", "#2b2418", "#1d4ed8", "#6b5d43", "#cdbb96"), p("ink", "Ink on black", "#141414", "#e9e7e1", "#f59e0b", "#7c7b77", "#1d1d1d")],
    fonts: [f("plex", "Plex Sans + Mono", F.plexSans, F.plexSans, F.plexMono), f("familjen", "Familjen + Space Mono", F.familjen, F.familjen, F.spaceMono)] },
  { id: "material", name: "Material", persona: "architecture", professions: ["architecture", "design", "art"], styles: ["Minimal", "Editorial"], mood: "light",
    description: "Warm and tactile: material swatches, generous photography and calm serif headlines for spaces that feel good.",
    idealFor: ["Interior designers", "Furniture makers", "Residential architects"], sections: ["about", "projects", "gallery", "services", "testimonials", "contact"],
    palettes: [p("oak", "Oak & lime", "#efe8dc", "#2a241c", "#a26a3a", "#857a6a", "#e4d9c7"), p("stone", "Stone", "#e6e3dd", "#25231f", "#55634f", "#7f7b72", "#d9d5cd"), p("walnut", "Walnut", "#2c221b", "#efe6d8", "#c99460", "#a2917d", "#382c23")],
    fonts: [f("gloock", "Gloock + Manrope", F.gloock, F.manrope), f("cormorant", "Cormorant + Manrope", F.cormorant, F.manrope)] },

  // ——— Research & academia ———
  { id: "preprint", name: "Preprint", persona: "academic", professions: ["academic", "data", "writing"], styles: ["Classic", "Technical"], mood: "light",
    description: "Your homepage as a paper: title, abstract, numbered sections and a proper references list.",
    idealFor: ["Researchers", "PhD students", "Lecturers"], sections: ["about", "highlights", "projects", "experience", "education", "services", "contact"],
    palettes: [p("latex", "LaTeX", "#fdfdfb", "#111111", "#a51c30", "#5f5f5a", "#f3f3ef"), p("arxiv", "Archive", "#f6f4ee", "#1a1a1a", "#b31b1b", "#6b685f", "#ebe8df"), p("dark", "Night reading", "#16171a", "#e3e1dc", "#8ab4f8", "#8b8c90", "#1e1f23")],
    fonts: [f("crimson", "Crimson Pro", F.crimson, F.crimson, F.plexMono), f("garamond", "EB Garamond", F.garamond, F.garamond, F.plexMono)] },
  { id: "seminar", name: "Seminar", persona: "academic", professions: ["academic", "student", "leadership"], styles: ["Minimal", "Classic"], mood: "light",
    description: "A clear academic homepage: who you are, what you work on, papers, students and teaching, all easy to scan.",
    idealFor: ["Professors", "Postdocs", "Research leads"], sections: ["about", "highlights", "projects", "services", "experience", "education", "stats", "contact"],
    palettes: [p("college", "College", "#fbfaf7", "#1d2433", "#1f4e8c", "#667085", "#f1efe9"), p("green", "Quad", "#f7f8f4", "#1c2a22", "#2f6b47", "#64735f", "#ebeee5"), p("plum", "Plum", "#faf7f9", "#2a1b2c", "#7a2e72", "#776a79", "#f1eaf0")],
    fonts: [f("literata", "Literata + Public Sans", F.literata, F.publicSans), f("newsreader", "Newsreader + Public Sans", F.newsreader, F.publicSans)] },

  // ——— Data & AI ———
  { id: "notebook", name: "Notebook", persona: "data", professions: ["data", "developer", "academic"], styles: ["Technical", "Playful"], mood: "light",
    description: "A computational notebook: In[1] / Out[1] cells, charts as outputs and your career run top to bottom.",
    idealFor: ["Data scientists", "ML engineers", "Analysts"], sections: ["about", "projects", "stats", "experience", "skills", "highlights", "education", "contact"],
    palettes: [p("jupyter", "Notebook", "#ffffff", "#1f2328", "#f37626", "#6e7781", "#f6f8fa"), p("colab", "Dark kernel", "#1e1e1e", "#d4d4d4", "#4fc1ff", "#858585", "#252526"), p("paper", "Paper", "#faf8f2", "#22201c", "#3d6b45", "#7a766c", "#f0ece2")],
    fonts: [f("jetbrains", "JetBrains Mono + Inter", F.interTight, F.interTight, F.jetbrains), f("plex", "Plex Sans + Mono", F.plexSans, F.plexSans, F.plexMono)] },
  { id: "signal", name: "Signal", persona: "data", professions: ["data", "marketing", "leadership", "consulting"], styles: ["Bold", "Technical"], mood: "dark",
    description: "Numbers first: oversized metrics, sparklines through your career and results stated plainly.",
    idealFor: ["Data leads", "Growth analysts", "Quant-minded operators"], sections: ["stats", "about", "projects", "experience", "skills", "testimonials", "contact"],
    palettes: [p("oscilloscope", "Oscilloscope", "#0b0d10", "#e8edf2", "#00e0a4", "#6b7785", "#12161b"), p("infrared", "Infrared", "#120a0a", "#f4e9e6", "#ff5a36", "#8a706a", "#1d1111"), p("print", "Print", "#f5f4ef", "#121212", "#1b4bff", "#6d6d68", "#e9e8e2")],
    fonts: [f("unbounded", "Unbounded + Inter", F.unbounded, F.interTight, F.jetbrains), f("grotesk", "Space Grotesk", F.grotesk, F.grotesk, F.spaceMono)] },

  // ——— Marketing ———
  { id: "campaign", name: "Campaign", persona: "marketing", professions: ["marketing", "design", "leadership"], styles: ["Bold", "Playful"], mood: "light",
    description: "Billboard energy: giant condensed type, results in big numbers, and work shown like posters on a wall.",
    idealFor: ["Marketers", "Creative directors", "Copywriters"], sections: ["stats", "projects", "about", "experience", "testimonials", "highlights", "services", "contact"],
    palettes: [p("volt", "Volt", "#f2f0e9", "#101010", "#d7ff3a", "#6c6a62", "#101010"), p("tomato", "Tomato", "#fff4ea", "#1a0f0a", "#ff4b2b", "#836c5e", "#1a0f0a"), p("cobalt", "Cobalt", "#eef0ff", "#0b0f2e", "#1b2bd6", "#5f6488", "#0b0f2e")],
    fonts: [f("anton", "Anton + Inter", F.anton, F.interTight), f("bigshoulders", "Big Shoulders + Archivo", F.bigShoulders, F.archivo)] },
  { id: "pitch", name: "Pitch", persona: "marketing", professions: ["marketing", "leadership", "consulting"], styles: ["Editorial", "Bold"], mood: "light",
    description: "A slide deck you scroll sideways: one idea per slide, page numbers, and a closing ask.",
    idealFor: ["Strategists", "Founders", "Consultants"], sections: ["about", "stats", "projects", "experience", "testimonials", "services", "contact"],
    palettes: [p("deck", "Deck", "#f5f1e8", "#151515", "#c2410c", "#7a7468", "#151515"), p("board", "Boardroom", "#101418", "#eef1f4", "#f5b301", "#7d8792", "#1a2027"), p("mint", "Mint", "#eaf4ef", "#0f2a1f", "#0f9d58", "#5f7a6c", "#0f2a1f")],
    fonts: [f("fraunces", "Fraunces + Grotesk", F.fraunces, F.grotesk), f("dmserif", "DM Serif + DM Sans", F.dmSerif, F.dmSans)] },

  // ——— Consulting & freelance ———
  { id: "practice", name: "Practice", persona: "consulting", professions: ["consulting", "wellness", "design", "leadership"], styles: ["Minimal", "Classic"], mood: "light",
    description: "A calm, trustworthy practice site: services with prices, proof, and one clear way to book a call.",
    idealFor: ["Consultants", "Fractional executives", "Freelancers"], sections: ["about", "services", "stats", "projects", "testimonials", "experience", "highlights", "contact"],
    palettes: [p("sage", "Sage", "#f4f3ee", "#1f2a24", "#3c6e57", "#6e766f", "#e8e9e1"), p("navy", "Navy", "#f6f5f1", "#14213d", "#b5833b", "#68708a", "#ebe9e1"), p("ink", "Evening", "#151a18", "#e9ebe6", "#9ccfb4", "#88918b", "#1d2421")],
    fonts: [f("youngserif", "Young Serif + Figtree", F.youngSerif, F.figtree), f("newsreader", "Newsreader + Figtree", F.newsreader, F.figtree)] },
  { id: "ledger", name: "Ledger", persona: "consulting", professions: ["consulting", "leadership", "data"], styles: ["Classic", "Technical"], mood: "light",
    description: "A finance-grade layout: ruled tables, tabular numbers, a statement of services and a clean signature.",
    idealFor: ["Accountants & CFOs", "Lawyers", "Financial advisers"], sections: ["about", "stats", "services", "projects", "experience", "testimonials", "highlights", "contact"],
    palettes: [p("green", "Ledger green", "#f3f2ea", "#1b2a22", "#0f5132", "#6c7468", "#e6e8dc"), p("ivory", "Ivory & navy", "#faf8f1", "#14213d", "#14213d", "#6e7487", "#efece2"), p("burgundy", "Burgundy", "#f6f1ec", "#2a1418", "#7d1d2c", "#7a676a", "#ece3db")],
    fonts: [f("caslon", "Caslon + Franklin", F.caslon, F.franklin, F.plexMono), f("crimson", "Crimson + Franklin", F.crimson, F.franklin, F.plexMono)] },

  // ——— Music ———
  { id: "liner-notes", name: "Liner Notes", persona: "music", professions: ["music", "film", "art"], styles: ["Artsy", "Editorial"], mood: "dark",
    description: "A record sleeve: releases as tracklists, credits in small caps, and a spinning vinyl you can actually drag.",
    idealFor: ["Musicians", "Producers", "Composers"], sections: ["about", "projects", "highlights", "experience", "stats", "contact"],
    palettes: [p("vinyl", "Black vinyl", "#121110", "#efe7d8", "#e8c07a", "#8f877a", "#1b1a18"), p("sleeve", "Paper sleeve", "#e9e1d0", "#1d1a16", "#b0381e", "#7f7564", "#ded4bf"), p("ocean", "Tide", "#0d2a3a", "#e6efe9", "#e8c07a", "#8aa4a8", "#11364a")],
    fonts: [f("syne", "Syne + Grotesk", F.syne, F.grotesk, F.spaceMono), f("instrument", "Instrument Serif + Grotesk", F.instrument, F.grotesk, F.spaceMono)] },
  { id: "tour-poster", name: "Tour Poster", persona: "music", professions: ["music", "art", "film"], styles: ["Bold", "Playful"], mood: "light",
    description: "A screen-printed gig poster: chunky type, tour dates down the page and records pinned beneath.",
    idealFor: ["Bands", "DJs", "Performers"], sections: ["highlights", "projects", "about", "gallery", "contact"],
    palettes: [p("red", "Red on cream", "#f2e3c6", "#1d1d1b", "#d0341f", "#6f6455", "#e9d6b1"), p("blue", "Blue on pink", "#f7d9d3", "#1b1b1b", "#2733c5", "#7b5c57", "#efc7bf"), p("black", "Gold on black", "#121212", "#f2e9d8", "#f2b705", "#8a8478", "#1d1d1d")],
    fonts: [f("bowlby", "Bowlby One + Grotesk", F.bowlby, F.grotesk), f("anton", "Anton + Grotesk", F.anton, F.grotesk)] },

  // ——— Film & motion ———
  { id: "credits", name: "Credits", persona: "film", professions: ["film", "music", "photo"], styles: ["Artsy", "Minimal"], mood: "dark",
    description: "Cinematic: letterboxed stills, a slate for each film and an end-credits roll of collaborators.",
    idealFor: ["Directors", "Cinematographers", "Editors"], sections: ["projects", "about", "highlights", "experience", "testimonials", "contact"],
    palettes: [p("noir", "Noir", "#050505", "#ecebe6", "#e0b14f", "#77756e", "#0f0f0f"), p("teal", "Teal & orange", "#071417", "#e6eeec", "#ff8c42", "#6c8584", "#0c1f23"), p("silver", "Silver screen", "#d9d7d2", "#151515", "#151515", "#6b6964", "#cfccc6")],
    fonts: [f("courier", "Courier + Inter", F.courier, F.interTight, F.courier), f("bodoni", "Bodoni + Inter", F.bodoni, F.interTight, F.courier)] },
  { id: "storyboard", name: "Storyboard", persona: "film", professions: ["film", "design", "art"], styles: ["Artsy", "Playful"], mood: "light",
    description: "Projects as storyboard panels with shot numbers, camera notes and arrows, on a production-office corkboard.",
    idealFor: ["Animators", "Motion designers", "Commercial directors"], sections: ["about", "projects", "experience", "skills", "highlights", "contact"],
    palettes: [p("board", "Production white", "#f4f2ec", "#1c1c1c", "#e8452c", "#7c7a73", "#ffffff"), p("cork", "Cork", "#c9a982", "#1e1810", "#1f4fd8", "#5a4630", "#f7f2e8"), p("dark", "Edit suite", "#1a1b1e", "#e7e5df", "#ffc53d", "#8a8b8f", "#24262a")],
    fonts: [f("grotesk", "Grotesk + Caveat notes", F.grotesk, F.grotesk, F.caveat), f("familjen", "Familjen + Caveat", F.familjen, F.familjen, F.caveat)] },

  // ——— Founders & executives ———
  { id: "annual-report", name: "Annual Report", persona: "leadership", professions: ["leadership", "consulting", "academic"], styles: ["Classic", "Editorial"], mood: "light",
    description: "A company annual report about you: a letter, the year in numbers, milestones and the board you sit on.",
    idealFor: ["Founders & CEOs", "Executives", "Board members"], sections: ["about", "stats", "experience", "highlights", "projects", "testimonials", "education", "services", "contact"],
    palettes: [p("navy", "Navy & cream", "#f6f2ea", "#0f1b33", "#b08a3e", "#69718a", "#ebe4d6"), p("forest", "Forest", "#f2f2ec", "#14261c", "#1f6b43", "#677164", "#e4e6db"), p("slate", "Slate", "#16191d", "#e9e7e2", "#c8a96a", "#8a8d92", "#1e2227")],
    fonts: [f("playfair", "Playfair + Franklin", F.playfair, F.franklin), f("caslon", "Caslon + Franklin", F.caslon, F.franklin)] },
  { id: "keynote", name: "Keynote", persona: "leadership", professions: ["leadership", "marketing", "wellness", "consulting"], styles: ["Bold", "Editorial"], mood: "dark",
    description: "A stage under lights: one big quote, a talks list with venues and a booking panel for organisers.",
    idealFor: ["Speakers", "Authors", "Thought leaders"], sections: ["about", "highlights", "projects", "testimonials", "services", "stats", "contact"],
    palettes: [p("stage", "Stage", "#0a0a0c", "#f2efe8", "#ff5b2e", "#7f7c76", "#141417"), p("spotlight", "Spotlight", "#101820", "#f4f1ea", "#f2c14e", "#7d8894", "#18222c"), p("daylight", "Daylight", "#f3efe7", "#141414", "#e2381f", "#77736b", "#e9e3d7")],
    fonts: [f("dmserif", "DM Serif + Inter", F.dmSerif, F.interTight), f("bricolage", "Bricolage", F.bricolage, F.bricolage)] },

  // ——— Students ———
  { id: "syllabus", name: "Syllabus", persona: "student", professions: ["student", "developer", "design", "academic"], styles: ["Playful", "Minimal"], mood: "light",
    description: "A friendly course catalogue: your degree, projects as assignments, a timetable of experience and a report card.",
    idealFor: ["Students", "New graduates", "Bootcamp graduates"], sections: ["about", "projects", "experience", "education", "skills", "highlights", "stats", "contact"],
    palettes: [p("notebook", "Notebook", "#fbf8f1", "#1f2430", "#2f5bea", "#6b7280", "#ffffff"), p("highlighter", "Highlighter", "#fffdf5", "#1d1d1d", "#ff7a00", "#6e6e6e", "#fff3c4"), p("chalk", "Chalkboard", "#233127", "#eef2ea", "#ffe066", "#a7b4a8", "#2c3d31")],
    fonts: [f("bricolage", "Bricolage + Plex Mono", F.bricolage, F.bricolage, F.plexMono), f("figtree", "Figtree + Caveat", F.figtree, F.figtree, F.caveat)] },

  // ——— Wellness & coaching ———
  { id: "sanctuary", name: "Sanctuary", persona: "wellness", professions: ["wellness", "consulting"], styles: ["Minimal", "Classic"], mood: "light",
    description: "Soft, slow and reassuring: breathing space, rounded shapes, clear prices and a gentle way to get in touch.",
    idealFor: ["Therapists", "Coaches", "Yoga & breathwork teachers"], sections: ["about", "services", "testimonials", "education", "experience", "highlights", "contact"],
    palettes: [p("sage", "Sage", "#eef0e8", "#22302a", "#6f8f7a", "#78837c", "#e2e6da"), p("sand", "Sand", "#f5eee4", "#33291f", "#c08454", "#8a7b6a", "#ece1d1"), p("dusk", "Dusk", "#2a2733", "#ece6ef", "#c9a7d9", "#9a93a3", "#34303f")],
    fonts: [f("fraunces", "Fraunces soft + Figtree", F.fraunces, F.figtree), f("cormorant", "Cormorant + Figtree", F.cormorant, F.figtree)] },
  { id: "training-log", name: "Training Log", persona: "trainer", professions: ["wellness", "student"], styles: ["Bold", "Playful"], mood: "dark",
    description: "Athletic and direct: condensed type, personal bests, programmes priced like a gym board.",
    idealFor: ["Personal trainers", "Coaches", "Athletes"], sections: ["stats", "about", "services", "testimonials", "highlights", "experience", "contact"],
    palettes: [p("chalk", "Chalk & volt", "#0f0f0f", "#f1f1ec", "#c8ff2e", "#7a7a75", "#1a1a1a"), p("track", "Track red", "#f0ece4", "#141414", "#e2382c", "#76726b", "#e4dfd4"), p("pool", "Pool blue", "#04223a", "#e8f3fa", "#3ad1ff", "#6d8ea6", "#0a2e4b")],
    fonts: [f("bigshoulders", "Big Shoulders + Archivo", F.bigShoulders, F.archivo, F.spaceMono), f("anton", "Anton + Archivo", F.anton, F.archivo, F.spaceMono)] },
];

const CATEGORY: Partial<Record<ProfessionId, TemplateDefinition["category"]>> = { developer: "Developer", data: "Developer", student: "Developer", design: "Creative", art: "Creative", photo: "Creative", music: "Creative", film: "Creative", architecture: "Creative" };
const LEGACY_STYLE: Record<StyleTag, TemplateDefinition["style"]> = { Minimal: "Minimal", Editorial: "Editorial", Bold: "Modern", Technical: "Modern", Artsy: "Editorial", Classic: "Classic", Playful: "Modern" };

export const studioCatalog: TemplateDefinition[] = SPECS.map((spec) => ({
  ...spec,
  category: CATEGORY[spec.professions[0]] ?? "Professional",
  author: "Formora Studio",
  createdAt: "2026-10-02",
  style: LEGACY_STYLE[spec.styles[0]],
  tags: [spec.mood === "dark" ? "Dark" : "Light", ...spec.styles],
  editor: "standard",
  colorThemes: false,
  collection: "studio",
}));
