"use client";

import Link from "next/link";
import { LogIn, MessageSquare, Send, Star } from "lucide-react";
import { useSession } from "next-auth/react";
import { useState } from "react";

export default function TemplateFeedback({ templateName }: { templateName: string }) {
  const { data: session } = useSession(); const [rating, setRating] = useState(0); const [comment, setComment] = useState(""); const [message, setMessage] = useState("");
  function submit() { if (!rating || !comment.trim()) { setMessage("Choose a rating and write a comment first."); return; } setMessage("Your review has not been published: SQL storage will be connected later, so Formora does not show dummy reviews."); }
  return <section className="mx-auto max-w-4xl px-5 py-12 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-700">Community feedback</p><h2 className="mt-2 text-3xl font-black">Rate {templateName}</h2><p className="mt-3 text-slate-600 dark:text-slate-400">There are no ratings or comments yet. This section is ready for real, SQL-backed reviews only.</p>{!session?.user ? <Link href="/login" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-700 px-4 py-3 text-sm font-bold text-white"><LogIn size={16} /> Sign in to leave a review</Link> : <div className="mt-6 rounded-2xl border border-slate-200 p-5 dark:border-white/10"><div className="flex gap-1">{Array.from({ length: 5 }, (_, index) => <button key={index} type="button" onClick={() => setRating(index + 1)} className={index < rating ? "text-amber-400" : "text-slate-300"} aria-label={`${index + 1} stars`}><Star size={27} fill="currentColor" /></button>)}</div><textarea value={comment} onChange={(e) => setComment(e.target.value)} maxLength={1000} rows={4} placeholder="What did you like about this template?" className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm dark:border-white/10 dark:bg-white/5" /><button onClick={submit} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-violet-700 px-3 py-2 text-sm font-bold text-white"><Send size={15} /> Post review</button>{message && <p className="mt-3 text-xs text-amber-700 dark:text-amber-300">{message}</p>}</div>}<div className="mt-6 rounded-2xl border border-dashed border-slate-300 p-6 text-center dark:border-white/15"><MessageSquare className="mx-auto text-slate-400" size={24} /><p className="mt-2 font-bold">No comments yet</p></div></section>;
}
